Repository containerd/containerd, pull requests merged in 2018-12, with the labels that each got.

#2854 Allow Kill in stopped state
  runtime/v1/linux/proc/init_state.go
Labels: cherry-pick/1.2.x

#2856 [release 1.2] Kill should still work in stopped state.
  runtime/v1/linux/proc/init_state.go
Labels: cherry-picked/1.2.x

#2857 Update runc to 96ec2177ae841256168fcf76954f7177af
  runtime/v1/linux/proc/utils.go
  vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
Labels: cherry-pick/1.1.x, cherry-pick/1.2.x

#2877 Add timeout and cancel to shim fifo open
  runtime/v1/linux/proc/exec.go
  runtime/v1/linux/proc/init.go
Labels: cherry-pick/1.0.x, cherry-pick/1.1.x, cherry-pick/1.2.x
