Repository containerd/containerd, pull requests merged in 2018-11, with the labels that each got.

#2757 [release/1.1] Backport: modify lock location of exec delete avoid exec hang
  linux/proc/exec_state.go
  linux/shim/service.go
Labels: cherry-pick/1.1.x

#2769 enhance: update v1/v2 runtime
  runtime/v1/shim/service.go
  runtime/v2/runc/service.go
  runtime/v2/shim/shim_unix.go
Labels: cherry-pick/1.2.x

#2788 Update runc to 10d38b660a77168360df3522881e2dc2be
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/README.md
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
Labels: cherry-pick/1.2.x

#2773 Fix process locking and state management
  runtime/proc/proc.go
  runtime/v1/linux/proc/exec.go
  runtime/v1/linux/proc/exec_state.go
  runtime/v1/linux/proc/init.go
  runtime/v1/linux/proc/init_state.go
Labels: cherry-pick/1.2.x

#2800 Revert v2 dropped events
  runtime/v2/shim/reaper_unix.go
Labels: cherry-pick/1.2.x

#2811 Lock `KillAll`.
  runtime/v1/linux/proc/init.go
Labels: cherry-pick/1.1.x, cherry-pick/1.2.x

#2807 fix pipe in broken may cause shim lock forever
  runtime/v1/shim/service_linux.go
  runtime/v2/runc/service_linux.go
Labels: cherry-pick/1.1.x, cherry-pick/1.2.x

#2801 [release/1.2] Update runc to 10d38b660a77168360df3522881e2dc2be5056bd
  vendor.conf
  vendor/github.com/opencontainers/runc/README.md
  vendor/github.com/opencontainers/runc/libcontainer/README.md
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
Labels: cherry-picked/1.2.x

#2803 [release/1.2] Fix process locking and state management
  runtime/proc/proc.go
  runtime/v1/linux/proc/exec.go
  runtime/v1/linux/proc/exec_state.go
  runtime/v1/linux/proc/init.go
  runtime/v1/linux/proc/init_state.go
Labels: cherry-picked/1.2.x

#2818 [release/1.1] Cherrypick: Lock `KillAll`.
  linux/proc/init.go
Labels: cherry-picked/1.1.x

#2817 [release/1.2] Cherrypick: Lock `KillAll`.
  runtime/v1/linux/proc/init.go
Labels: cherry-picked/1.2.x
