Repository containerd/containerd, pull requests merged in 2018-03, with the labels that each got.

#2163 archive: fix logic for skipping mknod when running in userns
  archive/tar_unix.go
Labels: cherry-pick/1.0.x

#2187 Handle SIGPIPE in shims
  cmd/containerd-shim/main_unix.go
  cmd/containerd-shim/shim_linux.go
Labels: cherry-pick/1.0.x

#2182 linux: fix runtime-root propagation
  client_test.go
  daemon_config_linux_test.go
  daemon_test.go
  linux/bundle.go
  linux/runtime.go
Labels: cherry-pick/1.0.x

#2198 [release/1.0] Update cgroups vendor for licenses/bug fix
  vendor.conf
  vendor/github.com/containerd/cgroups/blkio.go
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/control.go
  vendor/github.com/containerd/cgroups/cpu.go
  vendor/github.com/containerd/cgroups/cpuacct.go
  vendor/github.com/containerd/cgroups/cpuset.go
  vendor/github.com/containerd/cgroups/devices.go
  vendor/github.com/containerd/cgroups/errors.go
  vendor/github.com/containerd/cgroups/freezer.go
  vendor/github.com/containerd/cgroups/hierarchy.go
  vendor/github.com/containerd/cgroups/hugetlb.go
  vendor/github.com/containerd/cgroups/memory.go
  vendor/github.com/containerd/cgroups/named.go
  vendor/github.com/containerd/cgroups/net_cls.go
  vendor/github.com/containerd/cgroups/net_prio.go
  vendor/github.com/containerd/cgroups/paths.go
  vendor/github.com/containerd/cgroups/perf_event.go
  vendor/github.com/containerd/cgroups/pids.go
  vendor/github.com/containerd/cgroups/state.go
  vendor/github.com/containerd/cgroups/subsystem.go
  vendor/github.com/containerd/cgroups/systemd.go
  vendor/github.com/containerd/cgroups/ticks.go
  vendor/github.com/containerd/cgroups/utils.go
  vendor/github.com/containerd/cgroups/v1.go
Labels: cherry-pick/1.0.x

#1833 snapshots/overlay: add overlay cleanup
  metadata/snapshot.go
  snapshots/overlay/overlay.go
  snapshots/storage/bolt.go
Labels: status/needs-attention

#2096 containerd: include zfs plugin by default
  cmd/containerd/builtins_linux.go
  vendor.conf
  vendor/github.com/containerd/zfs/LICENSE
  vendor/github.com/containerd/zfs/README.md
  vendor/github.com/containerd/zfs/zfs.go
  vendor/github.com/mistifyio/go-zfs/LICENSE
  vendor/github.com/mistifyio/go-zfs/README.md
  vendor/github.com/mistifyio/go-zfs/error.go
  vendor/github.com/mistifyio/go-zfs/utils.go
  vendor/github.com/mistifyio/go-zfs/utils_notsolaris.go
  vendor/github.com/mistifyio/go-zfs/utils_solaris.go
  vendor/github.com/mistifyio/go-zfs/zfs.go
  vendor/github.com/mistifyio/go-zfs/zpool.go
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/node_js.go
  vendor/github.com/pborman/uuid/node_net.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
Labels: kind/enhancement

#2214 Fixes a default config bug of gc scheduler
  gc/scheduler/scheduler.go
Labels: cherry-pick/1.0.x

#2222 Ignore sockets when creating a tar stream of a layer
  archive/tar.go
  archive/tar_test.go
  vendor.conf
  vendor/github.com/containerd/continuity/fs/fstest/file.go
  vendor/github.com/containerd/continuity/fs/fstest/testsuite.go
Labels: cherry-pick/1.0.x

#2229 linux/prox: timeout fifo creation
  linux/proc/exec.go
Labels: cherry-pick/1.0.x

#2239 Fix typo in metadata test typeurl string
  metadata/containers_test.go
Labels: cherry-pick/1.0.x

#2255 Return a better error message is unix socket path is too long.
  cmd/containerd-shim/main_unix.go
  linux/shim/client/client.go
  sys/socket_unix.go
Labels: cherry-pick/1.0.x
