Repository containerd/containerd, pull requests merged in 2019-03, with the labels that each got.

#3064 Add content gc ref labels from containers, images, and snapshots
  metadata/gc.go
  metadata/gc_test.go
Labels: cherry-pick/1.2.x

#3079 [release1.2] Bump cgroups to dbea6f2bd41658b84b00417ceefa416b97
  vendor.conf
  vendor/github.com/containerd/cgroups/README.md
  vendor/github.com/containerd/cgroups/blkio.go
  vendor/github.com/containerd/cgroups/cgroup.go
  vendor/github.com/containerd/cgroups/control.go
  vendor/github.com/containerd/cgroups/cpuset.go
  vendor/github.com/containerd/cgroups/devices.go
  vendor/github.com/containerd/cgroups/net_prio.go
  vendor/github.com/containerd/cgroups/opts.go
  vendor/github.com/containerd/cgroups/paths.go
  vendor/github.com/containerd/cgroups/subsystem.go
  vendor/github.com/containerd/cgroups/systemd.go
  vendor/github.com/containerd/cgroups/utils.go
Labels: cherry-picked/1.2.x

#3137 Fix capability option race and panic.
  oci/spec_opts.go
  oci/spec_opts_test.go
Labels: cherry-pick/1.1.x, cherry-pick/1.2.x
