Repository containerd/containerd, pull requests merged in 2020-09, with the labels that each got.

#4519 shimv1: downgrade poroccess missing log to debug
  runtime/v1/shim/service.go
Labels: cherry-pick/1.4.x

#4532 Fix some signal forwarder issues
  cmd/ctr/commands/signals.go
  cmd/ctr/commands/signals_linux.go
  cmd/ctr/commands/signals_notlinux.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4546 Always consume shim logs
  runtime/v1/shim/client/client.go
Labels: cherry-pick/1.4.x

#4050 Update to golang 1.15.2
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .travis.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4566 vendor: github.com/willf/bitset v1.1.11
  vendor.conf
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/go.mod
Labels: cherry-pick/1.4.x

#4568 [release/1.4 backport] vendor: github.com/willf/bitset v1.1.11
  vendor.conf
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/go.mod
Labels: cherry-picked/1.4.x

#4573 Separate devmapper plugin
  cmd/containerd/builtins_devmapper_linux.go
  snapshots/devmapper/plugin/plugin.go
  snapshots/devmapper/snapshotter.go
Labels: needs-ok-to-test

#4533 feat(snapshot::aufs): config root_path
  cmd/containerd/builtins_aufs_linux.go
  vendor.conf
  vendor/github.com/containerd/aufs/README.md
  vendor/github.com/containerd/aufs/aufs.go
  vendor/github.com/containerd/aufs/go.mod
  vendor/github.com/containerd/aufs/plugin/plugin.go
Labels: impact/changelog

#4534 zfs: seperate implementation pkg from plugin pkg
  cmd/containerd/builtins_zfs_linux.go
  vendor.conf
  vendor/github.com/containerd/zfs/README.md
  vendor/github.com/containerd/zfs/go.mod
  vendor/github.com/containerd/zfs/plugin/plugin.go
  vendor/github.com/containerd/zfs/zfs.go
Labels: impact/changelog

#4579 Add support for NetBSD
  content/local/store_unix.go
  sys/stat_bsd.go
Labels: needs-ok-to-test
