Repository containerd/containerd, pull requests merged in 2020-12, with the labels that each got.

#4643 Optimize Windows and LCOW snapshotters to only create scratch layer on the final snapshot
  rootfs/apply.go
  snapshots/lcow/lcow.go
  snapshots/snapshotter.go
  snapshots/windows/windows.go
  unpacker.go
Labels: needs-ok-to-test

#4739 Handle an image ref with scheme
  reference/reference.go
  reference/reference_test.go
Labels: needs-ok-to-test

#4799 Add the Inclavare-Containers container runtime to the adopters list
  ADOPTERS.md
Labels: needs-ok-to-test

#4803 Allow configuration of different log formats: text, json
  cmd/containerd/command/main.go
  log/context.go
  services/server/config/config.go
Labels: needs-ok-to-test

#4772 [cri/config] : fix range iterator issue in ValidatePluginConfig
  pkg/cri/config/config.go
Labels: needs-ok-to-test

#4815 remove "apparmor" build tag
  BUILDING.md
  Makefile
  pkg/apparmor/apparmor.go
  pkg/apparmor/apparmor_unsupported.go
Labels: impact/changelog

#4850 Update RUNC.md
  RUNC.md
Labels: needs-ok-to-test

#4849 remove "selinux" build tag
  BUILDING.md
  Makefile
  docs/installation.md
  go.mod
  go.sum
  pkg/cri/server/helpers_selinux_linux_test.go
  test/build.sh
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
  vendor/modules.txt
Labels: impact/changelog

#4796 Mention built-in CRI support in README
  README.md
Labels: needs-ok-to-test

#4845 Add bounds on max oom_score_adj value for AdjustOOMScore
  container_linux_test.go
  runtime/v1/shim/client/client.go
  runtime/v2/shim/util_unix.go
  sys/oom_unix.go
  sys/oom_windows.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x, ok-to-test, priority/P1

#4863 [cri] ensure log dir is created
  pkg/cri/server/helpers_linux.go
Labels: cherry-pick/1.4.x

#4860 Return GRPC not found error instead of plain one
  container_linux_test.go
  runtime/v2/runc/v2/service.go
Labels: ok-to-test

#4874 [release/1.4] cherry-pick: Add bounds on max oom_score_adj value for AdjustOOMScore
  container_linux_test.go
  runtime/v1/shim/client/client.go
  runtime/v2/shim/util_unix.go
  sys/oom_unix.go
  sys/oom_windows.go
Labels: needs-ok-to-test

#4875 [release/1.3] cherry-pick: Add bounds on max oom_score_adj value for AdjustOOMScore
  container_linux_test.go
  runtime/v1/shim/client/client.go
  runtime/v2/shim/util_unix.go
  sys/oom_unix.go
  sys/oom_windows.go
Labels: needs-ok-to-test

#4841 Add two fuzzers to integrate containerd into OSS-fuzz
  fuzz/filters_fuzzers.go
  fuzz/platforms_fuzzers.go
Labels: needs-ok-to-test

#4872 [release/1.4 backport] Return GRPC not found error instead of plain one
  container_linux_test.go
  runtime/v2/runc/v2/service.go
Labels: needs-ok-to-test

#4866 Update BUILDING.md after moving to Go modules and various other small docs update
  BUILDING.md
  Makefile
  README.md
  container_linux_test.go
  docs/man/containerd-config.toml.5.md
  docs/remote-snapshotter.md
  images/image.go
  namespaces/ttrpc_test.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/server/bandwidth/fake_shaper.go
  pkg/cri/server/bandwidth/utils.go
  pkg/cri/server/container_stats_list_linux.go
  pkg/cri/server/helpers_test.go
  pkg/cri/server/restart.go
  pkg/cri/store/container/status.go
  pkg/netns/netns_linux.go
  pkg/netns/netns_other.go
  pkg/netns/netns_windows.go
  remotes/docker/auth/fetch.go
  remotes/docker/errcode.go
  reports/2017-04-28.md
  snapshots/devmapper/snapshotter.go
  test/push.sh
Labels: needs-ok-to-test

#4859 Update hcsshim and go-winio vendoring
  go.mod
  go.sum
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/vhd/vhd.go
  vendor/github.com/Microsoft/go-winio/vhd/zvhd.go
  vendor/github.com/Microsoft/hcsshim/.gitattributes
  vendor/github.com/Microsoft/hcsshim/CODEOWNERS
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/next.pb.txt
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.proto
  vendor/github.com/Microsoft/hcsshim/computestorage/attach.go
  vendor/github.com/Microsoft/hcsshim/computestorage/destroy.go
  vendor/github.com/Microsoft/hcsshim/computestorage/detach.go
  vendor/github.com/Microsoft/hcsshim/computestorage/export.go
  vendor/github.com/Microsoft/hcsshim/computestorage/format.go
  vendor/github.com/Microsoft/hcsshim/computestorage/helpers.go
  vendor/github.com/Microsoft/hcsshim/computestorage/import.go
  vendor/github.com/Microsoft/hcsshim/computestorage/initialize.go
  vendor/github.com/Microsoft/hcsshim/computestorage/mount.go
  vendor/github.com/Microsoft/hcsshim/computestorage/setup.go
  vendor/github.com/Microsoft/hcsshim/computestorage/storage.go
  vendor/github.com/Microsoft/hcsshim/computestorage/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/go.mod
  vendor/github.com/Microsoft/hcsshim/go.sum
  vendor/github.com/Microsoft/hcsshim/hcn/hcnglobals.go
  vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/syscall.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/utils.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/internal/hns/namespace.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group_affinity.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group_config.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group_configurations.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group_operations.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/cpu_group_property.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/create_group_operation.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/delete_group_operation.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/host_processor_modify_request.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/hv_socket_service_config.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/property_type.go
  vendor/github.com/Microsoft/hcsshim/internal/schema2/vm_processor_limits.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/filesystem.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/net.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
  vendor/modules.txt
Labels: needs-ok-to-test
