Repository containerd/containerd, pull requests merged in 2020-11, with the labels that each got.

#4688 bug fix:#4646
  container_restore_opts.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x, needs-ok-to-test

#4686 ci: run cri-integration target for all runtimes
  .github/workflows/ci.yml
  hack/test-utils.sh
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4687 ci: run critest target for all runtimes
  .github/workflows/ci.yml
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4692 Remove setuid gosu in favor of "sudo -E PATH=$PATH ..."
  .github/workflows/ci.yml
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4699 cri: selinux relabel /dev/shm
  pkg/cri/server/container_create_linux.go
Labels: ok-to-test

#4698 test: run tests with selinux enforcing
  .github/workflows/ci.yml
  Vagrantfile
Labels: ok-to-test

#4722 Move CRI plugin's docs from docs/ to docs/cri/
  docs/cri/architecture.md
  docs/cri/architecture.png
  docs/cri/config.md
  docs/cri/crictl.md
  docs/cri/decryption.md
  docs/cri/kube-up.md
  docs/cri/proposal.md
  docs/cri/registry.md
  docs/cri/release.md
  docs/cri/testing.md
Labels: needs-ok-to-test

#4724 docker: don’t hide pusher response error
  remotes/docker/pusher.go
Labels: needs-ok-to-test

#4723 ctr: fix the incorrect image unmount error hint
  cmd/ctr/commands/images/unmount.go
Labels: needs-ok-to-test

#4713 remove unused hack/* files
  hack/boilerplate/boilerplate
  hack/install/install-cni-config.sh
  hack/install/install-cni.sh
  hack/install/install-containerd.sh
  hack/install/install-critools.sh
  hack/install/install-deps.sh
  hack/install/install-runc.sh
  hack/install/utils.sh
  hack/install/windows/install-cni-config.sh
  hack/install/windows/install-cni.sh
  hack/install/windows/install-deps.sh
  hack/install/windows/install-hcsshim.sh
  hack/push.sh
  hack/release-windows.sh
  hack/release.sh
  hack/sort-vendor.sh
  hack/sync-vendor.sh
  hack/test-cri.sh
  hack/test-e2e-node.sh
  hack/update-proto.sh
  hack/verify-gofmt.sh
  hack/verify-vendor.sh
Labels: ok-to-test

#4725 docs: fix broken links
  docs/content-flow.md
  docs/getting-started.md
  docs/installation.md
Labels: needs-ok-to-test

#4735 Bump Golang 1.15.5
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-pick/1.4.x

#4653 Improve image pull performance from http 1.1 container registries
  content/helpers.go
Labels: ok-to-test

#4705 cri: selinuxrelabel=false for /dev/shm w/ host ipc
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: needs-ok-to-test

#4707 Do not hardcode "amd64" on LCOW and Windows-related files
  diff/lcow/lcow.go
  platforms/defaults_windows.go
  snapshots/lcow/lcow.go
Labels: needs-ok-to-test

#4647 Add annotations to task update request api
  api/next.pb.txt
  api/services/tasks/v1/tasks.pb.go
  api/services/tasks/v1/tasks.proto
  runtime/task.go
  runtime/v1/linux/task.go
  runtime/v2/shim.go
  runtime/v2/task/shim.pb.go
  runtime/v2/task/shim.proto
  services/tasks/local.go
  task.go
  task_opts.go
Labels: impact/changelog, kind/enhancement, ok-to-test

#4757 Update backports documentation
  RELEASES.md
Labels: needs-ok-to-test

#4751 [release/1.4] Improve image pull performance from http 1.1 container registries
  content/helpers.go
Labels: ok-to-test

#4761 Fix package name in cri runtimeoptions protobuf
  pkg/cri/runtimeoptions/v1/api.pb.go
  pkg/cri/runtimeoptions/v1/api.proto
Labels: ok-to-test

#4765 Fix Windows service panic file to not be read-only
  cmd/containerd/command/service_windows.go
Labels: cherry-pick/1.4.x, needs-ok-to-test

#4764 Remove duplicate systemd units file
  contrib/systemd-units/containerd.service
Labels: ok-to-test

#4781 Fix some typos and grammars
  README.md
Labels: needs-ok-to-test
