Repository containerd/containerd, pull requests merged in 2020-10, with the labels that each got.

#4597 Update BUILDING.md - add dependency libseccomp-dev
  BUILDING.md
Labels: needs-ok-to-test

#4599 Windows CNI install script using lowercase "destdir"
  script/setup/install-cni-windows
Labels: cherry-pick/1.4.x

#4600 Allow to use repository scope helper function from other packages
  remotes/docker/fetcher.go
  remotes/docker/pusher.go
  remotes/docker/resolver.go
  remotes/docker/scope.go
  remotes/docker/scope_test.go
Labels: ok-to-test

#4613 Update test build script to push containerd variant
  test/build.sh
  test/e2e_node/gci-init.sh
  test/e2e_node/init.yaml
Labels: ok-to-test

#4620 Fix typo in examples of registry config
  docs/registry.md
Labels: ok-to-test

#4621 fix no-pivot not working in io.containerd.runtime.v1.linux
  pkg/cri/server/sandbox_run_linux.go
Labels: needs-ok-to-test

#4625 Fix comment in RemovePodSandbox
  pkg/cri/server/sandbox_remove.go
Labels: needs-ok-to-test

#4628 Read trailing data from tar reader
  diff/lcow/lcow.go
Labels: ok-to-test

#4629 ensure we cancel child context when reading grpc
  content/proxy/content_reader.go
Labels: ok-to-test

#4633 Support AppArmor beta version format for Ubuntu 20.10
  contrib/apparmor/apparmor_test.go
  contrib/apparmor/template.go
Labels: ok-to-test

#4635 Filter snapshotter labels passed to wrapper of WithNewSnapshot
  pkg/cri/server/container_create.go
  pkg/cri/server/sandbox_run.go
Labels: ok-to-test

#4642 Add d2iq as an adopter
  ADOPTERS.md
Labels: needs-ok-to-test

#4645 Check if a process exists before returning it
  container_linux_test.go
  runtime/v2/shim.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x, ok-to-test

#4662 Revender latest containerd/fifo
  vendor.conf
  vendor/github.com/containerd/fifo/fifo.go
Labels: needs-ok-to-test

#4661 [release/1.4] cherry-pick: Read trailing data from tar reader
  diff/lcow/lcow.go
Labels: needs-ok-to-test

#4656 CRI: always set unknown to false when handling exit event
  pkg/cri/server/events.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x, ok-to-test

#4664 use proper buffer size for content get
  cmd/ctr/commands/content/content.go
Labels: needs-ok-to-test

#4610 Add manifest digest annotation for snapshotters
  pkg/cri/server/image_pull.go
Labels: ok-to-test
