Repository containerd/containerd, pull requests merged in 2020-08, with the labels that each got.

#4437 snapshots/devmapper: fix rollback
  snapshots/devmapper/metadata.go
  snapshots/devmapper/pool_device.go
  snapshots/devmapper/pool_device_test.go
Labels: cherry-pick/1.3.x

#4472 runtime: ignore ErrNotExist when remove rootfs
  runtime/v2/bundle.go
Labels: cherry-pick/1.4.x

#4486 tasks: Monitor v2 tasks in initFunc as well
  services/tasks/local.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4492 seccomp: sync some changes with Docker/Moby's profile
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.4.x

#4505 Add configurable overlayfs path
  snapshots/overlay/config.go
  snapshots/overlay/overlay.go
Labels: kind/enhancement

#4506 Separate overlay implementation from plugin
  cmd/containerd/builtins_linux.go
  snapshots/overlay/overlay.go
  snapshots/overlay/plugin/plugin.go
Labels: impact/changelog
