Repository containerd/containerd, pull requests merged in 2020-07, with the labels that each got.

#4356 Minor actions fixes/updates
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: cherry-pick/1.3.x

#4380 Don't clash with GH Actions runner's containerd
  .github/workflows/ci.yml
  script/setup/install-critools
Labels: cherry-picked/1.3.x

#4398 Bump Golang 1.13.14
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .travis.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-pick/1.2.x, cherry-pick/1.3.x

#4374 snapshots/devmapper: suspend a device to avoid data corruption
  snapshots/devmapper/pool_device.go
Labels: cherry-pick/1.3.x

#4384 Deprecate legacy shims
  RELEASES.md
  services/tasks/local.go
Labels: impact/changelog, impact/deprecation, kind/docs
