Repository containerd/containerd, pull requests merged in 2021-02, with the labels that each got.

#4906 bugfix: change the flag of open log fifo to avoid containerd hang on syscall open
  runtime/v2/binary.go
  runtime/v2/shim.go
  runtime/v2/shim_unix.go
Labels: cherry-pick/1.4.x

#4971 [release/1.4] bugfix change flag from RDONLY to RDWR and close the fifo correct
  runtime/v2/binary.go
  runtime/v2/shim.go
  runtime/v2/shim_unix.go
Labels: ok-to-test

#4988 runtime: fix shutdown runc v2 service
  runtime/v2/runc/v2/service.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x, needs-ok-to-test

#4992 [release/1.3] runtime: fix shutdown runc v2 service
  runtime/v2/runc/v2/service.go
Labels: needs-ok-to-test

#4993 [release/1.4] runtime: fix shutdown runc v2 service
  runtime/v2/runc/v2/service.go
Labels: needs-ok-to-test

#4987 Fix deprecated registry auth conversion.
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4717 further reduce uses of libcontainer and update runc v1.0.0-rc93
  go.mod
  go.sum
  pkg/cri/server/container_create_linux_test.go
  vendor/github.com/cilium/ebpf/.clang-format
  vendor/github.com/cilium/ebpf/.gitignore
  vendor/github.com/cilium/ebpf/abi.go
  vendor/github.com/cilium/ebpf/asm/instruction.go
  vendor/github.com/cilium/ebpf/asm/opcode.go
  vendor/github.com/cilium/ebpf/collection.go
  vendor/github.com/cilium/ebpf/doc.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/go.mod
  vendor/github.com/cilium/ebpf/go.sum
  vendor/github.com/cilium/ebpf/internal/btf/btf.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
  vendor/github.com/cilium/ebpf/internal/btf/ext_info.go
  vendor/github.com/cilium/ebpf/internal/btf/fuzz.go
  vendor/github.com/cilium/ebpf/internal/btf/types.go
  vendor/github.com/cilium/ebpf/internal/feature.go
  vendor/github.com/cilium/ebpf/internal/syscall.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/linker.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/readme.md
  vendor/github.com/cilium/ebpf/run-tests.sh
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/types_string.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/device_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/hugepage_limit.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/interface_priority_map.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/network.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/syndtr/gocapability/capability/enum.go
  vendor/github.com/syndtr/gocapability/capability/enum_gen.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: cherry-pick/1.4.x, impact/changelog

#5004 Update to go 1.15.8
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-picked/1.4.x

#5019 [release/1.4] Update continuity
  vendor.conf
  vendor/github.com/containerd/continuity/fs/du_unix.go
  vendor/github.com/containerd/continuity/go.mod
Labels: needs-ok-to-test

#4973 Allow moving netns directory into StateDir
  docs/cri/config.md
  pkg/cri/config/config.go
  pkg/cri/server/sandbox_run.go
  pkg/netns/netns_linux.go
  pkg/netns/netns_other.go
  pkg/netns/netns_windows.go
Labels: cri, kind/enhancement, needs-ok-to-test

#5025 Add references to Windows 20H2 test images.
  client_windows_test.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#4912 Scratch size customization and UVM scratch creation for WCOW snapshotter
  snapshots/windows/windows.go
Labels: needs-ok-to-test

#5033 Fix TestRuntimeHandler logging
  integration/runtime_handler_test.go
Labels: ok-to-test

#5044 Fix empty error warpping
  pkg/cri/server/container_create.go
Labels: needs-ok-to-test

#5045 FIx file is not closed
  mount/losetup_linux.go
Labels: needs-ok-to-test

#5024 cri: append envs from image config to empty slice to avoid env lost
  pkg/cri/server/container_create_linux.go
Labels: needs-ok-to-test

#5028 oci: fix the file mode of the device
  oci/spec_opts_linux.go
  oci/spec_opts_unix.go
Labels: needs-ok-to-test

#5021 Fix repeated sending signal
  pkg/cri/server/container_stop.go
  pkg/cri/store/container/container.go
Labels: needs-ok-to-test

#5078 CI: fix "ls: cannot access '/etc/cni/net.d': Permission denied"
  .github/workflows/ci.yml
Labels: cherry-pick/1.4.x

#5085 Fix broken docs links
  docs/PLUGINS.md
  docs/RUNC.md
  docs/cri/containerd.png
  docs/cri/installation.md
  docs/cri/performance.png
  docs/cri/testing.md
Labels: needs-ok-to-test

#5070 cri: set default masked/readonly paths to empty paths
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: needs-ok-to-test

#5086 Fixed wording in docs, and broken link
  docs/PLUGINS.md
  docs/ops.md
Labels: needs-ok-to-test

#5064 oci: fix superfluous slice operations
  oci/spec_opts.go
Labels: needs-ok-to-test

#5051 Fix missing close
  runtime/v2/runc/v1/service.go
Labels: needs-ok-to-test
