Repository containerd/containerd, pull requests merged in 2021-07, with the labels that each got.

#5571 Install specific golang version in Windows CI.
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test

#5676 Update for distribution spec 1.0
  README.md
  docs/hosts.md
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
Labels: status/merge-on-green

#5700 Dockerfile.test: add "cri-in-userns" (aka rootless) test stage
  .github/workflows/ci.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/Dockerfile.test.d/cri-in-userns/docker-entrypoint.sh
  contrib/Dockerfile.test.d/cri-in-userns/etc_containerd_config.toml
Labels: cri, kind/test

#5666 Add unit test for plugin
  plugin/plugin_test.go
Labels: ok-to-test

#5578 test integration: Adds a test that restarts a failed container
  integration/container_restart_test.go
Labels: ok-to-test

#5673 [Vendor] Update hcsshim to 0.8.18
  go.mod
  go.sum
  vendor/modules.txt
Labels: ok-to-test

#5712 Fix missing Body.Close() calls on push to docker remote
  remotes/docker/pusher.go
Labels: ok-to-test

#5722 Update Go to 1.16.6
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
  integration/client/go.mod
  integration/client/go.sum
  script/setup/prepare_env_windows.ps1
Labels: status/merge-on-green

#5751 update runc to v1.0.1
  go.mod
  go.sum
  integration/client/go.sum
  script/setup/runc-version
  vendor/github.com/cilium/ebpf/asm/func.go
  vendor/github.com/cilium/ebpf/asm/func_string.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/internal/btf/btf.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
  vendor/github.com/cilium/ebpf/internal/btf/btf_types_string.go
  vendor/github.com/cilium/ebpf/internal/btf/types.go
  vendor/github.com/cilium/ebpf/internal/syscall.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/link/iter.go
  vendor/github.com/cilium/ebpf/link/syscalls.go
  vendor/github.com/cilium/ebpf/link/uprobe.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/types_string.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5755 Use systemd cgroup driver for Kubernetes e2e tests with cgroupsv2
  contrib/gce/configure.sh
Labels: ok-to-test

#5769 remotes/docker/fetcher.go: Fix missing Close() on fetch from docker remote
  remotes/docker/fetcher.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x, needs-ok-to-test

#5770 remotes/docker/pusher.go: Fix missing Close() on push to docker remote
  remotes/docker/pusher.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x, needs-ok-to-test

#5687 Add docker.Fetch fuzzer
  contrib/fuzz/docker_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: ok-to-test

#5779 Fuzzing: Add archive fuzzer
  contrib/fuzz/archive_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
  go.mod
  go.sum
  vendor/github.com/AdaLogics/go-fuzz-headers/LICENSE
  vendor/github.com/AdaLogics/go-fuzz-headers/README.md
  vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
  vendor/github.com/AdaLogics/go-fuzz-headers/go.mod
  vendor/modules.txt
Labels: ok-to-test, status/merge-on-green

#5745 interface about shim build check
  runtime/v2/shim.go
Labels: ok-to-test, status/merge-on-green

#5744 Add runtime label to metrics
  metrics/cgroups/v1/cgroups.go
  metrics/cgroups/v1/metrics.go
  metrics/cgroups/v2/cgroups.go
  metrics/cgroups/v2/metrics.go
  runtime/monitor.go
  services/tasks/local.go
Labels: status/merge-on-green

#5590 Makefile: fix passing build tags
  Makefile
Labels: ok-to-test, status/merge-on-green

#5756 Discard blocks when removing a thin device
  snapshots/devmapper/README.md
  snapshots/devmapper/blkdiscard/blkdiscard.go
  snapshots/devmapper/config.go
  snapshots/devmapper/dmsetup/dmsetup.go
  snapshots/devmapper/dmsetup/dmsetup_test.go
  snapshots/devmapper/pool_device.go
  snapshots/devmapper/pool_device_test.go
Labels: ok-to-test, status/merge-on-green

#5162 integration: Windows volume-copy-up images
  integration/images/volume-copy-up/Dockerfile
  integration/images/volume-copy-up/Dockerfile_windows
  integration/images/volume-copy-up/Makefile
Labels: ok-to-test

#5606 grpc config add options tcp_client_ca_cert
  services/server/config/config.go
  services/server/server.go
Labels: kind/enhancement, ok-to-test

#5800 respect context timeout in shim binary call
  runtime/v2/shim/util.go
Labels: ok-to-test

#5043 Add a sharedNamespace label
  docs/ops.md
  labels/labels.go
  metadata/buckets.go
  metadata/buckets_test.go
  metadata/content.go
  metadata/images.go
Labels: impact/changelog, ok-to-test

#5725 Enable critest on Windows Periodic Jobs
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#5144 Update release workflow to upload binary without CNI
  .github/workflows/release.yml
Labels: ok-to-test

#5809 mergo: Upgrade to 0.3.12 to fix panic
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/merge.go
  vendor/modules.txt
Labels: cherry-pick/1.5.x, ok-to-test

#5746 runtime: fix the issue of create new socket with abstract address
  runtime/v2/shim/util_unix.go
Labels: ok-to-test

#5785 Fuzzing: Add container fuzzer
  contrib/fuzz/container_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: ok-to-test
