Repository containerd/containerd, pull requests merged in 2021-08, with the labels that each got.

#5823 Fuzzing: Remove panics of container_fuzzer
  contrib/fuzz/container_fuzzer.go
Labels: needs-ok-to-test

#5821 platforms: Format(): use path.Join() instead of joinNotEmpty()
  platforms/platforms.go
  platforms/platforms_test.go
Labels: status/merge-on-green

#5825 Fuzzing: Add two fuzzers
  contrib/fuzz/archive_fuzzer.go
  contrib/fuzz/content_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: needs-ok-to-test

#5829 Fuzzing: Fix for OSS-fuzz issue 36825
  contrib/fuzz/container_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: needs-ok-to-test

#5842 Update Go to 1.16.7
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/integration-test.yaml
  .zuul/playbooks/containerd-build/run.yaml
  .zuul/playbooks/containerd-build/unit-test.yaml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: cherry-picked/1.5.x

#5839 Fix Linux CI Linter using Go 1.15.14
  .github/workflows/ci.yml
Labels: needs-ok-to-test

#5852 [Scripts] Add trap to cri-integration test script
  script/test/cri-integration.sh
Labels: needs-ok-to-test

#5851 replace cri and point to new location
  contrib/ansible/README.md
  contrib/ansible/vars/vars.yaml
Labels: ok-to-test

#5840 Fuzzing: Add experimental version of container fuzzer
  contrib/fuzz/container_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: ok-to-test

#5863 Fuzzing: Add 4 fuzzers
  contrib/fuzz/cap_fuzzer.go
  contrib/fuzz/content_fuzzer.go
  contrib/fuzz/cri_fuzzer.go
  contrib/fuzz/docker_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: needs-ok-to-test

#5878 Allow expanded DNS configuration
  pkg/cri/server/helpers_linux.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: ok-to-test

#5884 Make Cgroup driver configurable in gce configure script
  contrib/gce/configure.sh
Labels: needs-ok-to-test

#5886 Fuzzing: Add fuzzer
  contrib/fuzz/containerd_import_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
Labels: needs-ok-to-test

#5896 integration: fix TestContainerPids
  integration/client/container_test.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5893 [release/1.5 backport] Allow expanded DNS configuration
  pkg/cri/server/helpers_linux.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: needs-ok-to-test

#5131 Add Windows HostProcess Support
  pkg/cri/annotations/annotations.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/restart.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/server/sandbox_run_windows_test.go
  pkg/cri/server/sandbox_status.go
Labels: kind/feature, windows, ok-to-test

#5902 cri: filter selinux xattr for image volumes
  pkg/cri/opts/container.go
Labels: ok-to-test, cherry-pick/1.5.x

#5905 go.mod: github.com/pelletier/go-toml v1.9.3
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/pelletier/go-toml/CONTRIBUTING.md
  vendor/github.com/pelletier/go-toml/LICENSE
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/azure-pipelines.yml
  vendor/github.com/pelletier/go-toml/fuzzit.sh
  vendor/github.com/pelletier/go-toml/go.mod
  vendor/github.com/pelletier/go-toml/go.sum
  vendor/github.com/pelletier/go-toml/lexer.go
  vendor/github.com/pelletier/go-toml/localtime.go
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/token.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/github.com/pelletier/go-toml/tomlpub.go
  vendor/github.com/pelletier/go-toml/tomltree_write.go
  vendor/github.com/pelletier/go-toml/tomltree_writepub.go
  vendor/modules.txt
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5899 bump up runc v1.0.2
  go.mod
  go.sum
  integration/client/go.sum
  script/setup/runc-version
  vendor/modules.txt
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5845 Fix dir support for devices
  oci/spec_opts_linux.go
  oci/spec_opts_linux_test.go
Labels: ok-to-test

#5122 cri: Devices ownership from SecurityContext
  oci/spec_opts_unix.go
  pkg/cri/config/config.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: ok-to-test, status/needs-discussion

#5927 Update Pause image in tests & config
  contrib/ansible/cri-containerd.yaml
  docs/PLUGINS.md
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/client_test.go
  integration/client/image_test.go
  integration/client/lease_test.go
  integration/common.go
  integration/image_list.sample.toml
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test
