Repository containerd/containerd, pull requests merged in 2021-06, with the labels that each got.

#5548 docs/cri: update links
  docs/cri/crictl.md
  docs/cri/decryption.md
Labels: needs-ok-to-test

#5553 integration: Cleanup containerd on test teardown
  script/test/utils.sh
Labels: needs-ok-to-test

#5536 scrub the stale TODO
  pkg/cri/constants/constants.go
Labels: needs-ok-to-test

#5558 Install apparmor parser for arm64 environment
  .zuul/playbooks/containerd-build/integration-test.yaml
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x, kind/test

#5560 Change Wrapf of non-error to an actual error
  content/local/store.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5535 Makefile: fix DESTDIR environment variable behaviour
  BUILDING.md
  Makefile
Labels: impact/changelog, ok-to-test

#5284 tests: Symlink volume tests
  integration/container_volume_test.go
  integration/main_test.go
Labels: ok-to-test

#5422 Use DeactivateLayer to unlock layers that we cannot rename
  snapshots/windows/windows.go
Labels: ok-to-test

#5559 Windows periodic job: Add creation timestamp to RG
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#5551 diff/walking: fix defer cleanup
  diff/walking/differ.go
Labels: ok-to-test

#5565 fix invalid validation error checking
  metadata/containers.go
  metadata/content.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5569 Fix cleanup context of teardownPodNetwork
  pkg/cri/server/sandbox_run.go
Labels: cherry-pick/1.5.x

#5594 Add proper Go version before project checks
  .github/workflows/ci.yml
Labels: cherry-pick/1.5.x

#5593 [release/1.5] cherry pick #5569 to release 1.5 - Fix cleanup context of teardownPodNetwork
  pkg/cri/server/sandbox_run.go
Labels: ok-to-test, status/merge-on-green

#5598 [release/1.5] cherry-pick #5533: Fix incorrect UA used for registry authentication
  remotes/docker/auth/fetch.go
Labels: ok-to-test

#5475 add cgroupv2 setup for cos with a flag
  test/e2e_node/gci-init.sh
Labels: ok-to-test

#5611 ctr flags of container rootfs propagation
  cmd/ctr/commands/commands_unix.go
  cmd/ctr/commands/run/run_unix.go
Labels: ok-to-test

#5617 runtime,v2: Enable debug when containerd is on debug+ log level
  runtime/v2/binary.go
Labels: needs-ok-to-test

#5545 docs: fix deprecation config for default runtime
  docs/cri/config.md
Labels: ok-to-test

#5640 sandbox: send pod UID to CNI plugins as K8S_POD_UID
  pkg/cri/server/sandbox_run.go
Labels: ok-to-test

#5643 [release/1.5] sandbox: send pod UID to CNI plugins as K8S_POD_UID
  pkg/cri/server/sandbox_run.go
Labels: needs-ok-to-test

#5287 Cri integration cleanup
  integration/addition_gids_test.go
  integration/container_log_test.go
  integration/container_restart_test.go
  integration/container_stats_test.go
  integration/container_stop_test.go
  integration/container_update_resources_test.go
  integration/container_volume_test.go
  integration/container_without_image_ref_test.go
  integration/containerd_image_test.go
  integration/duplicate_name_test.go
  integration/image_load_test.go
  integration/imagefs_info_test.go
  integration/main_test.go
  integration/no_metadata_test.go
  integration/pod_dualstack_test.go
  integration/runtime_handler_test.go
  integration/volume_copy_up_test.go
Labels: ok-to-test

#5655 snapshot/devmapper: log exported methods correctly
  snapshots/devmapper/snapshotter.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5660 Add ctr command label in NewContainerOpts
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/containers/containers.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
Labels: ok-to-test
