Repository containerd/containerd, pull requests merged in 2021-01, with the labels that each got.

#4899 docs: point cri release tarball to github release page
  README.md
  contrib/ansible/tasks/binaries.yaml
  docs/cri/cri.png
  docs/cri/installation.md
  docs/cri/kube-up.md
  docs/cri/release.md
Labels: needs-ok-to-test

#4909 Fix typo in comment
  images/mediatypes.go
Labels: needs-ok-to-test

#4923 runtime/v2: should use defer ctx to cleanup
  runtime/v2/manager.go
Labels: cherry-pick/1.3.x, cherry-pick/1.4.x

#4916 Allow passing environent variables to StreamProcessors
  diff/stream.go
  diff/stream_unix.go
  diff/stream_windows.go
  services/server/config/config.go
  services/server/server.go
Labels: status/merge-on-green

#4528 Add amd64->386 fallback
  platforms/compare.go
  platforms/compare_test.go
Labels: status/merge-on-green

#4933 Ensure request.header is never nil
  remotes/docker/resolver.go
Labels: needs-ok-to-test

#4918 signal: do not print message when dealing with SIG_PIPE
  cmd/containerd/command/main_unix.go
Labels: needs-ok-to-test

#4941 [release/v1.4] docker: avoid concurrent map access panic
  remotes/docker/resolver.go
Labels: needs-ok-to-test

#4942 [release/v1.4] pusher: add missing authentication support for requests
  remotes/docker/pusher.go
Labels: needs-ok-to-test

#4953 Derive cpuinfo as needed, instead of at init-time
  platforms/cpuinfo.go
  platforms/defaults.go
  platforms/defaults_test.go
  platforms/platforms.go
  platforms/platforms_test.go
Labels: ok-to-test

#4955 Clean Up Doc and fix some broken links
  README.md
  docs/cri/installation.md
  docs/cri/kube-up.md
  docs/cri/testing.md
Labels: needs-ok-to-test

#4824 Add scratch space re-use functionality to LCOW snapshotter
  snapshots/lcow/lcow.go
Labels: ok-to-test

#4759 Enhance logging driver to support windows
  cmd/ctr/commands/tasks/tasks_windows.go
  runtime/v2/logging/logging.go
  runtime/v2/logging/logging_unix.go
  runtime/v2/logging/logging_windows.go
Labels: needs-ok-to-test

#4959 Bump Golang 1.15.7
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-pick/1.4.x

#4964 Add cgo tag to btrfs plugin
  cmd/containerd/builtins_btrfs_linux.go
  snapshots/btrfs/btrfs.go
  snapshots/btrfs/btrfs_test.go
  snapshots/btrfs/plugin/plugin.go
Labels: needs-ok-to-test

#4963 Move runtimeoptions out of cri package
  cmd/ctr/commands/run/run_unix.go
  pkg/cri/server/helpers.go
  pkg/runtimeoptions/v1/api.pb.go
  pkg/runtimeoptions/v1/api.proto
Labels: needs-ok-to-test

#4682 cri: handle sandbox/container exit event in parallel
  pkg/cri/server/container_start.go
  pkg/cri/server/container_stop.go
  pkg/cri/server/events.go
  pkg/cri/server/restart.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_stop.go
Labels: cri, kind/performance

#4701 content: support filters on local.store#Walk()
  content/adaptor.go
  content/local/store.go
  metadata/adaptors.go
  metadata/content.go
Labels: needs-ok-to-test

#4922 cri: add annotations for pod name and namespace
  pkg/cri/annotations/annotations.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/server/sandbox_run_windows_test.go
Labels: needs-ok-to-test

#4972 remove exec sync debug contents from logs
  pkg/cri/server/instrumented_service.go
Labels: cherry-pick/1.4.x

#4974 Update gogo/protobuf to v1.3.2
  api/events/container.pb.go
  api/events/content.pb.go
  api/events/image.pb.go
  api/events/namespace.pb.go
  api/events/snapshot.pb.go
  api/events/task.pb.go
  api/services/containers/v1/containers.pb.go
  api/services/content/v1/content.pb.go
  api/services/diff/v1/diff.pb.go
  api/services/events/v1/events.pb.go
  api/services/images/v1/images.pb.go
  api/services/introspection/v1/introspection.pb.go
  api/services/leases/v1/leases.pb.go
  api/services/namespaces/v1/namespace.pb.go
  api/services/snapshots/v1/snapshots.pb.go
  api/services/tasks/v1/tasks.pb.go
  api/services/ttrpc/events/v1/events.pb.go
  api/services/version/v1/version.pb.go
  api/types/descriptor.pb.go
  api/types/metrics.pb.go
  api/types/mount.pb.go
  api/types/platform.pb.go
  api/types/task/task.pb.go
  go.mod
  go.sum
  pkg/runtimeoptions/v1/api.pb.go
  runtime/linux/runctypes/runc.pb.go
  runtime/v1/shim/v1/shim.pb.go
  runtime/v2/runc/options/oci.pb.go
  runtime/v2/task/shim.pb.go
  vendor/github.com/gogo/protobuf/plugin/unmarshal/unmarshal.go
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/github.com/gogo/protobuf/types/any.pb.go
  vendor/github.com/gogo/protobuf/types/api.pb.go
  vendor/github.com/gogo/protobuf/types/duration.pb.go
  vendor/github.com/gogo/protobuf/types/empty.pb.go
  vendor/github.com/gogo/protobuf/types/field_mask.pb.go
  vendor/github.com/gogo/protobuf/types/source_context.pb.go
  vendor/github.com/gogo/protobuf/types/struct.pb.go
  vendor/github.com/gogo/protobuf/types/timestamp.pb.go
  vendor/github.com/gogo/protobuf/types/type.pb.go
  vendor/github.com/gogo/protobuf/types/wrappers.pb.go
  vendor/modules.txt
Labels: ok-to-test
