Repository containerd/containerd, pull requests merged in 2021-03, with the labels that each got.

#5099 CI: cache ~/.vagrant.d/boxes
  .github/workflows/ci.yml
Labels: cherry-pick/1.4.x

#5088 update linuxkit readme
  contrib/linuxkit/README.md
Labels: ok-to-test

#5007 v2, util: Take the full binary path when starting the shimv2 process
  runtime/v2/shim/util.go
Labels: ok-to-test

#5107 [release/v1.4] vendor: update cri
  vendor.conf
  vendor/github.com/containerd/cri/README.md
  vendor/github.com/containerd/cri/pkg/api/runtimeoptions/v1/api.pb.go
  vendor/github.com/containerd/cri/pkg/config/config.go
  vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
  vendor/github.com/containerd/cri/pkg/server/container_create_windows.go
  vendor/github.com/containerd/cri/pkg/server/helpers_unix.go
  vendor/github.com/containerd/cri/vendor.conf
Labels: needs-ok-to-test

#5117 cri: fix container status
  pkg/cri/server/container_status.go
  pkg/cri/server/container_status_test.go
Labels: ok-to-test

#5106 update BUILDING.md
  BUILDING.md
Labels: needs-ok-to-test

#5134 apparmor: add DumpDefaultProfile
  contrib/apparmor/apparmor.go
  contrib/apparmor/apparmor_test.go
Labels: kind/enhancement

#5111 mark device faulty after parent fails to suspend
  snapshots/devmapper/pool_device.go
Labels: needs-ok-to-test

#5014 move to v3.4.1 for the pause image
  client_test.go
  contrib/ansible/cri-containerd.yaml
  docs/PLUGINS.md
  docs/cri/config.md
  docs/cri/crictl.md
  integration/main_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#4467 apparmor: handle signal mediation
  contrib/apparmor/template.go
  contrib/apparmor/template_test.go
Labels: cherry-pick/1.4.x

#5076 overlay: support "userxattr" option (kernel 5.11)
  snapshots/overlay/check.go
  snapshots/overlay/overlay.go
  snapshots/overlay/overlay_test.go
Labels: cherry-pick/1.4.x, impact/changelog

#5114 Print elapsed time for image unpack
  cmd/ctr/commands/images/pull.go
Labels: needs-ok-to-test

#5147 [release/1.4] overlay: support "userxattr" option (kernel 5.11)
  snapshots/overlay/check.go
  snapshots/overlay/overlay.go
  snapshots/overlay/overlay_test.go
Labels: impact/changelog

#5056 Update to Go 1.16.1
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
  go.mod
Labels: cherry-pick/1.4.x

#5178 Update to Go 1.16.2
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/run.yaml
  Vagrantfile
  contrib/Dockerfile.test
Labels: cherry-pick/1.4.x

#5189 Reduce load on ratelimited docker.io
  integration/client/client_test.go
  integration/client/go.mod
  integration/client/go.sum
  integration/client/image_test.go
  integration/client/lease_test.go
Labels: ok-to-test

#5164 Improve unexpected response error handling
  remotes/docker/pusher.go
  remotes/errors/errors.go
Labels: needs-ok-to-test

#5184 Prevent runc inheriting BUILDTAGS from containerd
  script/setup/install-runc
Labels: cherry-picked/1.4.x

#5198 cmd/ctr: use e.g. in the command usage
  cmd/ctr/commands/commands.go
Labels: needs-ok-to-test

#5197 cmd/ctr: fix export command
  cmd/ctr/commands/images/export.go
Labels: cherry-pick/1.4.x, needs-ok-to-test

#5201 [release/1.4] cmd/ctr: fix export command
  cmd/ctr/commands/images/export.go
Labels: needs-ok-to-test

#5196 rootfs: fix the error handling of the snapshotter.Commit
  rootfs/init.go
Labels: cherry-pick/1.4.x, ok-to-test

#5186 Fix docker style cert loading.
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
Labels: cherry-pick/1.4.x

#5174 runtime: ignore file-already-closed error if dead shim
  runtime/v2/shim.go
  runtime/v2/shim_unix.go
  runtime/v2/shim_unix_test.go
Labels: cherry-pick/1.4.x, ok-to-test

#5200 ctr plugin ls: plugin status should be skip, not error
  cmd/ctr/commands/plugins/plugins.go
Labels: needs-ok-to-test

#5206 runtime/v2/runc: fix the defer cleanup of the NewContainer
  runtime/v2/runc/container.go
Labels: needs-ok-to-test

#5195 runtime/v2/runc: fix leaking socket path
  runtime/v2/runc/v1/service.go
  runtime/v2/runc/v2/service.go
  runtime/v2/shim/shim.go
Labels: cherry-pick/1.4.x, ok-to-test

#5160 Use net.IP.IsLoopback() to match loopback addresses
  remotes/docker/registry.go
  remotes/docker/registry_test.go
Labels: needs-ok-to-test

#5222 runtime/v2: add comment for checkCopyShimLogError
  runtime/v2/binary.go
  runtime/v2/shim.go
Labels: ok-to-test

#5218 change default runtime for containerd-stress app
  cmd/containerd-stress/main.go
Labels: ok-to-test

#5211 upgrade pause image to 3.5 for non-root
  contrib/ansible/cri-containerd.yaml
  docs/PLUGINS.md
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/client_test.go
  integration/client/image_test.go
  integration/client/lease_test.go
  integration/main_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#5202 Change dgst to digest in debug
  cmd/ctr/commands/content/prune.go
  diff/apply/apply.go
  diff/lcow/lcow.go
  diff/windows/windows.go
Labels: ok-to-test

#5230 Fix error log when kill shim
  runtime/v1/linux/runtime.go
Labels: needs-ok-to-test

#4949 Add unit test for func in remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: ok-to-test

#5229 Fix error log when copy file
  pkg/process/init.go
Labels: cherry-pick/1.4.x, kind/bug, ok-to-test

#4708 Re-enable CRIU tests by not using overlayfs snapshotter
  .github/workflows/ci.yml
  integration/client/client_test.go
  integration/client/container_checkpoint_test.go
  pkg/process/init.go
  runtime/v2/runc/container.go
Labels: ok-to-test

#4898 standard makefile,fix not work no macos
  Makefile
Labels: needs-ok-to-test

#5148 runtime/v2: Fix defer cleanup for TaskManager.Create
  runtime/v2/manager.go
Labels: needs-ok-to-test

#5244 night ci: add packages for ubuntu 20.04
  .github/workflows/nightly.yml
Labels: needs-ok-to-test

#5243 go.mod: github.com/containerd/zfs v0.0.0-20210322090317-0e92c2247fb7 (for snapshot usage)
  go.mod
  go.sum
  vendor/github.com/containerd/zfs/plugin/plugin.go
  vendor/github.com/containerd/zfs/zfs.go
  vendor/modules.txt
Labels: impact/changelog

#5125 add caller info to the testHook
  log/logtest/context.go
Labels: ok-to-test

#5254 Make CRI registry docs more clear
  docs/cri/registry.md
Labels: needs-ok-to-test

#5234 Support HTTP debug in ctr
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/content/fetch.go
  cmd/ctr/commands/images/images.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/resolver.go
  remotes/docker/config/hosts.go
Labels: ok-to-test

#5133 Correct clean-up of Windows Layers in testsuite
  integration/client/go.mod
  integration/client/go.sum
  sys/filesys_windows.go
Labels: needs-ok-to-test

#5135 add imgcrypt stream processors to the default config
  cmd/containerd/command/config.go
  cmd/containerd/command/config_linux.go
  cmd/containerd/command/config_unsupported.go
  cmd/containerd/command/config_windows.go
  cmd/containerd/command/main.go
  cmd/containerd/command/main_unix.go
  cmd/containerd/command/main_windows.go
  defaults/defaults_unix.go
  defaults/defaults_windows.go
  docs/cri/decryption.md
  images/mediatypes.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: impact/changelog, kind/enhancement

#5267 Extend default timeout for nested VM integration run
  Vagrantfile
Labels: cherry-pick/1.4.x

#5145 use (sort of) happy-eyeballs for port-forwarding
  pkg/cri/server/sandbox_portforward_linux.go
Labels: ok-to-test

#5231 [release/1.4] Cherry pick of #5229: Fix error log when copy file
  pkg/process/init.go
Labels: ok-to-test
