Repository containerd/containerd, pull requests merged in 2021-09, with the labels that each got.

#5932 Fix cwd flag for `ctr tasks exec`
  cmd/ctr/commands/tasks/exec.go
Labels: needs-ok-to-test

#5937 Makefile.linux: build on RISC-V with PIE
  Makefile.linux
Labels: needs-ok-to-test

#5929 go.mod: Update hcsshim to v0.8.21
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/errors.go
  vendor/github.com/Microsoft/hcsshim/hcn/hcn.go
  vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go
  vendor/github.com/Microsoft/hcsshim/hnsendpoint.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go
  vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go
  vendor/modules.txt
Labels: needs-ok-to-test

#5947 fix document non-synchronous
  docs/cri/crictl.md
Labels: needs-ok-to-test

#5944 using Hosts replace deprecated field
  client.go
Labels: needs-ok-to-test

#5943 Content fuzzer: Clean up temp store dir
  contrib/fuzz/content_fuzzer.go
Labels: needs-ok-to-test

#5951 Add WS2022 support in Windows Periodic tests
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#5958 replace deprecated Dialer with ContextDialer
  runtime/v2/shim/util_unix.go
Labels: needs-ok-to-test, easy-to-review

#5949 archive: Add WriteDiff error logs
  archive/tar.go
Labels: needs-ok-to-test, easy-to-review

#5858 Update RELEASES.md
  RELEASES.md
Labels: easy-to-review

#5941 [release/1.5] Fix dir support for devices
  oci/spec_opts_linux.go
  oci/spec_opts_linux_test.go
Labels: needs-ok-to-test

#5917 Use issue forms for bug reporting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: easy-to-review

#5627 Feature: containerd-cri support LinuxContainerResources.Unified
  pkg/cri/opts/spec_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_update_resources_linux_test.go
Labels: needs-ok-to-test

#5954 sandbox: Allows the sandbox to be deleted in NotReady state
  pkg/cri/server/sandbox_remove.go
Labels: ok-to-test

#5939 cri: add devices for privileged container
  pkg/cri/server/container_create_linux.go
Labels: ok-to-test

#5966 Fix content copy to not ignore unexpected EOF
  content/helpers.go
  content/helpers_test.go
Labels: cherry-pick/1.5.x

#5972 complete integration test for pulling image with labels
  integration/containerd_image_test.go
Labels: needs-ok-to-test

#5610 add xfs support to devicemapper snapshotter
  snapshots/devmapper/config.go
  snapshots/devmapper/config_test.go
  snapshots/devmapper/snapshotter.go
  snapshots/devmapper/snapshotter_test.go
Labels: ok-to-test

#5982 seccomp: support "clone3" (return ENOSYS unless SYS_ADMIN is granted)
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#5974 task delete: Closes task IO before waiting
  pkg/cri/io/helpers_windows.go
  task.go
Labels: needs-ok-to-test

#5981 [release/1.5] cherry-pick: cri: add devices for privileged container
  pkg/cri/server/container_create_linux.go
Labels: needs-ok-to-test

#6028 bump console version to v1.0.3 that remove pkg/errors
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/console/console_windows.go
  vendor/github.com/containerd/console/console_zos.go
  vendor/github.com/containerd/console/go.mod
  vendor/github.com/containerd/console/go.sum
  vendor/github.com/containerd/console/tc_unix.go
  vendor/github.com/containerd/console/tc_zos.go
  vendor/modules.txt
Labels: needs-ok-to-test

#5998 ctr namespaces: improve usage string
  cmd/ctr/commands/namespaces/namespaces.go
Labels: needs-ok-to-test

#5991 FreeBSD: fix tar headers & the nil check on getxattr
  archive/tar.go
  archive/tar_unix.go
Labels: ok-to-test, platform/freebsd

#6027 add current process state to the error message
  process.go
Labels: status/merge-on-green, ok-to-test

#5979 fix error string format
  integration/common.go
Labels: ok-to-test

#5916 ctr: Fixes Windows image import
  images/archive/importer.go
Labels: ok-to-test

#5926 import: Raise error if the imported image is filtered out
  images/handlers.go
  import.go
  integration/client/import_test.go
Labels: ok-to-test

#5946 switch usage directly to errdefs.(ErrAlreadyExists and ErrNotFound)
  .empty-mod/go.mod
  pkg/cri/server/container_remove.go
  pkg/cri/server/container_status.go
  pkg/cri/server/container_stop.go
  pkg/cri/server/events.go
  pkg/cri/server/helpers.go
  pkg/cri/server/helpers_test.go
  pkg/cri/server/image_remove.go
  pkg/cri/server/image_status.go
  pkg/cri/server/sandbox_remove.go
  pkg/cri/store/container/container.go
  pkg/cri/store/container/container_test.go
  pkg/cri/store/errors_test.go
  pkg/cri/store/image/image.go
  pkg/cri/store/image/image_test.go
  pkg/cri/store/sandbox/sandbox.go
  pkg/cri/store/sandbox/sandbox_test.go
  pkg/cri/store/snapshot/snapshot.go
  pkg/cri/store/snapshot/snapshot_test.go
Labels: ok-to-test

#6023 Change `oci.WithUser` behavior for LCOW
  oci/spec_opts.go
Labels: ok-to-test

#5853 integration: Adds Windows HostProcess tests
  integration/main_test.go
  integration/windows_hostprocess_test.go
  script/test/cri-integration.sh
  script/test/utils.sh
Labels: windows, ok-to-test

#5922 replace deprecated function with Domain and Path
  reference/docker/reference.go
Labels: ok-to-test

#6059 fix: make exec-id flag required in exec command
  cmd/ctr/commands/tasks/exec.go
Labels: needs-ok-to-test, ok-to-test

#6070 feat: support import image for specific platform
  cmd/ctr/commands/images/import.go
  import.go
Labels: needs-ok-to-test

#6069 feat: enable integration cri remote client to call with grpc calloptions
  integration/cri-api/pkg/apis/services.go
  integration/main_test.go
  integration/remote/remote_image.go
  integration/remote/remote_runtime.go
Labels: ok-to-test
