Repository containerd/containerd, pull requests merged in 2021-11, with the labels that each got.

#6182 integration: Enables TestVolumeCopyUp for Windows
  integration/volume_copy_up_test.go
Labels: ok-to-test

#6177 compression: support zstd with skippable frame
  archive/compression/compression.go
  archive/compression/compression_test.go
Labels: needs-ok-to-test

#6171 Add mkdir on Dockerfile
  contrib/Dockerfile.test
Labels: ok-to-test

#6179 integration: Enables TestRuntimeHandler for Windows
  integration/runtime_handler_test.go
Labels: needs-ok-to-test

#6200 test: Add grace period for restart monitor test
  integration/client/restart_monitor_test.go
Labels: ok-to-test

#5918 Decouple task manager
  integration/client/container_linux_test.go
  plugin/plugin.go
  runtime/runtime.go
  runtime/task_list.go
  runtime/v2/binary.go
  runtime/v2/manager.go
  runtime/v2/process.go
  runtime/v2/shim.go
  runtime/v2/shim_load.go
  services/tasks/local.go
  services/tasks/local_freebsd.go
  services/tasks/local_unix.go
  services/tasks/local_windows.go
Labels: impact/changelog

#6205 Pin az CLI version in windows-periodic workflow
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6222 cleanup: add more description on comment
  pkg/cri/server/helpers.go
Labels: needs-ok-to-test

#6228 go.mod: Bump ttrpc to 1.1.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/ttrpc/.gitignore
  vendor/github.com/containerd/ttrpc/.travis.yml
  vendor/github.com/containerd/ttrpc/README.md
  vendor/github.com/containerd/ttrpc/channel.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/codec.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/go.mod
  vendor/github.com/containerd/ttrpc/go.sum
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  vendor/modules.txt
Labels: needs-ok-to-test

#6230 go.mod: Bump hcsshim to v0.9.1
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.proto
  vendor/github.com/Microsoft/hcsshim/go.mod
  vendor/github.com/Microsoft/hcsshim/go.sum
  vendor/modules.txt
Labels: needs-ok-to-test

#6229 [release/1.5] go.mod: Bump ttrpc to 1.1.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/ttrpc/.gitignore
  vendor/github.com/containerd/ttrpc/.travis.yml
  vendor/github.com/containerd/ttrpc/README.md
  vendor/github.com/containerd/ttrpc/channel.go
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/codec.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/go.mod
  vendor/github.com/containerd/ttrpc/go.sum
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/github.com/containerd/ttrpc/unixcreds_linux.go
  vendor/modules.txt
Labels: needs-ok-to-test

#6221 Fix containerd fails to pull OCI image with non-`http(s)://` urls
  remotes/docker/fetcher.go
Labels: cherry-pick/1.4.x, cherry-pick/1.5.x

#6231 [release/1.5] go.mod: Bump hcsshim to v0.8.23
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.proto
  vendor/github.com/Microsoft/hcsshim/go.mod
  vendor/github.com/Microsoft/hcsshim/go.sum
  vendor/modules.txt
Labels: needs-ok-to-test

#6246 Close file if permission modification fails
  archive/tar_unix.go
Labels: cherry-pick/1.4.x, needs-ok-to-test, cherry-pick/1.5.x

#6206 Allow absolute path to shim binaries
  api/next.pb.txt
  api/services/tasks/v1/tasks.pb.go
  api/services/tasks/v1/tasks.proto
  pkg/cri/config/config.go
  pkg/cri/server/container_start.go
  pkg/cri/server/sandbox_run.go
  runtime/runtime.go
  runtime/v2/binary.go
  runtime/v2/manager.go
  runtime/v2/shim/util.go
  runtime/v2/shim_load.go
  services/tasks/local.go
  task_opts.go
  vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.pb.go
  vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.proto
Labels: impact/changelog

#6253 feat: use rwmutex instead
  pkg/timeout/timeout.go
Labels: needs-ok-to-test, kind/refactor

#6255 Integration: Generalize Windows CI setup scripts for any username.
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test

#6111 [cri] add sandbox and container latency metrics
  pkg/cri/server/container_create.go
  pkg/cri/server/container_list.go
  pkg/cri/server/container_remove.go
  pkg/cri/server/container_start.go
  pkg/cri/server/container_stop.go
  pkg/cri/server/metrics.go
  pkg/cri/server/sandbox_list.go
  pkg/cri/server/sandbox_remove.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_stop.go
Labels: impact/changelog

#6170 CRI: Support enable_unprivileged_icmp and enable_unprivileged_ports options
  docs/cri/config.md
  pkg/cri/config/config.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: impact/changelog, ok-to-test

#6241 Add support for TMP override on toml
  services/server/config/config.go
  services/server/server.go
Labels: ok-to-test

#6258 [CRI] Fix panic when registry.mirrors use localhost
  pkg/cri/server/image_pull.go
Labels: needs-ok-to-test

#6254 feat:support custom callopts on client side
  client.go
  client_opts.go
Labels: ok-to-test

#6272 fix: server error return
  cmd/containerd/command/main.go
Labels: needs-ok-to-test

#6276 Fix wrong make target on documentation
  docs/cri/crictl.md
  integration/image_load_test.go
Labels: needs-ok-to-test

#6268 Integration: Remove explicit version passing to `azure/CLI`.
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6280 content/local: Close the file if Seek fails
  content/local/store.go
Labels: needs-ok-to-test

#6284 feat: skip ci for fork
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6289 ctr: Add Linux Capabilities control flags
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test

#6297 Add VMware TKG & TCE to Containerd adopters
  ADOPTERS.md
Labels: needs-ok-to-test

#6286 Integration: Separate Windows Periodic Tests workflow trigger.
  .github/workflows/windows-periodic-trigger.yml
  .github/workflows/windows-periodic.yml
Labels: ok-to-test
