Repository containerd/containerd, pull requests merged in 2022-06, with the labels that each got.

#7003 promote pause image to 3.7 (sync with kube v1.24)
  contrib/ansible/cri-containerd.yaml
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/client_test.go
  integration/client/image_test.go
  integration/client/lease_test.go
  integration/common.go
  integration/image_list.sample.toml
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#7009 update go-cni/for cni update fixing plugins that don't respond with version
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/server/testing/fake_cni_plugin.go
  vendor/github.com/containerd/go-cni/Makefile
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x

#7004 Fix containerd-stress duration flag
  BUILDING.md
Labels: needs-ok-to-test

#6899 Support runtime level snapshotter for issue 6657
  docs/cri/config.md
  pkg/cri/annotations/annotations.go
  pkg/cri/config/config.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_create_test.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_pull_test.go
  pkg/cri/server/sandbox_run.go
Labels: kind/enhancement, cri, ok-to-test

#7017 Bump k8s.io deps to v0.24.1
  go.mod
  go.sum
  integration/client/go.sum
  vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  vendor/modules.txt
Labels: ok-to-test

#7018 Bump grpc to v1.47.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: ok-to-test

#7028 go.mod: github.com/containerd/continuity v0.3.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/go-winio/backuptar/tar.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  vendor/github.com/Microsoft/go-winio/pkg/security/grantvmgroupaccess.go
  vendor/github.com/Microsoft/go-winio/vhd/vhd.go
  vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go
  vendor/github.com/containerd/continuity/.golangci.yml
  vendor/github.com/containerd/continuity/.mailmap
  vendor/github.com/containerd/continuity/AUTHORS
  vendor/github.com/containerd/continuity/Makefile
  vendor/github.com/containerd/continuity/README.md
  vendor/github.com/containerd/continuity/context.go
  vendor/github.com/containerd/continuity/driver/driver_unix.go
  vendor/github.com/containerd/continuity/driver/utils.go
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_device_unix.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_freebsd.go
  vendor/github.com/containerd/continuity/fs/copy_irregular_unix.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/diff.go
  vendor/github.com/containerd/continuity/fs/dtype_linux.go
  vendor/github.com/containerd/continuity/fs/fstest/compare.go
  vendor/github.com/containerd/continuity/fs/fstest/testsuite.go
  vendor/github.com/containerd/continuity/hardlinks.go
  vendor/github.com/containerd/continuity/ioutils.go
  vendor/github.com/containerd/continuity/manifest.go
  vendor/github.com/containerd/continuity/proto/gen.go
  vendor/github.com/containerd/continuity/proto/manifest.pb.go
  vendor/github.com/containerd/continuity/proto/manifest.proto
  vendor/github.com/containerd/continuity/sysx/generate.sh
  vendor/github.com/containerd/continuity/testutil/loopback/loopback_linux.go
  vendor/modules.txt
Labels: easy-to-review

#7027 go.mod: github.com/containerd/cgroups v1.0.4
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/cgroups/README.md
  vendor/github.com/containerd/cgroups/Vagrantfile
  vendor/github.com/containerd/cgroups/utils.go
  vendor/github.com/containerd/cgroups/v2/manager.go
  vendor/github.com/containerd/cgroups/v2/memory.go
  vendor/github.com/containerd/cgroups/v2/utils.go
  vendor/modules.txt
Labels: easy-to-review

#7031 fix minor spelling mistake: lablel -> label
  snapshots/overlay/overlay.go
Labels: needs-ok-to-test

#7033 Allow CRI on Darwin
  cmd/containerd/builtins_cri.go
Labels: easy-to-review

#7022 Make building static binaries simpler
  BUILDING.md
  Makefile
  Makefile.linux
Labels: cherry-pick/1.6.x

#7008 fix:userattr-unmount unexpected timeout
  snapshots/overlay/overlayutils/check.go
Labels: needs-ok-to-test

#7051 [release/1.6] ctr: fix label args used in NewContainer
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test

#6913 CRI: Improve the /dev/shm mount options in Sandbox.
  pkg/cri/server/sandbox_run_linux.go
Labels: ok-to-test

#7052 Run fuzzers in CI
  .github/workflows/cifuzz.yml
Labels: ok-to-test

#7057 Make test path a constant
  services/server/server_test.go
Labels: needs-ok-to-test

#7062 Downgrade MinGW in Windows setup scripts.
  script/setup/prepare_env_windows.ps1
Labels: needs-ok-to-test

#7071 [release/1.5] ctr: fix label args used in NewContainer
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test

#7077 improve content-flow
  docs/content-flow.md
Labels: needs-ok-to-test

#7086 Forward ctr snapshotter flags on Windows
  cmd/ctr/commands/run/run_windows.go
Labels: needs-ok-to-test

#7105 Cleanup metadata tests
  metadata/containers_test.go
  metadata/content_test.go
  metadata/db_test.go
  metadata/gc_test.go
  metadata/images_test.go
  metadata/leases_test.go
  metadata/namespaces_test.go
  metadata/sandbox_test.go
  metadata/snapshot_test.go
Labels: kind/test, easy-to-review

#7107 Fix missing closed HTTP Body
  cmd/ctr/commands/pprof/pprof.go
Labels: easy-to-review

#7108 pkg/cri: use marshal wrapper for version convertor
  pkg/cri/server/instrumented_service.go
Labels: cri, kind/refactor
