Repository containerd/containerd, pull requests merged in 2022-09, with the labels that each got.

#7359 feature: upgrade registry.k8s.io/pause version
  integration/images/image_list.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#7291 feature: use client default namespace
  client.go
  container_opts.go
Labels: ok-to-test

#7372 Update to go 1.19.1, 1.18.6 to address CVE-2022-27664, CVE-2022-32190
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7374 CRI: update cdi version to v0.5.1
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/registry.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec-dirs.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_linux.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_other.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/schema/Makefile
  vendor/github.com/container-orchestrated-devices/container-device-interface/schema/defs.json
  vendor/github.com/container-orchestrated-devices/container-device-interface/schema/schema.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/schema/schema.json
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/config.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/oci.go
  vendor/modules.txt
Labels: ok-to-test

#7370 Fix missing close
  images/converter/default.go
Labels: needs-ok-to-test

#7341 chore: matching the casing of other flags for ctr's pull command
  cmd/ctr/commands/images/pull.go
Labels: needs-ok-to-test

#7328 ctr: add privileged-without-host-devices for run command
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test

#7395 Replace github.com/emicklei/go-restful package, versions <2.16.0
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: ok-to-test

#7393 remotes/docker/config: Skipping TLS verification for localhost
  pkg/cri/server/image_pull.go
  remotes/docker/config/hosts.go
  remotes/docker/resolver.go
Labels: ok-to-test

#7396 Fuzzing: Instrument with new sanitizers
  contrib/fuzz/archive_fuzzer.go
  contrib/fuzz/fuzz_FuzzImportIndex.dict
  contrib/fuzz/fuzz_FuzzImportIndex.options
  contrib/fuzz/oss_fuzz_build.sh
Labels: ok-to-test

#7404 Enable OpenSSF Scorecard Github Action
  .github/workflows/scorecards.yml
Labels: needs-ok-to-test

#7413 cri-integration: propagate ENABLE_CRI_SANDBOXES
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_status.go
  pkg/cri/sbserver/container_update_resources.go
  pkg/cri/sbserver/helpers.go
  script/test/utils.sh
Labels: kind/test

#7408 reference CDI configuration details
  docs/cri/config.md
  pkg/cri/config/config.go
Labels: cri, needs-ok-to-test

#7416 remove stray .zuul.yaml
  .zuul.yaml
Labels: needs-ok-to-test

#7417 Set grpc code for unimplemented cri-api methods
  pkg/cri/sbserver/container_checkpoint.go
  pkg/cri/sbserver/container_events.go
  pkg/cri/server/container_checkpoint.go
  pkg/cri/server/container_events.go
Labels: status/merge-on-green, ok-to-test

#7421 [release/1.6] cherry-pick: Set grpc code for unimplemented cri-api methods
  pkg/cri/server/container_checkpoint.go
  pkg/cri/server/container_events.go
Labels: ok-to-test

#7405 Refactor CRI fuzzers
  contrib/fuzz/cri_fuzzer.go
  contrib/fuzz/cri_sbserver_fuzzer.go
  contrib/fuzz/cri_server_fuzzer.go
  pkg/cri/sbserver/cri_fuzzer.go
  pkg/cri/sbserver/fuzz.go
  pkg/cri/server/cri_fuzzer.go
  pkg/cri/server/fuzz.go
Labels: cri

#7430 Fix missing close
  snapshots/benchsuite/benchmark_test.go
Labels: needs-ok-to-test

#7438 [release/1.6] remotes/docker/config: Skipping TLS verification for localhost
  pkg/cri/server/image_pull.go
  remotes/docker/config/hosts.go
  remotes/docker/resolver.go
Labels: needs-ok-to-test
