Repository containerd/containerd, pull requests merged in 2022-10, with the labels that each got.

#7456 [release/1.6] Setup pod network after creating the sandbox container
  integration/main_test.go
  integration/sandbox_run_rollback_test.go
  pkg/cri/server/container_update_resources_other.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_other.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/store/sandbox/status.go
Labels: impact/changelog, cri, ok-to-test

#7466 cri doc: Update kata containers reference
  docs/cri/config.md
Labels: needs-ok-to-test

#7463 use raw link to containerd.service config
  docs/getting-started.md
Labels: kind/docs, needs-ok-to-test

#7474 Update to go 1.19.2 to address CVE-2022-2879, CVE-2022-2880, CVE-2022-41715
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7461 [release/1.6] retry request on writer reset
  content/helpers.go
  content/helpers_test.go
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: ok-to-test

#7477 fuzzing: create structured tar bytes in archive fuzzer
  contrib/fuzz/archive_fuzzer.go
Labels: needs-ok-to-test, kind/test

#7488 archive: validate digests before use
  images/archive/exporter.go
  images/archive/importer.go
Labels: cherry-pick/1.6.x

#7425 Add new ctr option for discarding unpacked layers
  cmd/ctr/commands/images/import.go
  import.go
Labels: needs-ok-to-test

#7478 archive: add WithSourceDateEpoch() for whiteouts
  api/next.pb.txt
  api/services/diff/v1/diff.pb.go
  api/services/diff/v1/diff.proto
  archive/tar.go
  archive/tar_opts.go
  archive/tar_test.go
  cmd/ctr/commands/snapshots/snapshots.go
  diff.go
  diff/diff.go
  diff/walking/differ.go
  pkg/epoch/epoch.go
  pkg/epoch/epoch_test.go
  services/diff/local.go
Labels: kind/enhancement

#7481 Update container with sandbox metadata after NetNS is created
  integration/main_test.go
  integration/restart_test.go
  integration/sandbox_run_rollback_test.go
  pkg/cri/server/container_update_resources_other.go
  pkg/cri/server/sandbox_run.go
  script/test/utils.sh
Labels: kind/bug, cri, ok-to-test, cherry-pick/1.5.x, cherry-pick/1.6.x

#7505 [release/1.6] Update container with sandbox metadata after NetNS is created
  integration/main_test.go
  integration/restart_test.go
  integration/sandbox_run_rollback_test.go
  pkg/cri/server/container_update_resources_other.go
  pkg/cri/server/sandbox_run.go
  script/test/utils.sh
Labels: kind/bug, cri, ok-to-test

#7497 cmd/containerd: replace deprecated windows.IsAnInteractiveSession()
  cmd/containerd/command/service_windows.go
Labels: windows

#7483 Updates oci image config to support upstream ArgsEscaped
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts.go
  oci/spec_opts_windows_test.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: ok-to-test

#7510 Update the default seccomp to block socket calls to AF_VSOCK
  contrib/seccomp/seccomp_default.go
Labels: impact/changelog, ok-to-test, impact/breaking

#7519 fix the --no-pivot flag being ignored by `ctr tasks start`
  cmd/ctr/commands/tasks/start.go
  cmd/ctr/commands/tasks/tasks_unix.go
  cmd/ctr/commands/tasks/tasks_windows.go
Labels: needs-ok-to-test

#7489 CI: update GHA instances from Ubuntu 18.04 to 20.04
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: cherry-pick/1.6.x

#7535 cri: PodSandboxStatus should tolerate missing task
  pkg/cri/sbserver/sandbox_status.go
  pkg/cri/server/sandbox_status.go
Labels: cri, cherry-pick/1.5.x, cherry-pick/1.6.x

#7539 Vagrantfile: explicitly specify rsync as the shared folder driver
  Vagrantfile
Labels: kind/test, cherry-pick/1.5.x, cherry-pick/1.6.x

#7542 Use `go env` to determine GOPATH in Makefile.
  Makefile
Labels: needs-ok-to-test

#7541 containerd should not print error log that failed to init a tracing processor while the tracing plugin is not loaded
  tracing/plugin/otlp.go
Labels: needs-ok-to-test

#7551 [release/1.6] cri: PodSandboxStatus should tolerate missing task
  pkg/cri/server/sandbox_status.go
Labels: cri

#7550 [release/1.5] migrate from k8s.gcr.io to registry.k8s.io
  contrib/ansible/cri-containerd.yaml
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/client_test.go
  integration/client/image_test.go
  integration/common.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: cri, ok-to-test

#7473 fix pusher concurrent close channel
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: ok-to-test

#7546 Add logging related metrics to Containerd CRI plugin
  pkg/cri/io/logger.go
  pkg/cri/io/metrics.go
Labels: kind/enhancement, cri, ok-to-test

#7571 [release/1.6] Add logging volume metrics to Containerd CRI plugin
  pkg/cri/io/logger.go
  pkg/cri/io/metrics.go
Labels: cri, ok-to-test

#7419 Configure CDI registry only on start
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts_linux.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/service_linux.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/service_linux.go
Labels: needs-ok-to-test

#7457 CRI: implement Controller.Delete for SandboxAPI
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/helpers_linux.go
  pkg/cri/sbserver/podsandbox/controller.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/sbserver/sandbox_remove.go
Labels: cri, needs-ok-to-test

#7569 Fix LogURI generation-related tests on Windows.
  cio/io_test.go
  cio/io_unix_test.go
  cio/io_windows_test.go
Labels: needs-ok-to-test

#7574 [release/1.6] adding support of CAP_BPF and CAP_PERFMON
  contrib/seccomp/seccomp_default.go
Labels: ok-to-test

#7581 Update GitHub actions release workflow set output
  .github/workflows/release.yml
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#7576 Cleanup sandbox interfaces
  api/next.pb.txt
  api/runtime/sandbox/v1/sandbox.pb.go
  api/runtime/sandbox/v1/sandbox.proto
  api/runtime/sandbox/v1/sandbox_ttrpc.pb.go
  api/services/sandbox/v1/sandbox.pb.go
  api/services/sandbox/v1/sandbox.proto
  api/services/sandbox/v1/sandbox_grpc.pb.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/sandbox_run.go
  runtime/v2/runc/pause/sandbox.go
  sandbox/controller.go
  sandbox_controller.go
  services/sandbox/controller_local.go
  services/sandbox/controller_service.go
Labels: status/merge-on-green

#7583 [release/1.5] cherry-pick: Migrate away from GitHub actions set-output
  .github/workflows/release.yml
Labels: needs-ok-to-test

#7025 Add Workflow for running critest with Hyper-V Containers on Windows.
  .github/workflows/windows-hyperv-periodic-trigger.yml
  .github/workflows/windows-hyperv-periodic.yml
  script/test/utils.sh
Labels: needs-ok-to-test

#7582 [release/1.6] cherry-pick: Migrate away from GitHub actions set-output
  .github/workflows/release.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#7537 Retry client connection in waitForStart
  integration/client/container_linux_test.go
  integration/client/daemon.go
Labels: ok-to-test

#7594 [release/1.6] ctr import: strictly match platform
  cmd/ctr/commands/images/import.go
Labels: needs-ok-to-test

#7588 fuzzing: improve archive fuzzer
  contrib/fuzz/archive_fuzzer.go
Labels: needs-ok-to-test
