Repository containerd/containerd, pull requests merged in 2022-07, with the labels that each got.

#6847 fix can't edit object by using ctr content edit command
  cmd/ctr/commands/content/content.go
Labels: easy-to-review

#7149 seccomp: allow clock_settime64 when CAP_SYS_TIME is added
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7124 update some devmapper docs
  docs/snapshotters/devmapper.md
Labels: needs-ok-to-test

#7158 cri doc: fix formatting for CDI options
  docs/cri/config.md
Labels: needs-ok-to-test

#7167 seccomp: add get_mempolicy, mbind, set_mempolicy, with CAP_SYS_NICE
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7153 Update install-protobuf script to install protobuf on Darwin
  script/setup/install-protobuf
Labels: easy-to-review

#7163 seccomp: seccomp: add syscalls related to PKU in default policy
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7174 docs: Fix sample config.toml syntax
  docs/man/containerd-config.toml.5.md
Labels: kind/docs, cherry-pick/1.5.x, cherry-pick/1.6.x

#7182 code cleanup
  cmd/ctr/commands/images/images.go
  pkg/cri/io/helpers.go
  remotes/docker/fetcher_test.go
Labels: needs-ok-to-test

#7173 test: Add ability to switch between cgroupv1 or cgroupv2 for node e2e
  test/e2e_node/gci-init.sh
Labels: ok-to-test

#7189 using ContextDialer instead
  pkg/ttrpcutil/client.go
Labels: needs-ok-to-test

#7198 cri_stats: handle missing cpu stats
  pkg/cri/server/container_stats_list.go
Labels: ok-to-test

#7201 Make getServicesOpts a helper
  integration/build_local_containerd_helper_test.go
  pkg/cri/cri.go
  runtime/restart/monitor/monitor.go
  services.go
Labels: kind/refactor

#7203 Drop deprecated `ioutil`
  archive/compression/benchmark_test.go
  integration/client/export_test.go
  integration/client/import_test.go
  integration/sandbox_clean_remove_windows_test.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux_test.go
  remotes/docker/config/docker_fuzzer_internal.go
  snapshots/lcow/lcow.go
Labels: ok-to-test

#7206 chore: bump macos runner version
  .github/workflows/ci.yml
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7215 Fix CRI image pull timeout test for ppc64le
  integration/image_pull_timeout_test.go
Labels: ok-to-test

#7221 Use `httputil.DumpRequestOut` for dumping client req
  cmd/ctr/commands/resolver.go
Labels: needs-ok-to-test

#7207 replace with selinux label
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/server/container_create_linux.go
Labels: needs-ok-to-test

#7220 Add extra context to error when push unauthorized
  remotes/docker/pusher.go
Labels: needs-ok-to-test

#7195 test: error strings should not be capitalized
  snapshots/testsuite/helpers.go
Labels: needs-ok-to-test

#7223 Windows HostProcess container CRI stats test
  integration/windows_hostprocess_test.go
Labels: cherry-pick/1.6.x

#7204 fix: support simultaneous create diff for same parent snapshot
  rootfs/diff.go
Labels: needs-ok-to-test
