Repository containerd/containerd, pull requests merged in 2022-03, with the labels that each got.

#6596 cri: relax test for system without hugetlb
  pkg/cri/server/container_update_resources_linux_test.go
  pkg/cri/server/service_test.go
Labels: ok-to-test

#6479 Adds support for Windows ArgsEscaped images
  oci/spec_opts.go
  oci/spec_opts_linux.go
  oci/spec_opts_unix.go
  oci/spec_opts_windows.go
  oci/spec_opts_windows_test.go
Labels: ok-to-test

#6603 Add --user support for ctr run Windows
  cmd/ctr/commands/run/run_windows.go
Labels: ok-to-test

#6568 Update TestContainerSymlinkVolumes to use windows path
  integration/container_volume_test.go
Labels: needs-ok-to-test

#6613 Use version 2 configuration format in docs/PLUGINS.md
  docs/PLUGINS.md
Labels: kind/docs, ok-to-test

#6595 cri: fix integration test on cgroupsv2 system
  integration/container_update_resources_test.go
Labels: ok-to-test

#6626 Run CRI integration tests in GitHub Actions (Windows)
  .github/workflows/ci.yml
  .github/workflows/windows-periodic.yml
  integration/addition_gids_test.go
  integration/container_log_test.go
  integration/pod_dualstack_test.go
  integration/pod_hostname_test.go
Labels: windows, needs-ok-to-test

#6617 Improve unexpected response error handling in resolver
  remotes/docker/resolver.go
  remotes/errors/errors.go
Labels: ok-to-test

#6658 Use temp file for export/import test
  integration/client/export_test.go
  integration/client/import_test.go
Labels: ok-to-test

#6423 Fuzzing: refactor metadata fuzzers
  contrib/fuzz/metadata_fuzzer.go
Labels: ok-to-test

#6663 Fix link in getting-started.md
  docs/getting-started.md
Labels: needs-ok-to-test

#6569 Update TestNormalize to only test Windows platform
  platforms/platforms_test.go
  platforms/platforms_windows_test.go
Labels: cherry-pick/1.6.x

#6661 Don't build a second copy of containerd-shim-runhcs-v1.exe
  .github/workflows/ci.yml
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#6618 Handle CRI Device.HostPath on Windows
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/commands_unix.go
  cmd/ctr/commands/commands_windows.go
  cmd/ctr/commands/run/run_windows.go
  integration/main_test.go
  integration/windows_device_test.go
  oci/spec_opts.go
  oci/spec_opts_test.go
  pkg/cri/opts/spec_windows.go
  pkg/cri/opts/spec_windows_test.go
  pkg/cri/server/container_create_windows.go
Labels: needs-ok-to-test

#6674 typo fixes under cmd.
  cmd/containerd-shim/main_unix.go
  cmd/containerd-stress/exec_worker.go
  cmd/containerd-stress/main.go
  cmd/containerd-stress/worker.go
  cmd/containerd/command/main_unix.go
Labels: needs-ok-to-test

#6519 ctr: improve error relative shim path error msg
  cmd/ctr/commands/commands.go
  runtime/v2/manager.go
  runtime/v2/manager_test.go
  runtime/v2/shim/util.go
Labels: ok-to-test

#6669 Enable gosec linter for golangci-lint
  .golangci.yml
  metadata/boltutil/helpers.go
  metadata/containers_test.go
  metadata/images_test.go
  oci/spec_opts_test.go
  services/containers/helpers.go
  services/images/helpers.go
Labels: needs-ok-to-test

#6660 Add shared content label to namespaces
  content/testsuite/testsuite.go
  docs/ops.md
  integration/client/content_test.go
  labels/labels.go
  metadata/content.go
  metadata/content_test.go
Labels: needs-ok-to-test

#6683 document log level and format
  docs/man/containerd-config.toml.5.md
  services/server/config/config.go
Labels: needs-ok-to-test

#6690 Update prometheus client vendor
  .github/workflows/ci.yml
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/server/container_stats.go
  pkg/cri/server/container_stats_list.go
  pkg/cri/server/sandbox_stats.go
  pkg/cri/server/sandbox_stats_list.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x

#6699 Remove gogoproto.customtype
  api/events/content.pb.go
  api/events/content.proto
  api/next.pb.txt
  api/services/content/v1/content.pb.go
  api/services/content/v1/content.proto
  api/services/tasks/v1/tasks.pb.go
  api/services/tasks/v1/tasks.proto
  api/types/descriptor.pb.go
  api/types/descriptor.proto
  container_checkpoint_opts.go
  content/proxy/content_reader.go
  content/proxy/content_store.go
  content/proxy/content_writer.go
  diff.go
  image_store.go
  services/content/contentserver/contentserver.go
  services/content/store.go
  services/diff/local.go
  services/images/helpers.go
  services/tasks/local.go
  task.go
  task_opts.go
Labels: impact/changelog

#6708 Remove enumvalue_customname, goproto_enum_prefix and enum_customname
  api/next.pb.txt
  api/services/content/v1/content.pb.go
  api/services/content/v1/content.proto
  api/services/snapshots/v1/snapshots.pb.go
  api/services/snapshots/v1/snapshots.proto
  api/types/task/task.pb.go
  api/types/task/task.proto
  container.go
  content/proxy/content_store.go
  content/proxy/content_writer.go
  contrib/snapshotservice/service.go
  runtime/v1/linux/process.go
  runtime/v1/linux/task.go
  runtime/v1/shim/service.go
  runtime/v2/process.go
  runtime/v2/runc/task/service.go
  runtime/v2/runc/v1/service.go
  runtime/v2/shim.go
  services/content/contentserver/contentserver.go
  services/snapshots/service.go
  services/tasks/local.go
  snapshots/proxy/proxy.go
Labels: impact/changelog, impact/breaking

#6651 Bug fix for mount path handling
  pkg/cri/opts/spec_windows.go
  pkg/cri/opts/spec_windows_test.go
Labels: needs-ok-to-test

#6722 native: fix deadlock from leaving transactions open
  snapshots/native/native.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#6721 moving up to go-cni v1.1.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/go-cni/.gitignore
  vendor/github.com/containerd/go-cni/Makefile
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x

#6323 cgroup2: monitor OOMKill instead of OOM to prevent missing container events
  pkg/oom/v2/v2.go
Labels: impact/changelog, needs-ok-to-test, cherry-pick/1.6.x

#6728 [release/1.6 backport] moving up to go-cni v1.1.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/go-cni/.gitignore
  vendor/github.com/containerd/go-cni/Makefile
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
  vendor/modules.txt
Labels: impact/changelog

#6713 fix: ctr images mount with snapshotter option can't get snapshotter
  cmd/ctr/commands/images/mount.go
Labels: needs-ok-to-test

#6740 Update README.md cncf landscape url
  README.md
Labels: needs-ok-to-test

#6743 added make help for cri integration
  BUILDING.md
  Makefile
  docs/cri/testing.md
Labels: ok-to-test

#6748 CI: bump up crun to 1.4.4
  script/setup/crun-version
  script/setup/install-runc
Labels: kind/test

#6747 CI: add Rocky Linux 8
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test, cherry-pick/1.6.x
