Repository containerd/containerd, pull requests merged in 2022-11, with the labels that each got.

#7611 overlayutils: Add fastpath for userxattr check
  snapshots/overlay/overlayutils/check.go
Labels: cherry-pick/1.6.x

#7610 [release/1.6] go.mod: Bump hcsshim to v0.9.5
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go
  vendor/modules.txt
Labels: ok-to-test

#7595 [release/1.5] feat: support import image for specific platform
  cmd/ctr/commands/images/import.go
  import.go
Labels: needs-ok-to-test

#7599 Harden GITHUB_TOKEN permissions for OSSF Scorecard
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/windows-hyperv-periodic-trigger.yml
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic-trigger.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#7615 ctr export strictly matching
  cmd/ctr/commands/images/export.go
Labels: cherry-pick/1.6.x

#7593 [release/1.5] ctr import: strictly match platform
  cmd/ctr/commands/images/import.go
Labels: needs-ok-to-test

#7626 docs: add additional info in backport process
  RELEASES.md
Labels: needs-ok-to-test

#7624 fix comments
  sys/reaper/reaper_unix.go
Labels: ok-to-test

#7604 Fix missing closed fifo
  runtime/v1/shim/service_linux.go
  runtime/v2/runc/platform.go
Labels: ok-to-test

#7453 Add tracing spans in CRI image service and pull.go
  docs/tracing.md
  integration/client/go.mod
  integration/client/go.sum
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/sbserver/image_remove.go
  pkg/cri/sbserver/image_status.go
  pkg/cri/sbserver/instrumented_service.go
  pkg/cri/server/helpers.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_remove.go
  pkg/cri/server/image_status.go
  pkg/cri/server/instrumented_service.go
  pkg/unpack/unpacker.go
  pull.go
  remotes/docker/resolver.go
  tracing/helpers.go
  tracing/log.go
  tracing/plugin/otlp.go
  tracing/tracing.go
Labels: status/merge-on-green, area/cri, ok-to-test

#7607 Support default hosts.toml configuration
  docs/hosts.md
  remotes/docker/config/config_unix.go
  remotes/docker/config/config_windows.go
Labels: impact/changelog, ok-to-test, cherry-pick/1.6.x

#7403 Fix "getCPUInfo for OS freebsd: not implemented" on FreeBSD/arm64
  platforms/cpuinfo.go
Labels: ok-to-test

#7460 remotes: add `FetcherByDigest` for fetching blobs without foreknown descriptors (useful for general-purpose CAS)
  cmd/ctr/commands/content/content.go
  remotes/docker/fetcher.go
  remotes/docker/resolver_test.go
  remotes/resolver.go
Labels: impact/changelog

#7627 [release/1.6] ctr export strictly match default platform
  cmd/ctr/commands/images/export.go
Labels: ok-to-test

#7513 Replace mount fork hack with CLONE_FS
  mount/fmountat_linux.go
  mount/fmountat_linux_test.go
  mount/mount_linux.go
  mount/mount_linux_test.go
  mount/subprocess_unsafe.s
  mount/subprocess_unsafe_gc.go
  mount/subprocess_unsafe_gccgo.go
Labels: impact/changelog

#7614 s390x: build and package s390x bin in release assets
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ok-to-test

#7638 Fix shim socket permissions on Darwin
  runtime/v2/shim/util_unix.go
Labels: ok-to-test

#7640 Extra documentation for content interfaces
  content/content.go
Labels: needs-ok-to-test

#7642 add oci.WithCPURT
  oci/spec_opts_linux.go
Labels: needs-ok-to-test

#7655 Add a thin wrapper around otel Span object
  docs/tracing.md
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/sbserver/image_remove.go
  pkg/cri/sbserver/image_status.go
  pkg/cri/sbserver/instrumented_service.go
  pkg/cri/server/helpers.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_remove.go
  pkg/cri/server/image_status.go
  pkg/cri/server/instrumented_service.go
  pkg/unpack/unpacker.go
  pull.go
  remotes/docker/resolver.go
  tracing/helpers.go
  tracing/tracing.go
Labels: needs-ok-to-test

#7629 Add `--debug` args to all subcommands of `ctr pprof`
  cmd/ctr/commands/pprof/pprof.go
Labels: needs-ok-to-test

#5263 feature: add gc scheduler metrics collection count
  gc/scheduler/metrics.go
  gc/scheduler/scheduler.go
Labels: impact/changelog, ok-to-test

#7661 Fix slice append error (`spec.Linux.Resources.HugepageLimits`)
  pkg/cri/server/helpers.go
  pkg/cri/store/container/status.go
Labels: ok-to-test, cherry-pick/1.5.x, cherry-pick/1.6.x

#7662 Bump OpenTelemetry contrib to v0.36.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/grpctrace.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/interceptorinfo.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/internal/parse.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/semconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/version.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/trace.go
  vendor/modules.txt
Labels: ok-to-test, dependencies

#7663 Bump k8s.io deps to v0.25.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/utils/net/port.go
  vendor/modules.txt
Labels: area/cri, ok-to-test, dependencies

#7523 add option to resolve symlinks in WithLinuxDevice
  oci/spec_opts.go
  oci/spec_opts_linux_test.go
Labels: ok-to-test

#7667 Fix broken link for CRI plugin in docs
  docs/cri/architecture.md
Labels: kind/docs

#7668 keep the lower case letter for flag info
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/commands_unix.go
  cmd/ctr/commands/images/mount.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/snapshots/snapshots.go
Labels: needs-ok-to-test

#7464 [release/1.5] Setup pod network after creating the sandbox container
  integration/main_test.go
  integration/restart_test.go
  integration/sandbox_run_rollback_linux_test.go
  pkg/cri/server/container_update_resources_windows.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_other.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/store/sandbox/status.go
  script/test/utils.sh
Labels: impact/changelog, area/cri, ok-to-test

#7670 complement sub-command note for containerd-main
  cmd/containerd/command/main.go
Labels: needs-ok-to-test

#7479 [release/1.5] retry request on writer reset
  content/helpers.go
  content/helpers_test.go
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: kind/bug, ok-to-test

#7686 Expose Done and Err in Shutdown service
  pkg/shutdown/shutdown.go
Labels: easy-to-review

#7678 tx rollback when GetInfo return error
  snapshots/overlay/overlay.go
Labels: needs-ok-to-test

#7691 CI: update Fedora to 37
  .cirrus.yml
  Vagrantfile
Labels: kind/test, cherry-pick/1.6.x

#7656 Update cri-api dependency to v0.26.0-beta.0
  Makefile
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  pkg/cri/sbserver/instrumented_service.go
  pkg/cri/sbserver/list_metric_descriptors.go
  pkg/cri/sbserver/list_pod_sandbox_metrics.go
  pkg/cri/sbserver/service.go
  pkg/cri/sbserver/version.go
  pkg/cri/server/instrumented_service.go
  pkg/cri/server/list_metric_descriptors.go
  pkg/cri/server/list_pod_sandbox_metrics.go
  pkg/cri/server/service.go
  pkg/cri/server/version.go
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/constants.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/terminal.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: impact/changelog, area/cri, ok-to-test

#7685 can set up the network serially by CNI plugins
  pkg/cri/config/config.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/cri/server/sandbox_run.go
Labels: needs-ok-to-test

#7703 Fsnotify bump and change code
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/sbserver/cni_conf_syncer.go
  pkg/cri/server/cni_conf_syncer.go
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/backend_fen.go
  vendor/github.com/fsnotify/fsnotify/backend_inotify.go
  vendor/github.com/fsnotify/fsnotify/backend_kqueue.go
  vendor/github.com/fsnotify/fsnotify/backend_other.go
  vendor/github.com/fsnotify/fsnotify/backend_windows.go
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/mkdoc.zsh
  vendor/github.com/fsnotify/fsnotify/system_bsd.go
  vendor/github.com/fsnotify/fsnotify/system_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: needs-ok-to-test

#7700 overlayfs: remove duplicated tx rollback
  snapshots/overlay/overlay.go
Labels: needs-ok-to-test

#7699 Missed out `platform interface` when reused the conn for Client.
  client.go
Labels: needs-ok-to-test

#7697 cri: add pod uid annotation
  pkg/cri/annotations/annotations.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/container_create_windows.go
  pkg/cri/sbserver/container_create_windows_test.go
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
  pkg/cri/sbserver/podsandbox/sandbox_run_windows.go
  pkg/cri/sbserver/podsandbox/sandbox_run_windows_test.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/server/sandbox_run_windows_test.go
Labels: needs-ok-to-test

#7707 Resolve Scorecards GitHub Actions workflow warnings
  .github/workflows/scorecards.yml
Labels: needs-ok-to-test

#7693 Add process_vm read and write calls to default seccomp profile
  contrib/seccomp/seccomp_default.go
Labels: needs-ok-to-test

#7499 runtime/v2/shim: clean up the use of containerdBinary
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/runc/v1/service.go
  runtime/v2/shim/shim.go
Labels: ok-to-test, kind/refactor

#7426 [port #5904 to sbserver] Setup pod network after creating the sandbox container
  integration/sandbox_run_rollback_test.go
  pkg/cri/sbserver/podsandbox/helpers.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/podsandbox/sandbox_stop.go
  pkg/cri/sbserver/restart.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/sbserver/sandbox_status.go
Labels: area/cri

#7470 Sandbox API: implement Controller.Status for SandboxAPI
  pkg/cri/sbserver/podsandbox/controller.go
  pkg/cri/sbserver/podsandbox/controller_test.go
  pkg/cri/sbserver/podsandbox/sandbox_stop.go
  pkg/cri/store/sandbox/status.go
Labels: area/cri, ok-to-test

#7706 Resolve warnings in Windows GitHub Actions periodic workflows
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#7669 make status more readable and update easy.
  cmd/ctr/commands/content/fetch.go
  cmd/ctr/commands/images/push.go
Labels: needs-ok-to-test

#7684 Fix sandbox API when calling sandboxed shims
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/podsandbox/helpers.go
  pkg/cri/sbserver/podsandbox/helpers_test.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/sbserver/sandbox_status.go
  pkg/cri/sbserver/service.go
  services/sandbox/controller_local.go
Labels: area/cri

#7714 Add ptrace readby and tracedby to default AppArmor profile
  contrib/apparmor/template.go
Labels: needs-ok-to-test

#7735 [release/1.6] cri: add pod uid annotation
  pkg/cri/annotations/annotations.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
  pkg/cri/server/sandbox_run_windows.go
  pkg/cri/server/sandbox_run_windows_test.go
Labels: needs-ok-to-test

#7736 use MaxConcurrentDownloads instead of MaxConcurrentUploadedLayers
  pull.go
Labels: needs-ok-to-test

#7708 Check for nullptr before dereferencing
  integration/sandbox_clean_remove_windows_test.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/server/helpers.go
Labels: ok-to-test

#7730 Add ctr image prune command
  cmd/ctr/commands/images/images.go
Labels: ok-to-test

#7702 Fix order of operations when setting lease labels
  leases/lease.go
  leases/lease_test.go
Labels: needs-ok-to-test

#7737 [release/1.6] Added nullptr checks to pkg/cri/server and sbserver
  integration/sandbox_clean_remove_windows_test.go
  pkg/cri/server/helpers.go
Labels: needs-ok-to-test
