Repository containerd/containerd, pull requests merged in 2022-04, with the labels that each got.

#6753 update runc to 1.1.1
  go.mod
  go.sum
  integration/client/go.sum
  script/setup/runc-version
  vendor/modules.txt
Labels: cherry-pick/1.6.x

#6752 [release/1.6] CI: add Rocky Linux 8
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test

#6756 BUILDING.md: update supported Go versions
  BUILDING.md
Labels: kind/docs

#6757 [Windows CI] Address some timeout issues
  .github/workflows/windows-periodic.yml
  script/setup/prepare_env_windows.ps1
Labels: needs-ok-to-test

#6755 Remove unmaintained contrib/linuxkit
  contrib/linuxkit/README.md
Labels: kind/docs

#6758 docs/getting-started.md: massive update
  docs/cri/installation.md
  docs/getting-started.md
Labels: kind/docs

#6751 Adding multi-arch support for the configure.sh script
  contrib/gce/configure.sh
Labels: needs-ok-to-test

#6709 Upgrade to Go 1.18
  go.mod
  go.sum
Labels: ok-to-test

#6768 Run go mod tidy in integration tests
  integration/client/go.mod
  integration/client/go.sum
Labels: needs-ok-to-test

#6754 Move historical docs to `docs/historical`
  docs/historical/cri/containerd.png
  docs/historical/cri/performance.png
  docs/historical/cri/proposal.md
  docs/historical/reports/2017-01-13.md
  docs/historical/reports/2017-01-20.md
  docs/historical/reports/2017-01-27.md
  docs/historical/reports/2017-02-10.md
  docs/historical/reports/2017-02-24.md
  docs/historical/reports/2017-03-10.md
  docs/historical/reports/2017-03-17.md
  docs/historical/reports/2017-03-24.md
  docs/historical/reports/2017-04-28.md
  docs/historical/reports/2017-05-05.md
  docs/historical/reports/2017-05-19.md
  docs/historical/reports/2017-05-26.md
  docs/historical/reports/2017-06-09.md
  docs/historical/reports/2017-06-23.md
Labels: kind/docs

#6774 [release/1.5] fix #6054 MaxConcurrentDownloads is not effect when Unpack is true
  unpacker.go
Labels: kind/bug

#6775 docs/getting-started.md: typo
  docs/getting-started.md
Labels: kind/docs

#6779 Skip flaky test on Windows
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6776 docs: remove runtime v1; migrate config v1 to v2
  docs/PLUGINS.md
  docs/garbage-collection.md
  docs/hosts.md
  docs/man/containerd-config.toml.5.md
  docs/managed-opt.md
  docs/ops.md
  docs/stream_processors.md
  docs/tracing.md
  snapshots/devmapper/README.md
Labels: kind/docs

#6702 CRI: improve image pulling performance
  image.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/service.go
  pkg/kmutex/kmutex.go
  pkg/kmutex/kmutex_test.go
  pkg/kmutex/noop.go
  unpacker.go
Labels: cri, kind/performance

#6777 mv design docs/historical/design
  docs/historical/design/architecture.md
  docs/historical/design/architecture.png
  docs/historical/design/data-flow.md
  docs/historical/design/data-flow.png
  docs/historical/design/lifecycle.md
  docs/historical/design/mounts.md
  docs/historical/design/snapshot_model.png
  docs/historical/design/snapshots.md
Labels: kind/docs

#6778 Add `docs/snapshotters`; simplify `docs/cri`
  docs/cri/config.md
  docs/cri/registry.md
  docs/snapshotters/README.md
  docs/snapshotters/devmapper.md
Labels: kind/docs

#6785 docs: add Deckhouse to the list of adopters
  ADOPTERS.md
Labels: needs-ok-to-test

#6790 Pin upload-cloud-storage action to 0.8.0 in Windows workflow.
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6788 metrics/cgroups: fix deadlock issue in Add during Collect
  Vagrantfile
  metrics/cgroups/common/type.go
  metrics/cgroups/metrics_test.go
  metrics/cgroups/v1/metrics.go
  metrics/cgroups/v2/metrics.go
Labels: priority/P1, cherry-pick/1.6.x

#6680 Optimize loading performance for cri recover
  pkg/cri/server/restart.go
Labels: needs-ok-to-test

#6789 tracing: fix panic on startup when configured
  tracing/plugin/otlp.go
Labels: needs-ok-to-test

#6805 Do not append []string{""} to command to preserve Docker compatibility
  pkg/cri/opts/spec.go
Labels: cri, ok-to-test, cherry-pick/1.6.x

#6806 check for duplicate nspath possibilities
  pkg/netns/netns_linux.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#6807 fix pool_device_test
  snapshots/devmapper/pool_device_test.go
Labels: ok-to-test

#6810 allow ptrace(2) by default for kernel >= 4.8
  contrib/seccomp/kernelversion/kernel_linux.go
  contrib/seccomp/kernelversion/kernel_linux_test.go
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.6.x

#6781 Set timeout when collecting metrics from shim's Stat
  metrics/cgroups/v1/metrics.go
  metrics/cgroups/v2/metrics.go
  metrics/metrics.go
Labels: ok-to-test

#6744 Add restart policy for enhanced restart manager
  integration/client/restart_monitor_test.go
  runtime/restart/monitor/change.go
  runtime/restart/monitor/monitor.go
  runtime/restart/restart.go
  runtime/restart/restart_test.go
Labels: impact/changelog, kind/enhancement

#6816 [release/1.6] CRI: improve image pulling performance
  image.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/service.go
  pkg/kmutex/kmutex.go
  pkg/kmutex/kmutex_test.go
  pkg/kmutex/noop.go
  unpacker.go
Labels: ok-to-test

#6829 Remove all gogoproto extensions
  Makefile
  api/events/task.pb.go
  api/events/task.proto
  api/next.pb.txt
  api/services/containers/v1/containers.pb.go
  api/services/containers/v1/containers.proto
  api/services/content/v1/content.pb.go
  api/services/content/v1/content.proto
  api/services/images/v1/images.pb.go
  api/services/images/v1/images.proto
  api/services/introspection/v1/introspection.pb.go
  api/services/introspection/v1/introspection.proto
  api/services/leases/v1/leases.pb.go
  api/services/leases/v1/leases.proto
  api/services/namespaces/v1/namespace.pb.go
  api/services/namespaces/v1/namespace.proto
  api/services/sandbox/v1/sandbox.pb.go
  api/services/sandbox/v1/sandbox.proto
  api/services/snapshots/v1/snapshots.pb.go
  api/services/snapshots/v1/snapshots.proto
  api/types/platform.pb.go
  api/types/platform.proto
  api/types/sandbox.pb.go
  api/types/sandbox.proto
  client.go
  cmd/ctr/commands/plugins/plugins.go
  containerstore.go
  content/proxy/content_store.go
  contrib/snapshotservice/service.go
  image_store.go
  leases/proxy/manager.go
  namespaces.go
  pkg/runtimeoptions/v1/api.pb.go
  pkg/runtimeoptions/v1/api.proto
  sandbox/helpers.go
  sandbox_store.go
  script/setup/install-dev-tools
  services/containers/helpers.go
  services/containers/local.go
  services/content/contentserver/contentserver.go
  services/images/helpers.go
  services/images/local.go
  services/introspection/local.go
  services/leases/service.go
  services/namespaces/local.go
  services/sandbox/store_local.go
  services/snapshots/service.go
  snapshots/proxy/proxy.go
Labels: impact/changelog

#6838 Add Container-Optimized OS into Adopters
  ADOPTERS.md
Labels: needs-ok-to-test

#6842 cri: close fifos when container is deleted
  pkg/cri/store/container/container.go
Labels: needs-ok-to-test

#6180 integration: Adds Windows equivalent for TestSandboxRemoveWithoutIPLeakage
  integration/main_test.go
  integration/sandbox_clean_remove_windows_test.go
Labels: ok-to-test

#5686 Add flag to allow oci.WithAllDevicesAllowed on PrivilegedWithoutHostDevices
  docs/cri/config.md
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: ok-to-test

#6851 images/image.go: typo
  images/image.go
Labels: needs-ok-to-test

#6150 feature: support image pull progress timeout
  integration/build_local_containerd_helper_test.go
  integration/build_local_containerd_helper_test_linux.go
  integration/image_pull_timeout_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/cri/server/image_pull.go
Labels: impact/changelog

#6858 Create ppc64le release
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: needs-ok-to-test

#6856 remove duplicate
  pkg/cri/opts/container.go
Labels: needs-ok-to-test

#6865 Bump opencontainers/selinux from 1.10.0 to 1.10.1
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go
  vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go
  vendor/modules.txt
Labels: ok-to-test, cherry-pick/1.6.x

#6868 Update go-cni to v1.1.5
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/go-cni/.golangci.yml
  vendor/github.com/containerd/go-cni/deprecated.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/modules.txt
Labels: ok-to-test

#6877 [release/1.6] Update go-cni to v1.1.5 backported due to conflict in go.mod
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/go-cni/.golangci.yml
  vendor/github.com/containerd/go-cni/deprecated.go
  vendor/github.com/containerd/go-cni/opts.go
  vendor/github.com/containernetworking/cni/libcni/conf.go
  vendor/github.com/containernetworking/cni/pkg/version/plugin.go
  vendor/modules.txt
Labels: ok-to-test

#5490 Support for cgroups blockio
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/run/run_unix.go
  docs/cri/config.md
  docs/man/containerd-config.toml.5.md
  oci/spec_opts_linux.go
  oci/spec_opts_nonlinux.go
  pkg/cri/config/config.go
  pkg/cri/server/blockio_linux.go
  pkg/cri/server/blockio_stub_linux.go
  pkg/cri/server/container_create_linux.go
  services/tasks/blockio_default.go
  services/tasks/blockio_linux.go
  services/tasks/local.go
  vendor/github.com/intel/goresctrl/pkg/blockio/blockio.go
  vendor/github.com/intel/goresctrl/pkg/blockio/config.go
  vendor/github.com/intel/goresctrl/pkg/blockio/kubernetes.go
  vendor/github.com/intel/goresctrl/pkg/blockio/oci.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupblkio.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupcontrol.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid_linux.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid_other.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/cgrouppath.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsi.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsimock.go
  vendor/github.com/intel/goresctrl/pkg/cgroups/fsios.go
  vendor/modules.txt
Labels: impact/changelog, kind/feature, ok-to-test, status/needs-discussion

#6875 docs: Adding windows installation steps to getting-started.md
  docs/getting-started.md
Labels: needs-ok-to-test
