Repository containerd/containerd, pull requests merged in 2022-08, with the labels that each got.

#7258 release: rollback Ubuntu to 18.04 (except for riscv64)
  .github/workflows/release.yml
  .github/workflows/release/Dockerfile
Labels: impact/changelog, priority/P0, cherry-pick/1.6.x

#7259 release workflow: increase timeout to 30 minutes & remove Go setup action
  .github/workflows/release.yml
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7265 Vagrantfile: dump containerd log after critest
  Vagrantfile
Labels: cri, kind/test

#7254 Switch to Go 1.19
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .zuul/playbooks/containerd-build/integration-test.yaml
  .zuul/playbooks/containerd-build/run.yaml
  .zuul/playbooks/containerd-build/unit-test.yaml
  Vagrantfile
  api/services/containers/v1/containers.pb.go
  api/services/containers/v1/containers.proto
  api/services/content/v1/content.pb.go
  api/services/content/v1/content.proto
  api/services/images/v1/images.pb.go
  api/services/images/v1/images.proto
  api/services/introspection/v1/introspection.pb.go
  api/services/introspection/v1/introspection.proto
  api/services/snapshots/v1/snapshots.pb.go
  api/services/snapshots/v1/snapshots.proto
  cmd/ctr/commands/cni.go
  content/local/store.go
  contrib/Dockerfile.test
  contrib/fuzz/daemon.go
  contrib/fuzz/oss_fuzz_build.sh
  filters/filter.go
  filters/parser.go
  filters/quote.go
  images/archive/importer.go
  integration/failpoint/cmd/cni-bridge-fp/main_linux.go
  integration/image_pull_timeout_test.go
  metadata/buckets.go
  metadata/db.go
  namespaces/store.go
  oci/spec_opts.go
  oci/spec_opts_nonlinux.go
  pkg/apparmor/apparmor.go
  pkg/cri/opts/spec.go
  pkg/cri/sbserver/events.go
  pkg/cri/server/events.go
  pkg/cri/streaming/server.go
  pkg/failpoint/fail.go
  pkg/ioutil/write_closer.go
  pkg/os/os_windows.go
  platforms/platforms.go
  process.go
  reference/docker/reference.go
  remotes/docker/config/hosts.go
  remotes/handlers.go
  script/setup/install-cni
  script/setup/install-critools
  script/setup/install-dev-tools
  script/setup/install-runc
  script/setup/install-seccomp
  script/setup/prepare_env_windows.ps1
  snapshots/devmapper/dmsetup/dmsetup.go
  snapshots/devmapper/pool_device.go
  snapshots/snapshotter.go
  snapshots/testsuite/testsuite.go
Labels: cherry-pick/1.6.x

#7298 [release/1.6] Do not append []string{""} to command to preserve Docker compatibility
  pkg/cri/opts/spec.go
Labels: ok-to-test

#7306 Don't fail test when GOOGLE_APPLICATION_CREDENTIALS is unset
  test/build-utils.sh
Labels: ok-to-test

#7301 Adding support of CAP_BPF and CAP_PERFMON
  contrib/seccomp/seccomp_default.go
Labels: ok-to-test, cherry-pick/1.6.x

#7286 Follow up #7254 (Switch to Go 1.19)
  contrib/fuzz/daemon.go
  pkg/cri/streaming/server.go
Labels: status/merge-on-green

#6906 ctr import: strictly match platform
  cmd/ctr/commands/images/import.go
Labels: ok-to-test

#7038 migrate from k8s.gcr.io to registry.k8s.io
  .github/workflows/ci.yml
  .github/workflows/windows-periodic.yml
  contrib/ansible/cri-containerd.yaml
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/client_test.go
  integration/client/image_test.go
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#6517 ContainerStatus to return container resources
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  integration/container_update_resources_test.go
  integration/containerd_image_test.go
  pkg/cri/sbserver/container_checkpoint.go
  pkg/cri/sbserver/container_events.go
  pkg/cri/sbserver/instrumented_service.go
  pkg/cri/server/container_checkpoint.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_events.go
  pkg/cri/server/container_status.go
  pkg/cri/server/container_update_resources.go
  pkg/cri/server/helpers.go
  pkg/cri/server/instrumented_service.go
  pkg/cri/store/container/status.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  vendor/modules.txt
Labels: status/merge-on-green, cri, ok-to-test

#7315 update runc binary to v1.1.4
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  script/setup/runc-version
  vendor/modules.txt
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#7324 Clarify containerd 1.5.0+ for k8s 1.20,1.21
  RELEASES.md
Labels: needs-ok-to-test

#7338 chore: remove duplicate word in comments
  oci/spec_opts_linux.go
  oci/spec_opts_nonlinux.go
  pkg/cri/sbserver/sandbox_portforward_linux.go
  pkg/cri/sbserver/sandbox_portforward_other.go
  pkg/cri/server/sandbox_portforward_linux.go
  pkg/cri/server/sandbox_portforward_other.go
  script/test/cri-integration.sh
Labels: needs-ok-to-test

#7326 Add kubernetes v1.25 supported version as v1.24
  RELEASES.md
Labels: ok-to-test
