Repository containerd/containerd, pull requests merged in 2022-01, with the labels that each got.

#6304 fix(ctr): enable networking for Windows containers
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
  cmd/ctr/commands/run/run_windows.go
  oci/spec_opts_windows.go
Labels: needs-ok-to-test

#6207 docs: improve plugin documentation
  docs/man/containerd-config.toml.5.md
Labels: needs-ok-to-test

#6403 content/local: use syscall.Timespec.Unix
  content/local/store_bsd.go
  content/local/store_openbsd.go
  content/local/store_unix.go
Labels: needs-ok-to-test

#6391 fix: use _ for consistency
  runtime/v1/linux/task.go
Labels: needs-ok-to-test

#6292 Integration: Check GCP secrets on Windows CI artifact upload.
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#6396 remotes/docker: allow fetching "refresh token" (aka "identity token", "offline token")
  remotes/docker/auth/fetch.go
  remotes/docker/authorizer.go
  remotes/docker/config/hosts.go
  remotes/docker/resolver_test.go
Labels: kind/enhancement

#6412 corrected link in cri architecture documentation
  docs/cri/architecture.md
Labels: needs-ok-to-test

#6413 update the adoption status of containerd in GKE
  ADOPTERS.md
Labels: needs-ok-to-test

#6416 Updating adoption of containerd for AKS
  ADOPTERS.md
Labels: needs-ok-to-test

#6419 Fix wrong log message
  pkg/cri/server/instrumented_service.go
Labels: needs-ok-to-test

#6418 test: e2e node COS cgroupv2 script
  test/e2e_node/gci-init.sh
Labels: ok-to-test

#6426 remove io/ioutil
  integration/container_update_resources_test.go
  integration/volume_copy_up_test.go
  runtime/v2/runc/manager/manager_linux.go
Labels: ok-to-test

#6397 Integration: Switch to using `auth` Gcloud action in Windows workflow.
  .github/workflows/windows-periodic-trigger.yml
  .github/workflows/windows-periodic.yml
Labels: ok-to-test

#6427 ctr: Unify the delete subcommand alias
  cmd/ctr/commands/containers/containers.go
  cmd/ctr/commands/images/images.go
  cmd/ctr/commands/leases/leases.go
  cmd/ctr/commands/snapshots/snapshots.go
  cmd/ctr/commands/tasks/delete.go
Labels: needs-ok-to-test

#6435 Add ppc64 support for test images
  integration/images/volume-copy-up/Makefile
  integration/images/volume-ownership/Makefile
Labels: ok-to-test

#6440 Revert "Add shared content label to namespaces"
  docs/ops.md
  labels/labels.go
  metadata/buckets.go
  metadata/buckets_test.go
  metadata/content.go
  metadata/images.go
Labels: impact/changelog, ok-to-test

#6451 [containerd-stress] delete useless code
  cmd/containerd-stress/density.go
Labels: needs-ok-to-test

#6466 [release/1.5] add-list-stat: return container list if filter is nil
  pkg/cri/server/container_stats_list.go
Labels: ok-to-test

#6463 Fix empty scopes return
  remotes/docker/scope.go
  remotes/docker/scope_test.go
Labels: needs-ok-to-test

#6476 Fix windows periodic workflow
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6481 Fix acr fetch token 400
  remotes/docker/authorizer.go
Labels: ok-to-test

#5828 shimv2: handle sigint/sigterm
  runtime/v2/shim/shim.go
  runtime/v2/shim/shim_unix.go
  runtime/v2/shim/shim_windows.go
Labels: ok-to-test

#6411 seccomp: add support for "swapcontext" syscall in default policy
  contrib/seccomp/seccomp_default.go
Labels: ok-to-test
