Repository containerd/containerd, pull requests merged in 2022-05, with the labels that each got.

#6885 docs: minor fixes in snapshots.Snapshotter comments
  snapshots/snapshotter.go
Labels: needs-ok-to-test

#6881 Update k8 docurl in file
  contrib/ansible/README.md
Labels: needs-ok-to-test

#6866 Cleanup leaked shim process
  runtime/v2/manager.go
  runtime/v2/shim_load.go
Labels: needs-ok-to-test

#6894 Update critools to v1.24
  Vagrantfile
  script/setup/critools-version
Labels: ok-to-test, cherry-picked/1.6.x

#6895 [release/1.6] Update critools to v1.24
  Vagrantfile
  script/setup/critools-version
Labels: ok-to-test

#6912 Pass explicit JUnit outfile to critest.exe in Windows workflow.
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#6915 (Vagrant CI) Enable git commands due to git CVE fix
  Vagrantfile
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#6938 Reverts removal of parallel run from critest
  Vagrantfile
  script/setup/critools-version
  script/setup/install-critools
Labels: ok-to-test, cherry-pick/1.6.x

#6942 [release/1.6] Reverts removal of parallel run from critest
  Vagrantfile
  script/setup/critools-version
  script/setup/install-critools
Labels: ok-to-test

#6910 shim: fix debug flag not working
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/shim/shim.go
Labels: needs-ok-to-test

#6946 Separate windows-2019 and windows-2022 test results
  .github/workflows/ci.yml
Labels: ok-to-test

#6929 [release/1.6] Bug fix for mount path handling
  pkg/cri/opts/spec_windows.go
  pkg/cri/opts/spec_windows_test.go
Labels: needs-ok-to-test

#6952 update doc url about k8s
  contrib/ansible/README.md
Labels: needs-ok-to-test

#6960 cmd/ctr/commands/content: fix typo in fetch command usage
  cmd/ctr/commands/content/fetch.go
Labels: needs-ok-to-test

#6956 adjust format in comment
  cmd/ctr/commands/commands.go
Labels: needs-ok-to-test

#6969 Fix Windows install powershell script
  docs/getting-started.md
Labels: needs-ok-to-test

#6972 config: improve config v1 deprecation message
  services/server/config/config.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#6978 Fix tx closed error when upperdirlabel specified
  snapshots/overlay/overlay.go
Labels: ok-to-test, cherry-pick/1.6.x

#6982 archive: add human-readable hint to Lchown error
  archive/tar.go
Labels: cherry-pick/1.5.x, cherry-pick/1.6.x

#6959 ctr sandbox: handle sandbox config
  cmd/ctr/commands/sandboxes/sandboxes.go
Labels: ok-to-test

#6954 ctr: fix label args used in NewContainer
  cmd/ctr/commands/run/run_unix.go
Labels: cherry-pick/1.6.x

#6937 sandbox: replace github.com/pkg/errors with native errors
  go.mod
  metadata/sandbox.go
  sandbox.go
Labels: needs-ok-to-test
