Repository containerd/containerd, pull requests merged in 2023-04, with the labels that each got.

#8343 CI: bump up crun to 1.8.3
  script/setup/crun-version
Labels: kind/test

#8345 [release/1.6] archive: consistently respect value of WithSkipDockerManifest
  images/archive/exporter.go
  integration/client/export_test.go
Labels: ok-to-test

#8344 [release/1.7] archive: consistently respect value of WithSkipDockerManifest
  images/archive/exporter.go
  integration/client/export_test.go
Labels: ok-to-test

#8351 oci: Use WithReadonlyTempMount when adding users/groups
  oci/spec_opts.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8136 [CRI] fix additionalGids: it should fallback to imageConfig.User when securityContext.RunAsUser,RunAsUsername are empty
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: kind/bug, ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8370 Follow Up for #8136
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux_test.go
Labels: needs-ok-to-test

#8375 update the version of the runc shim in the readme and examples
  runtime/v2/README.md
  runtime/v2/manager.go
Labels: needs-ok-to-test

#8384 update runc binary to v1.1.6
  script/setup/runc-version
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x

#8359 Fix argsEscaped tests
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  integration/windows_hostprocess_test.go
Labels: needs-ok-to-test

#8395 go.mod: remove redundant replace, and some cleaning-up
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
  vendor/modules.txt
Labels: cherry-picked/1.7.x

#8397 oci: partially restore comment on read-only mounts for uid/gid uses
  oci/spec_opts.go
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x

#8211 [release/1.7] Throw an error if the kubelet requests mounts with uid/gid mappings
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  pkg/cri/opts/spec_linux_opts.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/pkgbits/encoder.go
  vendor/golang.org/x/tools/internal/tokeninternal/tokeninternal.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: needs-ok-to-test

#8272 Fix image pulling with Transfer service
  plugins/transfer/plugin.go
Labels: ok-to-test, cherry-pick/1.7.x

#8413 ctr: Add sandbox flag to ctr run
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
  cmd/ctr/commands/run/run_windows.go
Labels: kind/enhancement

#8405 [release/1.7] Fix argsEscaped tests
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  integration/windows_hostprocess_test.go
Labels: needs-ok-to-test

#8416 Update transfer configuration
  plugins/transfer/plugin.go
Labels: cherry-pick/1.7.x

#8247 [release/1.6 ] Add ArgsEscaped support for CRI
  integration/common.go
  integration/image_list.sample.toml
  integration/windows_hostprocess_test.go
  oci/spec_opts_windows.go
  pkg/cri/opts/spec_windows.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/container_execsync.go
Labels: ok-to-test

#8328 doc: update CI signal information in README
  README.md
  releases/README.md
Labels: needs-ok-to-test

#8367 CRI Sbserver: Make PodSandboxStatus friendlier to shim crashes
  pkg/cri/sbserver/sandbox_status.go
Labels: kind/enhancement

#8430 [doc]Update external repo links that changed default branch to main
  code-of-conduct.md
  docs/cri/config.md
  docs/rootless.md
  pkg/netns/netns_linux.go
Labels: needs-ok-to-test

#8437 cri: Vendor v0.27.1
  go.mod
  go.sum
  integration/client/go.sum
  vendor/modules.txt
Labels: ok-to-test

#8393 runtime/shim: fix the nil checkpoint options
  runtime/v2/runc/container.go
Labels: needs-ok-to-test

#8444 [release/1.7] cri: Vendor v0.27.1
  go.mod
  go.sum
  integration/client/go.sum
  vendor/modules.txt
Labels: ok-to-test

#8414 Remove entry for container from container store on error
  pkg/cri/sbserver/container_remove.go
  pkg/cri/server/container_remove.go
Labels: needs-ok-to-test

#8456 [release/1.6] Remove entry for container from container store on error
  pkg/cri/server/container_remove.go
Labels: needs-ok-to-test

#8457 [release/1.7] Remove entry for container from container store on error
  pkg/cri/sbserver/container_remove.go
  pkg/cri/server/container_remove.go
Labels: needs-ok-to-test
