Repository containerd/containerd, pull requests merged in 2023-08, with the labels that each got.

#8316 fix: allow attaching to any combination of stdin/stdout/stderr
  cio/io.go
  cio/io_unix_test.go
Labels: ok-to-test

#8908 [release/1.6 backport] Upgrade GitHub actions packages in release workflow
  .github/workflows/release.yml
Labels: needs-ok-to-test

#8897 cri/sbserver: Use platform instead of GOOS for userns detection
  pkg/cri/sbserver/sandbox_run.go
Labels: needs-ok-to-test

#8910 [release/1.7] fix: allow attaching to any combination of stdin/stdout/stderr
  cio/io.go
  cio/io_unix_test.go
Labels: needs-ok-to-test

#8919 CI: move Vagrant tests to GitHub Actions (larger runners)
  .cirrus.yml
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8929 Makefile: allow REVISION be overwritten by environment
  Makefile
Labels: needs-ok-to-test

#8927 [release/1.6] cri: Don't use rel path for image volumes
  pkg/cri/server/container_create.go
Labels: needs-ok-to-test

#8427 CI: update Fedora to 38
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8926 [release/1.7] cri: Don't use rel path for image volumes
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/server/container_create.go
Labels: ok-to-test

#8928 Makefile: fix overriding go command
  Makefile
Labels: needs-ok-to-test

#8854 [release/1.6] Add stable ABI support in windows platform matcher + update hcsshim tag
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  platforms/defaults_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/platform_compat_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
  vendor/modules.txt
Labels: ok-to-test, cherry-pick/1.7.x

#8950 [release/1.7] Port fix for Linux Integration test failure
  pkg/cri/sbserver/container_stats_list.go
  pkg/cri/sbserver/container_stats_list_test.go
Labels: needs-ok-to-test

#8955 update runc to v1.1.9
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  script/setup/runc-version
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8930 CI: update Rocky Linux to 8.8
  .github/workflows/ci.yml
  Vagrantfile
  script/resize-vagrant-root.sh
Labels: kind/test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8778 Invoke stable ABI compliant platform check in windows matcher
  pkg/transfer/streaming/stream.go
  platforms/defaults_windows.go
  platforms/defaults_windows_test.go
  platforms/platforms.go
  platforms/platforms_other.go
  platforms/platforms_windows.go
Labels: needs-ok-to-test

#8954 *: fix leaked shim caused by high IO pressure
  Vagrantfile
  integration/issue7496_linux_test.go
  integration/issue7496_shutdown_linux_test.go
  pkg/cri/sbserver/events.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/server/events.go
  runtime/v2/shim.go
Labels: ok-to-test

#8922 feat: replace mcr.microsoft.com registry to ghcr.io/containerd registry
  integration/client/client_windows_test.go
  integration/client/image_test.go
  integration/sandbox_clean_remove_windows_test.go
Labels: ok-to-test, easy-to-review

#8975 cri: spec_linux: drop unused retvals
  pkg/cri/opts/spec_linux.go
Labels: needs-ok-to-test

#8964 FreeBSD: set default runtime
  defaults/defaults_freebsd.go
  defaults/defaults_linux.go
  defaults/defaults_unix.go
Labels: needs-ok-to-test, platform/freebsd

#8957 Go 1.21.0
  .devcontainer/devcontainer.json
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  BUILDING.md
  Vagrantfile
  contrib/Dockerfile.test
  contrib/apparmor/apparmor.go
  contrib/fuzz/oss_fuzz_build.sh
  contrib/seccomp/seccomp.go
  go.mod
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8985 [release/1.7] Backport remote/proxy differ
  contrib/diffservice/service.go
  diff.go
  diff/proxy/differ.go
  services/server/server.go
Labels: impact/changelog

#8946 bump client-go v0.26.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/modules.txt
Labels: ok-to-test

#8974 ctr: metrics: drop unused retval from printWindowsStats()
  cmd/ctr/commands/tasks/metrics.go
Labels: needs-ok-to-test

#8936 Makefile: add rule for installing documentation
  Makefile
Labels: needs-ok-to-test

#8986 [release/1.7] Add blockfile snapshotter
  cmd/containerd/builtins/builtins_linux.go
  cmd/containerd/builtins/builtins_unix.go
  docs/snapshotters/README.md
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  mount/losetup_linux.go
  mount/mount_linux.go
  pkg/testutil/helpers.go
  pkg/testutil/mount_other.go
  snapshots/blockfile/blockfile.go
  snapshots/blockfile/blockfile_loopsetup_test.go
  snapshots/blockfile/blockfile_other_test.go
  snapshots/blockfile/blockfile_test.go
  snapshots/blockfile/plugin/plugin.go
  snapshots/btrfs/btrfs_test.go
  snapshots/testsuite/helpers.go
  snapshots/testsuite/helpers_linux.go
  snapshots/testsuite/helpers_other.go
  snapshots/testsuite/testsuite_unix.go
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_unix.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/fstest/file.go
  vendor/modules.txt
Labels: impact/changelog

#8991 Docs: Document proxy plugins diff support
  docs/PLUGINS.md
Labels: kind/docs

#8990 Remove temporary replace for fuzzer library
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
  vendor/modules.txt
Labels: needs-ok-to-test

#8915 Makefile: allow overriding the binary executable target dir
  Makefile
Labels: needs-ok-to-test

#8889 archive/compression: update out of date RFC draft link
  archive/compression/compression.go
Labels: needs-ok-to-test

#8951 Populate commit memory for windows memory usage stats
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: needs-ok-to-test

#8945 Add WithMetaStore to overlay snapshotter to allow bringing your own
  snapshots/overlay/overlay.go
Labels: needs-ok-to-test

#8935 add metrics for discarding events
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/metrics.go
  pkg/cri/server/helpers.go
  pkg/cri/server/metrics.go
Labels: needs-ok-to-test

#8997 [release/1.7] Remove temporary replace
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
  vendor/github.com/AdamKorcz/go-118-fuzz-build/testing/unsupported_funcs.go
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/LICENSE
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/cyphar/filepath-securejoin/vfs.go
  vendor/modules.txt
Labels: ok-to-test

#8938 archive/tarheader: fix FreeBSD hdr for regular files
  archive/tarheader/tarheader_unix.go
Labels: needs-ok-to-test

#8663 MergeStringSlices use sets
  pkg/cri/util/strings.go
Labels: needs-ok-to-test

#8694 Fix ctr push image can't show right rate
  remotes/docker/pusher.go
  remotes/handlers.go
Labels: needs-ok-to-test

#8556 Update default platform matcher when ctr import
  cmd/ctr/commands/images/import.go
Labels: needs-ok-to-test

#9005 [release/1.7] Cherry-pick: [overlay] add configurable mount options to overlay snapshotter
  snapshots/overlay/overlay.go
  snapshots/overlay/overlay_test.go
  snapshots/overlay/plugin/plugin.go
Labels: ok-to-test

#9003 [releases/1.7] *: fix leaked shim caused by high IO pressure
  Vagrantfile
  integration/issue7496_linux_test.go
  integration/issue7496_shutdown_linux_test.go
  pkg/cri/sbserver/events.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/server/events.go
  runtime/v2/shim.go
Labels: ok-to-test

#9004 [releases/1.6] *: fix leaked shim caused by high IO pressure
  Vagrantfile
  integration/issue7496_linux_test.go
  pkg/cri/server/container_stop.go
  pkg/cri/server/events.go
  pkg/cri/server/sandbox_stop.go
Labels: ok-to-test

#8994 Use sandboxed CRI by default
  .github/workflows/ci.yml
  RELEASES.md
  Vagrantfile
  containerd.service
  contrib/Dockerfile.test
  integration/sandbox_run_rollback_test.go
  pkg/cri/config/config.go
  pkg/cri/cri.go
  script/test/cri-integration.sh
  script/test/utils.sh
Labels: impact/changelog, area/cri

#9007 Update critools to 1.28.0
  script/setup/critools-version
Labels: ok-to-test

#9011 go.mod: github.com/containerd/continuity v0.4.2
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/continuity/devices/mknod_freebsd.go
  vendor/github.com/containerd/continuity/driver/lchmod_unix.go
  vendor/github.com/containerd/continuity/fs/copy_unix.go
  vendor/github.com/containerd/continuity/fs/stat_atim.go
  vendor/modules.txt
Labels: cherry-picked/1.7.x

#9006 Update LTS description
  RELEASES.md
Labels: needs-ok-to-test

#9017 Remove redundant nil check
  container.go
  remotes/docker/config/hosts.go
Labels: needs-ok-to-test

#9021 make repositories of install dependencies configurable
  script/setup/install-cni
  script/setup/install-critools
  script/setup/install-runc
Labels: ok-to-test

#9025 [release/1.7 backport] make repositories of install dependencies configurable
  script/setup/install-cni
  script/setup/install-critools
  script/setup/install-runc
Labels: ok-to-test

#9024 [release/1.6 backport] make repositories of install dependencies configurable
  script/setup/install-cni
  script/setup/install-critools
  script/setup/install-runc
Labels: ok-to-test

#9030 Update hcsshim tag to v0.12.0-rc.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/.golangci.yml
  vendor/github.com/Microsoft/hcsshim/computestorage/helpers.go
  vendor/github.com/Microsoft/hcsshim/computestorage/storage.go
  vendor/github.com/Microsoft/hcsshim/computestorage/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/ext4/internal/compactext4/compact.go
  vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go
  vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/isolation_settings.go
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/log/format.go
  vendor/github.com/Microsoft/hcsshim/internal/log/scrub.go
  vendor/github.com/Microsoft/hcsshim/internal/safefile/safeopen.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/baselayerreader.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/converttobaselayer.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/legacy.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/offlinereg.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/ofreg.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/osversion/osversion_windows.go
  vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/export.go
  vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/import.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/pubsub.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/shared_buffer_pool.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: needs-ok-to-test

#9031 Revert "log: define G() as a function instead of a variable"
  log/context.go
Labels: cherry-pick/1.6.x, cherry-picked/1.7.x

#9028 Add missing unpacker.Wait for image import
  pkg/transfer/local/import.go
Labels: needs-ok-to-test
