Repository containerd/containerd, pull requests merged in 2023-02, with the labels that each got.

#8039 cmd/ctr/commands: clean up the func IntToInt32Array in utils.go
  cmd/ctr/commands/utils.go
Labels: needs-ok-to-test

#7989 Adding support to run install hcsshim from local clone
  script/setup/install-runhcs-shim
Labels: needs-ok-to-test

#8045 Fix sandbox exit monitor
  pkg/cri/sbserver/sandbox_run.go
Labels: area/cri

#8049 go.mod: Bump hcsshim to v0.10.0-rc.5
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/.gitignore
  vendor/modules.txt
Labels: needs-ok-to-test

#8071 Clean CI yaml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: easy-to-review, kind/cleanup

#8075 Fix retry logic within devmapper device deactivation
  snapshots/devmapper/pool_device.go
Labels: needs-ok-to-test

#8077 chore: use http constants instead of string
  cmd/ctr/commands/pprof/pprof.go
  remotes/docker/auth/fetch.go
Labels: needs-ok-to-test

#8076 fetch: Use data from descriptor when available.
  content/helpers.go
  remotes/handlers.go
Labels: impact/changelog

#8078 chore: clean up repeated package import
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_execsync.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_execsync.go
  pkg/cri/server/sandbox_run.go
  runtime/v2/shim/util.go
  tracing/plugin/otlp.go
  tracing/plugin/otlp_test.go
Labels: needs-ok-to-test

#8082 CI: skip some jobs when `repo != containerd/containerd`
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
Labels: kind/test, cherry-picked/1.5.x, cherry-picked/1.6.x

#8086 Revert `apparmor_parser` regression
  pkg/apparmor/apparmor.go
  pkg/apparmor/apparmor_linux.go
Labels: ok-to-test, cherry-pick/1.6.x

#8087 [release/1.6 backport] Revert `apparmor_parser` regression
  pkg/apparmor/apparmor.go
  pkg/apparmor/apparmor_linux.go
Labels: ok-to-test

#8088 [release/1.6] Fix retry logic within devmapper device deactivation
  snapshots/devmapper/pool_device.go
Labels: needs-ok-to-test

#8089 [release/1.5] Fix retry logic within devmapper device deactivation
  snapshots/devmapper/pool_device.go
Labels: needs-ok-to-test

#8091 CRI: Mirror generic toml runtime config under server
  pkg/cri/server/helpers.go
Labels: impact/changelog, area/cri, easy-to-review

#8093 Extract CRI instrument into separate package
  pkg/cri/instrument/instrumented_service.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/service.go
  pkg/cri/server/helpers.go
  pkg/cri/server/instrumented_service.go
  pkg/cri/server/service.go
Labels: area/cri, kind/refactor

#8094 [release/1.6] ctr/run: flags --detach and --rm cannot be specified together
  cmd/ctr/commands/run/run.go
Labels: needs-ok-to-test

#7984 test: add hostNetwork tests for both windows and linux
  pkg/cri/sbserver/helpers_test.go
  pkg/cri/sbserver/helpers_windows_test.go
  pkg/cri/server/helpers_test.go
  pkg/cri/server/helpers_windows_test.go
Labels: needs-ok-to-test

#8047 Send container events with nil PodSandboxStatus
  integration/container_event_test.go
  pkg/cri/sbserver/events.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/server/helpers.go
Labels: area/cri, ok-to-test

#8100 [sandbox] Use options to pass PodSandboxConfig to shims
  pkg/cri/sbserver/sandbox_run.go
  sandbox/controller.go
Labels: area/cri, easy-to-review

#8067 cni: pass in the cgroupPath capability argument
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/server/sandbox_run.go
  vendor/github.com/containerd/go-cni/.golangci.yml
  vendor/github.com/containerd/go-cni/namespace_opts.go
  vendor/github.com/containerd/go-cni/result.go
  vendor/github.com/containerd/go-cni/testutils.go
  vendor/github.com/containerd/go-cni/types.go
  vendor/github.com/containerd/go-cni/types_others.go
  vendor/github.com/containerd/go-cni/types_windows.go
  vendor/modules.txt
Labels: ok-to-test

#8060 CRI: Pass sandbox annotations to _other platforms
  pkg/cri/annotations/annotations.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/sbserver/podsandbox/sandbox_run_other.go
  pkg/cri/sbserver/podsandbox/sandbox_run_windows.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_other.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_other.go
  pkg/cri/server/sandbox_run_windows.go
Labels: kind/enhancement, area/cri, easy-to-review

#8052 Initial GRPC shims support
  plugins/sandbox/controller.go
  runtime/v2/binary.go
  runtime/v2/bridge.go
  runtime/v2/manager.go
  runtime/v2/shim.go
  runtime/v2/shim/shim.go
  runtime/v2/shim_load.go
  sandbox/bridge.go
Labels: impact/changelog, kind/enhancement

#8109 Go 1.19.6
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: cherry-picked/1.5.x, cherry-picked/1.6.x

#8113 Clean up repeated package import
  sandbox/proxy/controller.go
Labels: needs-ok-to-test

#8044 docs: fix function names in fuzzing test documentation
  integration/client/container_fuzzer.go
Labels: ok-to-test

#8041 pkg/cri/config: fix Mirrors deprecation comment
  pkg/cri/config/config.go
Labels: needs-ok-to-test

#8096 ctr version: add args check
  cmd/ctr/commands/version/version.go
Labels: needs-ok-to-test

#8103 Go 1.20.1
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  BUILDING.md
  Vagrantfile
  archive/compression/compression_test.go
  archive/tar.go
  cmd/containerd-stress/density.go
  cmd/containerd/main.go
  cmd/ctr/main.go
  content/helpers.go
  content/local/store.go
  content/local/store_test.go
  contrib/Dockerfile.test
  diff/walking/differ.go
  go.mod
  images/archive/importer.go
  integration/client/go.mod
  leases/id.go
  mount/losetup_linux.go
  pkg/cap/cap_linux_test.go
  pkg/cri/util/id.go
  pkg/kmutex/kmutex_test.go
  pkg/randutil/randutil.go
  pkg/seed/seed.go
  pkg/unpack/unpacker.go
  remotes/docker/config/hosts.go
  rootfs/apply.go
  script/setup/prepare_env_windows.ps1
  snapshots/testsuite/helpers.go
  snapshots/testsuite/testsuite.go
Labels: cherry-pick/1.6.x

#8124 runtime/v2: Log BootstrapParams
  runtime/v2/shim.go
Labels: kind/enhancement, easy-to-review

#8130 Fix concurrent writes for UpdateContainerStats
  pkg/cri/store/sandbox/sandbox.go
Labels: kind/bug, area/cri, ok-to-test, cherry-pick/1.6.x

#8115 Add macOS build note
  BUILDING.md
Labels: kind/docs, needs-ok-to-test

#8125 Migrate from k8s.gcr.io to registry.k8s.io
  .github/workflows/windows-hyperv-periodic.yml
Labels: platform/windows, needs-ok-to-test, kind/test, cherry-pick/1.6.x

#8143 Add Fields type alias to log package
  cmd/containerd/command/main.go
  cmd/ctr/commands/content/prune.go
  diff/apply/apply.go
  diff/lcow/lcow.go
  diff/windows/windows.go
  events/exchange/exchange.go
  integration/client/client_test.go
  integration/client/go.mod
  log/context.go
  pkg/transfer/local/pull.go
  pkg/unpack/unpacker.go
  remotes/docker/authorizer.go
  remotes/docker/resolver.go
  remotes/handlers.go
  runtime/v1/linux/runtime.go
  runtime/v1/shim/client/client.go
  runtime/v1/shim/service.go
  runtime/v2/shim/shim.go
  services/content/contentserver/contentserver.go
  snapshots/btrfs/btrfs.go
  snapshots/devmapper/snapshotter.go
Labels: easy-to-review

#8120 runtime/v2: Call onCloseWithShimLog for grpc shims
  runtime/v2/shim.go
Labels: kind/enhancement

#8153 [release/1.6] go.mod: Bump hcsshim to v0.9.7
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
  vendor/modules.txt
Labels: needs-ok-to-test

#8134 docs: Show how to select GRPC for shims
  runtime/v2/README.md
Labels: kind/docs

#8062 Add configuration options to local transfer service
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/resolver.go
  pkg/transfer/image/imagestore.go
  pkg/transfer/local/import.go
  pkg/transfer/local/pull.go
  pkg/transfer/local/push.go
  pkg/transfer/local/transfer.go
  pkg/transfer/proxy/transfer.go
  pkg/transfer/registry/registry.go
  pkg/transfer/transfer.go
  plugins/transfer/plugin.go
  remotes/resolver.go
Labels: needs-ok-to-test

#8165 [transfer]Config options followup
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/pull.go
  pkg/transfer/local/import.go
  pkg/transfer/local/pull.go
  pkg/transfer/local/pull_test.go
  pkg/transfer/local/transfer.go
Labels: needs-ok-to-test

#8140 pkg/nri: pull in latest NRI, update NRI configuration.
  docs/NRI.md
  go.mod
  go.sum
  integration/client/go.sum
  pkg/nri/config.go
  pkg/nri/nri.go
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/config.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/adaptation/result.go
  vendor/github.com/containerd/nri/pkg/api/mount.go
  vendor/github.com/containerd/nri/pkg/api/plugin.go
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/modules.txt
Labels: priority/P2

#8157 [release/1.6] Prepare release notes for v1.6.19
  releases/v1.6.19.toml
  version/version.go
Labels: needs-ok-to-test

#8152 update CDI version to v0.5.4
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux_test.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/internal/multierror/multierror.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/annotations.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache_test_unix.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache_test_windows.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits_unix.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits_windows.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/registry.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_linux.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/version.go
  vendor/modules.txt
Labels: ok-to-test

#8164 Rework install-protobuf script and add new targets
  script/setup/install-protobuf
Labels: kind/refactor
