Repository containerd/containerd, pull requests merged in 2023-03, with the labels that each got.

#8190 Update CRI guide link
  README.md
Labels: needs-ok-to-test

#7864 ctr/tasks: support remapped UID/GID
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
  cmd/ctr/commands/run/run_windows.go
  cmd/ctr/commands/tasks/start.go
  cmd/ctr/commands/tasks/tasks_unix.go
  cmd/ctr/commands/tasks/tasks_windows.go
Labels: needs-ok-to-test

#8193 Create config struct to take user input
  pkg/transfer/local/transfer.go
  plugins/transfer/plugin.go
Labels: ok-to-test

#7832 pkg/cri: add timeout to drain exec io
  docs/cri/config.md
  integration/container_exec_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/cri/sbserver/container_execsync.go
  pkg/cri/sbserver/container_execsync_test.go
  pkg/cri/server/container_execsync.go
  pkg/cri/server/container_execsync_test.go
  script/test/utils.sh
Labels: area/cri, cherry-picked/sbserver

#7099 [cri] Implement CRI Pod and Container stats for Windows
  pkg/cri/sbserver/sandbox_stats.go
  pkg/cri/sbserver/sandbox_stats_linux.go
  pkg/cri/sbserver/sandbox_stats_list.go
  pkg/cri/sbserver/sandbox_stats_other.go
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats.go
  pkg/cri/server/sandbox_stats_linux.go
  pkg/cri/server/sandbox_stats_list.go
  pkg/cri/server/sandbox_stats_other.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: ok-to-test

#8214 docs: fix typo of shim.RunManager's function comment
  runtime/v2/shim/shim.go
Labels: needs-ok-to-test

#8205 [Feature] Transfer tag image
  cmd/ctr/commands/images/tag.go
  pkg/transfer/archive/importer.go
  pkg/transfer/image/imagestore.go
  pkg/transfer/local/tag.go
  pkg/transfer/local/transfer.go
Labels: needs-ok-to-test

#8198 Add ArgsEscaped support for CRI
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  integration/windows_hostprocess_test.go
  oci/spec_opts_windows.go
  pkg/cri/opts/spec_nonwindows.go
  pkg/cri/opts/spec_windows.go
  pkg/cri/opts/spec_windows_opts.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/server/container_create_windows.go
  pkg/cri/server/container_create_windows_test.go
  pkg/cri/server/container_execsync.go
Labels: needs-ok-to-test

#8224 labels: Add LabelDistributionSource
  integration/client/image_test.go
  labels/labels.go
  remotes/docker/handler.go
  remotes/docker/handler_test.go
  remotes/handlers.go
Labels: ok-to-test

#8240 docs: link docs/managed-opt.md to client.Install
  install.go
Labels: needs-ok-to-test

#8232 Flag usage uses uppercase letters
  cmd/ctr/app/main.go
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/containers/checkpoint.go
  cmd/ctr/commands/containers/containers.go
  cmd/ctr/commands/containers/restore.go
  cmd/ctr/commands/content/content.go
  cmd/ctr/commands/content/fetch.go
  cmd/ctr/commands/events/events.go
  cmd/ctr/commands/images/convert.go
  cmd/ctr/commands/images/export.go
  cmd/ctr/commands/images/images.go
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/mount.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/images/tag.go
  cmd/ctr/commands/images/unmount.go
  cmd/ctr/commands/install/install.go
  cmd/ctr/commands/leases/leases.go
  cmd/ctr/commands/namespaces/namespaces.go
  cmd/ctr/commands/plugins/plugins.go
  cmd/ctr/commands/pprof/pprof.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_windows.go
  cmd/ctr/commands/sandboxes/sandboxes.go
  cmd/ctr/commands/snapshots/snapshots.go
  cmd/ctr/commands/tasks/attach.go
  cmd/ctr/commands/tasks/checkpoint.go
  cmd/ctr/commands/tasks/delete.go
  cmd/ctr/commands/tasks/exec.go
  cmd/ctr/commands/tasks/kill.go
  cmd/ctr/commands/tasks/list.go
  cmd/ctr/commands/tasks/metrics.go
  cmd/ctr/commands/tasks/pause.go
  cmd/ctr/commands/tasks/ps.go
  cmd/ctr/commands/tasks/resume.go
  cmd/ctr/commands/tasks/start.go
  cmd/ctr/commands/tasks/tasks.go
Labels: needs-ok-to-test

#8241 RELEASES.md: describe the deprecated config properties
  RELEASES.md
  pkg/cri/config/config.go
Labels: kind/docs

#8261 docs: fix typo in comment of plugin.Plugin.Err()
  plugin/context.go
Labels: needs-ok-to-test

#8263 Remove `aufs` snapshotter (deprecated since v1.5)
  BUILDING.md
  RELEASES.md
  SCOPE.md
  Vagrantfile
  archive/tar_opts_linux.go
  cmd/containerd/builtins/aufs_linux.go
  diff/apply/apply_linux.go
  diff/apply/apply_linux_test.go
  docs/snapshotters/README.md
  go.mod
  go.sum
  integration/client/go.sum
  snapshots/testsuite/testsuite.go
  test/build.sh
  vendor/github.com/containerd/aufs/.golangci.yml
  vendor/github.com/containerd/aufs/LICENSE
  vendor/github.com/containerd/aufs/README.md
  vendor/github.com/containerd/aufs/aufs.go
  vendor/github.com/containerd/aufs/plugin/plugin.go
  vendor/modules.txt
Labels: impact/changelog, kind/cleanup

#8213 archive: consistently respect value of WithSkipDockerManifest
  images/archive/exporter.go
  integration/client/export_test.go
Labels: ok-to-test, cherry-pick/1.6.x

#8267 Optimization containerd-stress
  cmd/containerd-stress/cri_worker.go
  cmd/containerd-stress/rlimit_freebsd.go
  cmd/containerd-stress/rlimit_unix.go
  cmd/containerd-stress/size.go
Labels: needs-ok-to-test

#8264 Remove "containerd.io/restart.logpath" label (deprecated since v1.5)
  RELEASES.md
  runtime/restart/monitor/change.go
  runtime/restart/monitor/monitor.go
  runtime/restart/restart.go
Labels: impact/changelog, kind/cleanup

#8257 Sandbox: Correct/add some fields to Status()
  plugins/sandbox/controller.go
Labels: kind/bug, kind/enhancement, cherry-pick/1.7.x

#8255 Sandbox: Cleanup shim on Start failure
  plugins/sandbox/controller.go
Labels: kind/enhancement, cherry-pick/1.7.x

#7951 Fix restarting containers that are being paused
  integration/client/restart_monitor_test.go
  runtime/restart/monitor/monitor.go
Labels: ok-to-test

#8277 CRI: Don't always close netConfMonitor channel
  pkg/cri/sbserver/service.go
  pkg/cri/sbserver/service_other.go
  pkg/cri/sbserver/service_windows.go
  pkg/cri/server/service.go
Labels: area/cri

#8275 Remove support for config.toml `version = 1`
  RELEASES.md
  docs/PLUGINS.md
  services/server/config/config.go
  services/server/config/config_test.go
  services/server/server.go
Labels: impact/changelog, kind/cleanup

#8175 adding cni metadata to the container in the `ctr run --config`
  cmd/ctr/commands/run/run_unix.go
  cmd/ctr/commands/run/run_windows.go
Labels: needs-ok-to-test

#8281 fix: 'failed to resolve symlink' error messaging
  pkg/cri/opts/spec_windows_opts.go
Labels: needs-ok-to-test

#8259 Add `ReadonlyMounts` to make overlay mounts readonly
  diff/walking/differ.go
  mount/mount.go
  mount/mount_test.go
  mount/temp.go
Labels: ok-to-test

#8279 Remove the CriuPath field from runc's options
  RELEASES.md
  docs/cri/config.md
  pkg/cri/config/config_unix.go
  runtime/v2/runc/options/next.pb.txt
  runtime/v2/runc/options/oci.pb.go
  runtime/v2/runc/options/oci.proto
Labels: impact/changelog, needs-ok-to-test, kind/cleanup

#8276 Remove CRI v1alpha2 [deprecated since v1.7]
  .github/workflows/ci.yml
  Protobuild.toml
  RELEASES.md
  docs/cri/crictl.md
  pkg/cri/constants/constants.go
  pkg/cri/cri.go
  pkg/cri/instrument/instrumented_service.go
  pkg/cri/sbserver/service.go
  pkg/cri/sbserver/version.go
  pkg/cri/server/service.go
  pkg/cri/server/version.go
  pkg/cri/util/alpha.go
  script/setup/prepare_env_windows.ps1
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api_grpc.pb.go
  third_party/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/constants.go
Labels: impact/changelog, area/cri, ok-to-test, kind/cleanup

#8274 [release/1.6]go.mod: Bump hcsshim tag to v0.9.8
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/modules.txt
Labels: needs-ok-to-test

#8300 [release/1.7 backport] Add `WithReadonlyTempMount` to create readonly temporary mounts
  diff/walking/differ.go
  mount/mount.go
  mount/mount_test.go
  mount/temp.go
Labels: ok-to-test

#8273 [release/1.6] Adds support for Windows ArgsEscaped images
  oci/spec_opts.go
  oci/spec_opts_linux.go
  oci/spec_opts_unix.go
  oci/spec_opts_windows.go
  oci/spec_opts_windows_test.go
Labels: needs-ok-to-test

#8299 [release/1.6 backport] Add `WithReadonlyTempMount` to create readonly temporary mounts
  diff/walking/differ.go
  mount/mount.go
  mount/mount_test.go
  mount/temp.go
Labels: ok-to-test

#8312 Defer uid lookups on Darwin
  oci/spec_opts.go
Labels: easy-to-review, cherry-pick/1.7.x

#8314 [backport 1.7] Defer uid lookups on Darwin
  oci/spec_opts.go
Labels: cherry-picked/1.7.x

#8278 Cleanup protobuild config
  Protobuild.toml
  api/Protobuild.toml
Labels: ok-to-test, kind/cleanup

#8323 update runc binary to v1.1.5
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  script/setup/runc-version
  vendor/modules.txt
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8306 [release/1.6]Updates oci image config to support upstream ArgsEscaped
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts.go
  oci/spec_opts_windows_test.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: ok-to-test

#8159 Initial split of sandboxed CRI service
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/sbserver/container_stats_list_linux.go
  pkg/cri/sbserver/container_stats_list_windows.go
  pkg/cri/sbserver/container_status.go
  pkg/cri/sbserver/container_status_test.go
  pkg/cri/sbserver/container_stop.go
  pkg/cri/sbserver/events.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/helpers_test.go
  pkg/cri/sbserver/images/image_list.go
  pkg/cri/sbserver/images/image_list_test.go
  pkg/cri/sbserver/images/image_pull.go
  pkg/cri/sbserver/images/image_pull_test.go
  pkg/cri/sbserver/images/image_remove.go
  pkg/cri/sbserver/images/image_status.go
  pkg/cri/sbserver/images/image_status_test.go
  pkg/cri/sbserver/images/imagefs_info.go
  pkg/cri/sbserver/images/imagefs_info_test.go
  pkg/cri/sbserver/images/metrics.go
  pkg/cri/sbserver/images/service.go
  pkg/cri/sbserver/images/service_test.go
  pkg/cri/sbserver/images/snapshots.go
  pkg/cri/sbserver/metrics.go
  pkg/cri/sbserver/podsandbox/controller.go
  pkg/cri/sbserver/podsandbox/helpers.go
  pkg/cri/sbserver/podsandbox/helpers_test.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/restart.go
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/service.go
  pkg/cri/sbserver/service_test.go
  pkg/cri/sbserver/test_config.go
Labels: area/cri, kind/refactor

#8327 Keep linux mounts for linux sandboxes on Windows/Darwin
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/container_create_other.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/sbserver/container_create_windows.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/helpers_linux.go
Labels: cherry-pick/1.7.x

#8331 [release/1.7] Keep linux mounts for linux sandboxes on Windows/Darwin
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/container_create_other.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/sbserver/container_create_windows.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/helpers_linux.go
Labels: ok-to-test

#8309 Add noexec nodev and nosuid to sandbox /etc/resolv.conf mount bind.
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: area/cri, ok-to-test, cherry-pick/1.7.x

#8335 [release/1.7] ctr/tasks: fix unmarshal the task metrics for cgroups v1
  cmd/ctr/commands/tasks/metrics.go
Labels: needs-ok-to-test

#8208 fix the task setting the runtime path
  container.go
  integration/client/container_test.go
  integration/client/go.mod
  task.go
  task_opts.go
Labels: needs-ok-to-test

#8336 [release/1.7] Add noexec nodev and nosuid to sandbox /etc/resolv.conf mount bind.
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: ok-to-test
