Repository containerd/containerd, pull requests merged in 2023-07, with the labels that each got.

#8768 ci: remove libseccomp-dev installation for nightly
  .github/workflows/nightly.yml
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8712 [release/1.7 backport] runtime/v2/runc: handle early exits w/o big locks
  runtime/v2/runc/container.go
  runtime/v2/runc/task/service.go
Labels: needs-ok-to-test

#8763 Move GetTopic function out of runc shim
  runtime/events.go
  runtime/v2/runc/task/service.go
  runtime/v2/runc/util.go
Labels: needs-ok-to-test

#8769 [release/1.7] go.mod: Update cgroups to 3.0.2
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/cgroups/v3/README.md
  vendor/github.com/containerd/cgroups/v3/cgroup1/blkio.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/cgroup.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/control.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/memory.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/opts.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/pids.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/rdma.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/systemd.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/utils.go
  vendor/github.com/containerd/cgroups/v3/cgroup1/v1.go
  vendor/github.com/containerd/cgroups/v3/cgroup2/devicefilter.go
  vendor/github.com/containerd/cgroups/v3/cgroup2/manager.go
  vendor/github.com/containerd/cgroups/v3/cgroup2/utils.go
  vendor/modules.txt
Labels: impact/changelog

#8755 integration/client: Rework withBytesBuffers
  integration/client/container_checkpoint_test.go
  integration/client/container_linux_test.go
  integration/client/container_test.go
Labels: kind/test

#8772 [release/1.7 backport] ci: remove libseccomp-dev installation for nightly
  .github/workflows/nightly.yml
Labels: ok-to-test

#8744 remotes: allow FetchByDigest client to pass mediatype as header
  cmd/ctr/commands/content/content.go
  remotes/docker/fetcher.go
  remotes/resolver.go
Labels: needs-ok-to-test

#8714 update go to go1.20.5, go1.19.10
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: cherry-picked/1.7.x

#8777 Fix the automatically restart issue when using LogURI and Terminal together
  cio/io.go
  runtime/restart/monitor/change.go
Labels: needs-ok-to-test

#8779 Fix net.ipv4.ping_group_range with userns
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: needs-ok-to-test

#8786 [release/1.7] Fix net.ipv4.ping_group_range with userns
  pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux.go
  pkg/cri/server/sandbox_run_linux_test.go
Labels: needs-ok-to-test

#8798 Modify loopback size
  snapshots/blockfile/blockfile_loopsetup_test.go
Labels: needs-ok-to-test

#8780 Uncopypaste parsing of OCI Bundle spec file
  cmd/containerd/command/oci-hook.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
  oci/spec.go
  runtime/v2/bundle.go
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/runc/util.go
Labels: ok-to-test

#8418 bugfix(port-forward): Correctly handle known errors
  pkg/cri/streaming/portforward/httpstream.go
Labels: ok-to-test

#8671 [cri] Handle pod transition states gracefully while listing pod stats
  pkg/cri/sbserver/sandbox_stats_linux.go
  pkg/cri/sbserver/sandbox_stats_list.go
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_linux.go
  pkg/cri/server/sandbox_stats_list.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: ok-to-test

#8805 [release/1.6 backport] bugfix(port-forward): Correctly handle known errors
  pkg/cri/streaming/portforward/httpstream.go
Labels: ok-to-test

#8821 [release/1.6 backport] Use version 2 configuration format in docs
  docs/PLUGINS.md
  docs/garbage-collection.md
  docs/hosts.md
  docs/man/containerd-config.toml.5.md
  docs/managed-opt.md
  docs/ops.md
  docs/stream_processors.md
  docs/tracing.md
  snapshots/devmapper/README.md
Labels: kind/docs

#8820 [release/1.6 backport] release: Add "cri-containerd.DEPRECATED.txt" in the deprecated cri-containerd-* bundles
  Makefile
  releases/cri-containerd.DEPRECATED.txt
Labels: kind/docs, area/cri

#8819 [release/1.6 backport] Fix concurrent writes for UpdateContainerStats
  pkg/cri/store/sandbox/sandbox.go
Labels: kind/bug, area/cri

#8825 [release/1.7 backport] cri: write generated CNI config atomically
  cmd/ctr/commands/commands.go
  pkg/atomicfile/file.go
  pkg/atomicfile/file_test.go
  pkg/cri/sbserver/update_runtime_config.go
  pkg/cri/server/update_runtime_config.go
  runtime/v2/shim/util.go
Labels: area/cri

#8823 [release/1.6 backport] [CRI] fix additionalGids: it should fallback to imageConfig.User when securityContext.RunAsUser,RunAsUsername are empty
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: kind/bug, area/cri

#8773 [release/1.6 backport] ci: remove libseccomp-dev installation for nightly
  .github/workflows/nightly.yml
Labels: ok-to-test

#8766 fix ci Linux Integration test fail
  pkg/cri/sbserver/container_stats_list.go
  pkg/cri/sbserver/container_stats_list_test.go
Labels: needs-ok-to-test

#8841 update runc binary to v1.1.8
  script/setup/runc-version
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x

#8412 Update go-restful to v3.10.1 in release/1.6
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/SECURITY.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/constants.go
  vendor/github.com/emicklei/go-restful/v3/container.go
  vendor/github.com/emicklei/go-restful/v3/cors_filter.go
  vendor/github.com/emicklei/go-restful/v3/filter_adapter.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/emicklei/go-restful/v3/parameter.go
  vendor/github.com/emicklei/go-restful/v3/request.go
  vendor/github.com/emicklei/go-restful/v3/response.go
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/github.com/emicklei/go-restful/v3/web_service.go
  vendor/modules.txt
Labels: needs-ok-to-test

#8852 Fix ro mount option being passed
  snapshots/overlay/overlayutils/check.go
Labels: ok-to-test

#8857 cri: memory.memsw.limit_in_bytes: no such file or directory
  pkg/cri/opts/spec_linux_opts.go
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8837 fix: `ctr images check -q` outputs not unpacked images
  cmd/ctr/commands/images/images.go
Labels: ok-to-test

#8862 Migrate to community bucket for node e2e tests
  contrib/gce/configure.sh
  test/push.sh
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8868 pkg/epoch: fix Y2038 on 32-bit hosts
  pkg/epoch/epoch.go
  pkg/epoch/epoch_test.go
Labels: cherry-pick/1.7.x

#8870 [release/1.6] cri: memory.memsw.limit_in_bytes: no such file or directory
  pkg/cri/opts/spec_linux.go
Labels: needs-ok-to-test

#8876 [release/1.6] migrate to community owned bucket for node e2e tests
  contrib/gce/configure.sh
  test/push.sh
Labels: ok-to-test

#8869 [release/1.7] cri: memory.memsw.limit_in_bytes: no such file or directory
  pkg/cri/opts/spec_linux_opts.go
Labels: ok-to-test

#8863 [release/1.6] Prepare release notes for v1.6.22
  .mailmap
  releases/v1.6.22.toml
  version/version.go
Labels: needs-ok-to-test

#8871 [release/1.7] Prepare release notes for v1.7.3
  .mailmap
  releases/v1.7.3.toml
  version/version.go
Labels: needs-ok-to-test

#8885 cri: Don't use rel path for image volumes
  integration/volume_copy_up_test.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/server/container_create.go
Labels: ok-to-test
