Repository containerd/containerd, pull requests merged in 2023-10, with the labels that each got.

#9173 update gitignore
  .gitignore
Labels: needs-ok-to-test

#9178 ci-fix: pin the mingw version 12.2.0.3042023
  .github/workflows/ci.yml
Labels: platform/windows, kind/test

#9179 Fix some assertions for integ tests
  integration/container_stats_test.go
  integration/container_stop_test.go
  integration/container_without_image_ref_test.go
  integration/containerd_image_test.go
  integration/image_pull_timeout_test.go
  integration/sandbox_run_rollback_test.go
  integration/truncindex_test.go
Labels: needs-ok-to-test

#9182 remotes: always try to establish tls connection when tls configured
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
  remotes/docker/resolver.go
  remotes/docker/resolver_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9155 Use mediatype helpers in more places
  container_opts.go
  integration/client/export_test.go
  oci/spec_opts.go
  pkg/display/manifest_printer.go
  pkg/snapshotters/annotations.go
  pkg/transfer/local/pull.go
  pkg/unpack/unpacker.go
  remotes/docker/converter.go
  remotes/docker/fetcher.go
  remotes/docker/pusher.go
  remotes/handlers.go
  signals.go
Labels: needs-ok-to-test

#8861 docker: return most relevant error from docker resolution
  remotes/docker/resolver.go
  remotes/docker/resolver_test.go
Labels: ok-to-test

#9184 Bump x/net to 0.13
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: ok-to-test

#9180 [release/1.6] Build binaries with 1.21.1
  .github/workflows/ci.yml
Labels: needs-ok-to-test

#9187 remotes/docker: Fix MountedFrom prefixed with target repository
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#9193 [release 1.7] remotes/docker: Fix MountedFrom prefixed with target repository
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: needs-ok-to-test

#9192 [release 1.6] remotes/docker: Fix MountedFrom prefixed with target repository
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: needs-ok-to-test

#8989 Add image delete target
  api/next.pb.txt
  api/services/images/v1/images.pb.go
  api/services/images/v1/images.proto
  image_store.go
  images/image.go
  metadata/images.go
  metadata/images_test.go
  services/images/local.go
Labels: impact/changelog

#9150 [release/1.6] Allow for images with artifacts to pull
  image.go
Labels: ok-to-test

#9149 [release/1.7] Allow for images with artifacts to pull
  image.go
Labels: ok-to-test

#9118 Fix windows default path overwrite
  oci/spec_opts.go
  oci/spec_opts_nonwindows.go
  oci/spec_opts_nonwindows_test.go
  oci/spec_opts_test.go
  oci/spec_opts_windows.go
  oci/spec_opts_windows_test.go
Labels: needs-ok-to-test

#9076 Fix `ip_pref` configuration option
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/sbserver/sandbox_run_test.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_run_test.go
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8934 Makefile: allow overriding GO_BUILD_FLAGS via environment
  Makefile
Labels: needs-ok-to-test

#9177 add Duration type to compatible toml v1 version
  pkg/imageverifier/bindir/bindir.go
  pkg/imageverifier/bindir/bindir_test.go
  pkg/nri/config.go
  pkg/tomlext/toml_v2_util.go
  plugins/imageverifier/plugin.go
Labels: ok-to-test

#9104 containerd-shim-runc-v2: avoid potential deadlock in create handler
  Makefile
  integration/client/container_linux_test.go
  integration/failpoint/cmd/runc-fp/issue9103.go
  integration/failpoint/cmd/runc-fp/main.go
  runtime/v2/runc/task/service.go
  script/setup/install-failpoint-binaries
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#9221 update to go1.21.3, go1.20.10
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9027 prevent ctr from creating tags with forbidden characters
  cmd/ctr/commands/images/tag.go
Labels: needs-ok-to-test

#9223 Introduce top level config migration
  RELEASES.md
  services/server/config/config.go
  services/server/config/config_test.go
  services/server/server.go
Labels: impact/changelog

#9205 add cpu-burst param to ctr command
  cmd/ctr/commands/run/run_unix.go
  oci/spec_opts.go
Labels: ok-to-test, easy-to-review

#9200 Use Intel ISA-L's igzip if available
  archive/compression/benchmark_test.go
  archive/compression/compression.go
  archive/compression/compression_test.go
Labels: impact/changelog

#9234 remotes: add handling for missing basic auth credentials
  remotes/docker/authorizer.go
  remotes/docker/resolver_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9215 Add a new image label if it is docker schema 1
  integration/containerd_image_test.go
  integration/images/image_list.go
  pull.go
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#9211 Use LOOP_CONFIGURE when creating loop devices
  mount/losetup_linux.go
Labels: ok-to-test

#9236 [release/1.6] remotes: add handling for missing basic auth credentials
  remotes/docker/authorizer.go
  remotes/docker/resolver.go
  remotes/docker/resolver_test.go
  remotes/errors/errors.go
Labels: impact/changelog

#9239 CRI: use (snapshotter_id, snapshot_key) to uniquely identify snapshots
  pkg/cri/server/container_stats_list.go
  pkg/cri/server/container_status_test.go
  pkg/cri/server/images/imagefs_info.go
  pkg/cri/server/images/imagefs_info_test.go
  pkg/cri/server/images/service.go
  pkg/cri/server/images/service_test.go
  pkg/cri/server/images/snapshots.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
  pkg/cri/server/service.go
  pkg/cri/server/test_config.go
  pkg/cri/store/snapshot/snapshot.go
  pkg/cri/store/snapshot/snapshot_test.go
Labels: ok-to-test

#9252 [release/1.7] Add a new image label if it is docker schema 1
  integration/containerd_image_test.go
  integration/images/image_list.go
  pull.go
Labels: ok-to-test

#9233 Switch runc shim to task service v3 and fix restore
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
  integration/issue7496_linux_test.go
  integration/issue7496_shutdown_linux_test.go
  runtime/v2/binary.go
  runtime/v2/bridge.go
  runtime/v2/example/example.go
  runtime/v2/manager.go
  runtime/v2/process.go
  runtime/v2/runc/container.go
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/runc/task/service.go
  runtime/v2/shim.go
  runtime/v2/shim/shim.go
  runtime/v2/shim/util.go
  runtime/v2/shim_load.go
  runtime/v2/shim_test.go
Labels: impact/changelog

#9267 [release/1.6] Add a new image label if it is docker schema 1
  integration/common.go
  integration/containerd_image_test.go
  pull.go
Labels: ok-to-test

#9283 Avoid TLS fallback when protocol is not ambiguous
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9294 Check scheme and host of request on push redirect
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9286 vendor: github.com/klauspost/compress v1.17.2
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/klauspost/compress/zstd/enc_best.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9274 fix bug that using invalid token to retry fetching layer
  remotes/docker/authorizer.go
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#9305 Update cli --help output for consistency
  cmd/containerd-stress/main.go
  cmd/containerd/command/main.go
  cmd/ctr/app/main.go
  docs/ops.md
Labels: ok-to-test
