Repository containerd/containerd, pull requests merged in 2023-01, with the labels that each got.

#7888 integration/images: switch away from Docker Hub to avoid rate limit
  integration/images/image_list.go
Labels: kind/test, easy-to-review, cherry-pick/1.6.x

#7894 reused package errdefs for error
  pkg/cri/server/bandwidth/fake_shaper.go
  pkg/cri/server/bandwidth/unsupported.go
Labels: ok-to-test

#7887 Vagrantfile: install-rootless-podman: remove `setenforce 0`
  Vagrantfile
Labels: kind/test, easy-to-review, cherry-pick/1.6.x

#7893 Fix TestUpdateContainerResources_Memory* on cgroup v2 hosts
  integration/container_update_resources_test.go
Labels: area/cri, kind/test, cherry-pick/1.6.x

#7906 Use the const labels.LabelUncompressed
  diff/walking/differ.go
  diff/windows/windows.go
  image.go
  images/archive/importer.go
  pkg/unpack/unpacker.go
  remotes/docker/schema1/converter.go
Labels: needs-ok-to-test, easy-to-review, kind/refactor

#7908 Vagrantfile: fix comments about SELinux
  Vagrantfile
Labels: kind/docs, kind/test, easy-to-review, cherry-pick/1.6.x

#7907 Vagrantfile: fix disk resize error with VirtualBox
  Vagrantfile
Labels: kind/test, easy-to-review, cherry-pick/1.6.x

#7913 CI: Pass GITHUB_TOKEN to containerd/project-checks
  .github/workflows/ci.yml
Labels: kind/test, cherry-pick/1.5.x, cherry-pick/1.6.x

#7891 contrib/Dockerfile.test: add "integration", "cri-integration", "critest" stages
  contrib/Dockerfile.test
  contrib/Dockerfile.test.d/docker-entrypoint.sh
Labels: kind/test, cherry-pick/1.6.x

#7892 Cirrus CI (Fedora 37, Rocky 8): enable cri-integration
  .cirrus.yml
  Vagrantfile
  integration/container_stats_test.go
  integration/main_test.go
  integration/nri_test.go
  integration/volume_copy_up_test.go
  integration/volume_copy_up_unix_test.go
Labels: area/cri, kind/test, cherry-pick/1.6.x

#7861 Add cleanup package for context management during cleanup
  metadata/db.go
  pkg/cleanup/context.go
  pkg/cleanup/context_test.go
  pkg/unpack/unpacker.go
  rootfs/diff.go
  runtime/v1/linux/bundle.go
  runtime/v1/linux/runtime.go
  runtime/v2/manager.go
  runtime/v2/shim.go
  runtime/v2/shim_load.go
Labels: cherry-pick/1.6.x

#7927 archive: improve TestSourceDateEpoch
  archive/tar_test.go
Labels: kind/test

#7932 mod: update github.com/pelletier/go-toml@v1.9.5
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/modules.txt
Labels: dependencies, cherry-pick/1.6.x

#7917 Refactor snapshotters metastore transaction
  snapshots/lcow/lcow.go
  snapshots/native/native.go
  snapshots/windows/windows.go
Labels: platform/windows, needs-ok-to-test, kind/refactor

#7935 Fix Flaky Windows CRI Integration test on TestContainerConsumedStats
  integration/container_stats_test.go
Labels: needs-ok-to-test

#7929 ctr/run: flags --detach and --rm cannot be specified together
  cmd/ctr/commands/run/run.go
Labels: cherry-pick/1.6.x

#7942 [release/1.6] mod: update github.com/pelletier/go-toml@v1.9.5
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/pelletier/go-toml/README.md
  vendor/github.com/pelletier/go-toml/SECURITY.md
  vendor/github.com/pelletier/go-toml/marshal.go
  vendor/github.com/pelletier/go-toml/parser.go
  vendor/github.com/pelletier/go-toml/toml.go
  vendor/modules.txt
Labels: dependencies

#7946 cri: Fix TestUpdateOCILinuxResource for host w/o swap controller
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_update_resources_linux_test.go
  pkg/cri/server/container_update_resources_linux_test.go
Labels: needs-ok-to-test, cherry-pick/1.6.x

#7957 fuzzing: improve archive fuzzer
  contrib/fuzz/archive_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
  vendor/github.com/AdaLogics/go-fuzz-headers/funcs.go
  vendor/github.com/AdaLogics/go-fuzz-headers/sql.go
  vendor/modules.txt
Labels: ok-to-test

#7948 update to go1.19.5, go1.18.10
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test

#7958 Use specs Platform instead of generated API
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/sbserver/podsandbox/controller.go
  platforms/platforms.go
  sandbox/controller.go
  sandbox/proxy/controller.go
Labels: area/cri, easy-to-review

#7960 Add basic spec and mounts for Darwin
  oci/spec.go
  oci/spec_opts_test.go
  oci/spec_test.go
  pkg/cri/opts/spec_darwin_opts.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_other_test.go
  pkg/cri/sbserver/container_create_test.go
Labels: area/cri, easy-to-review

#7963 use local variable for rt when iterating collectors
  metadata/gc.go
Labels: needs-ok-to-test

#7969 release/Dockerfile: set DEBIAN_FRONTEND=noninteractive
  .github/workflows/release/Dockerfile
Labels: easy-to-review, cherry-pick/1.6.x

#7973 Backport changes to sandboxed CRI
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/sbserver/sandbox_run.go
Labels: area/cri

#7968 CI: test release.yml on every PR
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: kind/test

#7985 pushWriter: correctly propagate errors
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
Labels: ok-to-test, cherry-pick/1.6.x

#8005 Reused package errdefs for not supported error
  runtime/v2/shim/shim_windows.go
Labels: needs-ok-to-test

#8009 [release/1.5] integration/images: switch away from Docker Hub to avoid rate limit
  integration/common.go
Labels: kind/test

#7959 Fix Memory Limit test
  integration/container_update_resources_test.go
Labels: needs-ok-to-test, cherry-pick/1.6.x

#8018 [release/1.6] add network plugin metrics
  pkg/cri/server/metrics.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_stop.go
  pkg/cri/server/update_runtime_config.go
Labels: impact/changelog, ok-to-test

#8021 release: Ubuntu 18.04 -> 20.04 (glibc 2.27 -> 2.31)
  .github/workflows/release.yml
  .github/workflows/release/Dockerfile
  releases/v1.7.0-beta.toml
Labels: impact/changelog

#8023 deflake: TestContainerPids
  integration/client/client_unix_test.go
  integration/images/image_list.go
Labels: easy-to-review

#8022 RELEASES.md: update release status
  RELEASES.md
Labels: easy-to-review

#8012 runtime docs: Clarify delete cwd behavior
  runtime/v2/README.md
  runtime/v2/binary.go
Labels: kind/docs

#8007 Move PLEG events for pause container under podsandbox package
  pkg/cri/sbserver/events.go
  pkg/cri/sbserver/podsandbox/controller.go
  pkg/cri/sbserver/podsandbox/sandbox_delete.go
  pkg/cri/sbserver/podsandbox/sandbox_run.go
  pkg/cri/sbserver/sandbox_remove.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/sbserver/service.go
Labels: area/cri

#8020 cri: mkdir /etc/cni with 0755, not 0700
  pkg/cri/sbserver/cni_conf_syncer.go
  pkg/cri/server/cni_conf_syncer.go
Labels: impact/changelog, area/cri, cherry-pick/1.6.x

#8030 [release/1.6] cri: mkdir /etc/cni with 0755, not 0700
  pkg/cri/server/cni_conf_syncer.go
Labels: impact/changelog, area/cri

#7840 Use mount.Target to specify subdirectory of rootfs mount
  cmd/ctr/commands/snapshots/snapshots.go
  container.go
  contrib/snapshotservice/service.go
  diff.go
  docs/snapshotters/README.md
  mount/mount.go
  mount/mount_freebsd.go
  mount/mount_linux.go
  mount/mount_linux_test.go
  mount/mount_unix.go
  mount/mount_unsupported.go
  mount/mount_windows.go
  mount/temp.go
  pkg/process/init.go
  runtime/v1/linux/runtime.go
  runtime/v1/shim/service.go
  runtime/v2/bundle.go
  runtime/v2/runc/container.go
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/runc/v1/service.go
  runtime/v2/shim.go
  runtime/v2/shim_load.go
  services/diff/local.go
  services/snapshots/service.go
  services/tasks/local.go
  snapshots/proxy/proxy.go
Labels: needs-ok-to-test

#7847 Add integration test to opentelemetry tracing on image pull
  integration/client/client_test.go
  integration/client/go.mod
  integration/client/go.sum
  integration/client/tracing.go
Labels: ok-to-test

#8013 fix(docs): minor fix on the windows installation steps
  docs/getting-started.md
Labels: needs-ok-to-test
