Repository containerd/containerd, pull requests merged in 2023-05, with the labels that each got.

#8337 Register imagePullThroughput and count with MiB
  pkg/cri/sbserver/images/image_pull.go
  pkg/cri/sbserver/images/metrics.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/metrics.go
Labels: needs-ok-to-test, cherry-pick/1.7.x

#8465 Windows integration: fix critest binary path in Azure-based workflow.
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#8467 Add faasd and actuated into the ADOPTERS file
  ADOPTERS.md
Labels: kind/docs, needs-ok-to-test

#8470 update go to go1.20.4, go1.19.9
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: cherry-picked/1.7.x

#8473 cri: Fix umarshal metrics
  pkg/cri/sbserver/container_stats_list_linux.go
  pkg/cri/server/container_stats_list_linux.go
Labels: ok-to-test

#8474 move to CRI-TOOLS v1.27.0
  script/setup/critools-version
Labels: area/cri, kind/test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8472 [release/1.7] cri: Fix umarshal metrics
  pkg/cri/sbserver/container_stats_list_linux.go
  pkg/cri/server/container_stats_list_linux.go
Labels: area/cri, ok-to-test

#8494 bump typeurl to v2.1.1
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/typeurl/v2/types.go
  vendor/modules.txt
Labels: cherry-pick/1.7.x

#8489 Change to Readdirnames for some cases
  content/local/store.go
  pkg/cri/opts/container.go
  runtime/v2/shim_load.go
Labels: kind/enhancement

#8497 Update ttrpc to v1.2.2
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/ttrpc/.golangci.yml
  vendor/github.com/containerd/ttrpc/Makefile
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/containerd/ttrpc/stream.go
  vendor/modules.txt
Labels: cherry-pick/1.7.x

#8498 go.mod: github.com/opencontainers/image-spec v1.1.0-rc3
  go.mod
  go.sum
  images/converter/default.go
  images/converter/uncompress/uncompress.go
  images/diffid.go
  images/mediatypes.go
  integration/client/go.mod
  integration/client/go.sum
  integration/client/import_test.go
  oci/spec_opts.go
  pkg/cri/opts/spec_windows.go
  remotes/handlers_test.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8252 CDI: Use CRI Config.CDIDevices field for CDI injection
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: ok-to-test

#8254 Fix access denied on mounted vhdx root
  archive/tar_opts_windows.go
  snapshots/windows/windows.go
Labels: needs-ok-to-test

#8488 cache image diffIDs
  image.go
Labels: ok-to-test

#8373 runtime/shim: rename RunManager to Run and remove `runc/v2/services` package
  cmd/containerd-shim-runc-v2/main.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/main_linux.go
  runtime/v2/example/cmd/main.go
  runtime/v2/example/example.go
  runtime/v2/runc/v2/service.go
  runtime/v2/shim/shim.go
Labels: needs-ok-to-test

#8507 snapshots/testsuite: Rename: fix fuse-overlayfs incompatibility
  snapshots/testsuite/issues.go
Labels: cherry-pick/1.7.x

#8510 [release/1.7 backport] snapshots/testsuite: Rename: fix fuse-overlayfs incompatibility
  snapshots/testsuite/issues.go
Labels: kind/test

#8464 CRI: Support Linux username for !linux platforms
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
Labels: kind/enhancement, area/cri, cherry-pick/1.7.x

#8518 Bump seccomp version to be the same as one in runc repo
  script/setup/install-seccomp
Labels: ok-to-test

#8401 fix unable to checkpoint the container more than once
  services/tasks/local.go
Labels: needs-ok-to-test

#8519 [release/1.7] CDI: Use CRI Config.CDIDevices field for CDI injection
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
Labels: needs-ok-to-test

#8531 bugfix: resolve symlink when looking up mountpoint
  mount/lookup_unix.go
Labels: needs-ok-to-test

#8534 Fix image workflow
  .github/workflows/build-test-images.yml
  integration/images/volume-copy-up/Makefile
  integration/images/volume-ownership/Makefile
Labels: needs-ok-to-test

#8547 [sandbox] Optimize metadata Schema notes to correctly match metadata structures
  metadata/buckets.go
Labels: needs-ok-to-test

#8576 notify readiness when registered plugins are ready
  cmd/containerd/command/main.go
  pkg/cri/cri.go
  pkg/cri/sbserver/service.go
  pkg/cri/server/service.go
  plugin/context.go
  services/server/server.go
Labels: ok-to-test

#8587 upgrade registry.k8s.io/pause version
  contrib/ansible/cri-containerd.yaml
  docs/cri/config.md
  docs/cri/crictl.md
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
Labels: ok-to-test

#8595 snapshots/blockfile: use passed in dst in scratchGenerator
  snapshots/blockfile/blockfile.go
Labels: needs-ok-to-test

#8586 Fix: Correct the spelling of repository within the NRI plugin documentation.
  docs/NRI.md
Labels: needs-ok-to-test

#8603 Add handling of a '.' commondir and bounds checking to mount_linux
  mount/mount_linux.go
  mount/mount_linux_test.go
Labels: ok-to-test

#8604 [release/1.7] Backport CRI sandbox server stats changes
  pkg/cri/sbserver/container_stats.go
  pkg/cri/sbserver/container_stats_list.go
  pkg/cri/sbserver/container_stats_list_linux.go
  pkg/cri/sbserver/container_stats_list_other.go
  pkg/cri/sbserver/container_stats_list_test.go
  pkg/cri/sbserver/container_stats_list_windows.go
  pkg/cri/sbserver/sandbox_stats_windows.go
Labels: area/cri

#8583 [release/1.6] notify readiness when registered plugins are ready
  cmd/containerd/command/main.go
  pkg/cri/cri.go
  pkg/cri/server/service.go
  plugin/context.go
  services/server/server.go
Labels: needs-ok-to-test

#8601 Add cpuset flags to 'ctr run'
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test

#8599 update auths code comment
  pkg/cri/config/config.go
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x

#8553 Windows Integration: Switch Azure-based CI to vanilla 2019 image.
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test

#8525 Add support for CDI devices to ctr run command
  cmd/ctr/commands/run/run_unix.go
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/opts/spec_nonlinux.go
Labels: needs-ok-to-test

#8606 Remove cni conf_template deprecation
  RELEASES.md
  docs/cri/config.md
  pkg/cri/config/config.go
Labels: area/cri, ok-to-test, cherry-pick/1.7.x

#8334 fix: cio.Cancel() should close the pipes
  cio/io_unix.go
Labels: ok-to-test, cherry-pick/1.7.x
