Repository containerd/containerd, pull requests merged in 2023-12, with the labels that each got.

#9444 mv pkg/process cmd/containerd-shim-runc-v2/process
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
  cmd/containerd-shim-runc-v2/process/deleted_state.go
  cmd/containerd-shim-runc-v2/process/exec.go
  cmd/containerd-shim-runc-v2/process/exec_state.go
  cmd/containerd-shim-runc-v2/process/init.go
  cmd/containerd-shim-runc-v2/process/init_state.go
  cmd/containerd-shim-runc-v2/process/io.go
  cmd/containerd-shim-runc-v2/process/io_test.go
  cmd/containerd-shim-runc-v2/process/io_util.go
  cmd/containerd-shim-runc-v2/process/process.go
  cmd/containerd-shim-runc-v2/process/types.go
  cmd/containerd-shim-runc-v2/process/utils.go
  cmd/containerd-shim-runc-v2/runc/container.go
  cmd/containerd-shim-runc-v2/runc/platform.go
  cmd/containerd-shim-runc-v2/task/service.go
Labels: kind/refactor, size/XS

#9441 [release/1.6] Windows default path overwrite fix
  oci/spec_opts.go
  oci/spec_opts_nonwindows.go
  oci/spec_opts_nonwindows_test.go
  oci/spec_opts_test.go
  oci/spec_opts_windows.go
  oci/spec_opts_windows_test.go
Labels: ok-to-test, size/L

#9453 [release/1.6] push: inherit distribution sources from parent
  content/content.go
  remotes/handlers.go
Labels: ok-to-test, size/M

#9448 [release/1.6] snapshots: emit deprecation warning for aufs
  pkg/deprecation/deprecation.go
  services/snapshots/service.go
Labels: area/snapshotter, size/S

#9447 runtime/v2: net.Dial gRPC shim sockets before trying grpc
  runtime/v2/shim.go
Labels: size/S

#9434 sandbox: add cri integration test case for upgrade
  integration/release_upgrade_linux_test.go
  pkg/cri/server/container_create.go
Labels: ok-to-test, size/L

#9391 sandbox: Move CRI Image Service and CRI Base seperate plugins
  contrib/fuzz/cri_sbserver_fuzzer.go
  contrib/fuzz/cri_server_fuzzer.go
  integration/image_pull_timeout_test.go
  pkg/cri/cri.go
  pkg/cri/server/base/cri_base.go
  pkg/cri/server/base/cri_base_test.go
  pkg/cri/server/container_status_test.go
  pkg/cri/server/images/service.go
  pkg/cri/server/podsandbox/controller.go
  pkg/cri/server/service.go
  pkg/cri/server/service_test.go
  plugins/types.go
Labels: ok-to-test, size/XL

#9450 [release/1.7] tasks: emit warning for v1 runtime and runc v1 runtime
  pkg/deprecation/deprecation.go
  services/tasks/local.go
  services/tasks/local_darwin.go
  services/tasks/local_freebsd.go
  services/tasks/local_unix.go
  services/tasks/local_windows.go
Labels: ok-to-test, area/runtime, size/M

#9458 [release/1.7] runtime/v2: net.Dial gRPC shim sockets before trying grpc
  runtime/v2/shim.go
Labels: size/S

#9461 pkg/process: Check using idmap mount options too
  cmd/containerd-shim-runc-v2/process/init.go
Labels: needs-ok-to-test, size/S

#9465 Don't block snapshot garbage collection on Remove failures
  snapshots/windows/windows.go
Labels: platform/windows, ok-to-test, area/snapshotter, size/XS

#9474 upgrade crun version from 1.9 to 1.12
  script/setup/crun-version
Labels: needs-ok-to-test, size/XS

#9469 [release/1.7] cri: add deprecation warnings for deprecated CRI configs
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/deprecation/deprecation.go
Labels: size/M

#9479 [release/1.7] Add cri-api v1alpha2 usage warning to all api calls
  pkg/cri/instrument/instrumented_service.go
Labels: area/cri, cherry-pick/1.6.x, size/M

#9480 Fix otel version incompatibility
  go.mod
  go.sum
  remotes/docker/resolver.go
  tracing/plugin/otlp.go
  tracing/tracing.go
  vendor/github.com/felixge/httpsnoop/.gitignore
  vendor/github.com/felixge/httpsnoop/.travis.yml
  vendor/github.com/felixge/httpsnoop/LICENSE.txt
  vendor/github.com/felixge/httpsnoop/Makefile
  vendor/github.com/felixge/httpsnoop/README.md
  vendor/github.com/felixge/httpsnoop/capture_metrics.go
  vendor/github.com/felixge/httpsnoop/docs.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_gteq_1.8.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_lt_1.8.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/client.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/doc.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/gen.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/labeler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/wrap.go
  vendor/go.opentelemetry.io/otel/semconv/internal/v2/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.17.0/httpconv/http.go
  vendor/modules.txt
Labels: cherry-pick/1.7.x, size/XXL

#9483 [release/1.7] Fix otel version incompatibility
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  remotes/docker/resolver.go
  tracing/plugin/otlp.go
  tracing/tracing.go
  vendor/github.com/felixge/httpsnoop/.gitignore
  vendor/github.com/felixge/httpsnoop/.travis.yml
  vendor/github.com/felixge/httpsnoop/LICENSE.txt
  vendor/github.com/felixge/httpsnoop/Makefile
  vendor/github.com/felixge/httpsnoop/README.md
  vendor/github.com/felixge/httpsnoop/capture_metrics.go
  vendor/github.com/felixge/httpsnoop/docs.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_gteq_1.8.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_lt_1.8.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/LICENSE
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/client.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/doc.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/gen.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/labeler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/wrap.go
  vendor/go.opentelemetry.io/otel/semconv/internal/v2/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.17.0/httpconv/http.go
  vendor/modules.txt
Labels: size/XXL

#9472 [release/1.6] update to go1.20.12, test go1.21.5
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#9482 [release/1.7] Don't block snapshot garbage collection on Remove failures
  snapshots/windows/windows.go
Labels: needs-ok-to-test, size/XS

#9486 release: add .dockerignore to fix repeated builds
  .github/workflows/release/Dockerfile
  .github/workflows/release/Dockerfile.dockerignore
Labels: size/S

#9352 [release/1.7] update to go1.20.12, test go1.21.5
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#9490 [release/1.6] Prepare release notes for v1.6.26
  releases/v1.6.26.toml
  version/version.go
Labels: size/M

#9491 [release/1.7] Prepare release notes for v1.7.11
  releases/v1.7.11.toml
  version/version.go
Labels: size/M

#9456 *: enable ARM64 runner
  .github/workflows/ci.yml
  mount/mount_idmapped_linux_test.go
  script/setup/install-critools
Labels: impact/changelog, kind/test, size/S

#9401 *: introduce image_pull_with_sync_fs in CRI
  api/next.pb.txt
  api/services/diff/v1/diff.pb.go
  api/services/diff/v1/diff.proto
  client/image.go
  contrib/diffservice/service.go
  diff/apply/apply.go
  diff/apply/apply_darwin.go
  diff/apply/apply_linux.go
  diff/apply/apply_other.go
  diff/diff.go
  diff/proxy/differ.go
  pkg/cri/config/config.go
  pkg/cri/config/config_unix.go
  pkg/cri/server/images/image_pull.go
  services/diff/local.go
Labels: size/L

#9503 go.mod: Bump up github.com/pelletier/go-toml to v2.1.1
  go.mod
  go.sum
  vendor/github.com/pelletier/go-toml/v2/.gitignore
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/SECURITY.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/modules.txt
Labels: size/M

#9496 Add nighly job to verify doc links (and fix broken links)
  .github/workflows/links.yml
  .lycheeignore
  README.md
  docs/cri/installation.md
  docs/historical/cri/proposal.md
  docs/historical/reports/2017-01-13.md
  releases/v1.1.0.toml
Labels: size/M

#9504 CI: enable dependabot
  .github/dependabot.yml
Labels: area/ci, size/S

#9492 Move GenerateRuntimeOptions() to pkg/cri/config
  pkg/cri/config/config.go
  pkg/cri/server/helpers.go
  pkg/cri/server/helpers_test.go
  pkg/cri/server/runtime_config_linux.go
  pkg/cri/server/sandbox_run.go
  plugins/types.go
Labels: area/cri, size/M

#9494 WithAppendAdditionalGroups: better /etc/group handling
  oci/spec_opts.go
  oci/spec_opts_linux_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/M

#9532 dependabot: enable groups
  .github/dependabot.yml
Labels: size/S

#9544 [release/1.7 backport] WithAppendAdditionalGroups: better /etc/group handling
  oci/spec_opts.go
  oci/spec_opts_linux_test.go
Labels: size/M

#9541 integration: fix format string for klog.Infof
  integration/remote/remote_runtime.go
Labels: size/XS

#9546 [release/1.6] Add warning for CRIU config usage
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/deprecation/deprecation.go
Labels: area/cri, area/criu, size/M

#9502 [release/1.7] *: enable ARM64 runner
  .github/workflows/ci.yml
  script/setup/install-critools
Labels: size/S

#9547 [release/1.6] cri: add deprecation warnings for deprecated CRI configs
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/deprecation/deprecation.go
Labels: size/M

#9495 Document `ns` query string added to mirror requests
  docs/hosts.md
Labels: needs-ok-to-test, size/M

#9543 [release/1.6 backport] WithAppendAdditionalGroups: better /etc/group handling
  oci/spec_opts.go
  oci/spec_opts_linux_test.go
Labels: size/M

#9488 tracing/plugin: newTracer: ignore context.Canceled errors on Close()
  tracing/plugin/otlp.go
Labels: size/XS

#9551 docs: fix CI badge in README
  README.md
Labels: size/XS

#9501 [release 1.7] backport: fix on dialer function for windows
  pkg/dialer/dialer_windows.go
Labels: platform/windows, needs-ok-to-test, size/S

#9567 [release/1.7] restart: containerd.io/restart.logpath warning
  pkg/deprecation/deprecation.go
  runtime/restart/monitor/change.go
  runtime/restart/monitor/monitor.go
Labels: size/M

#9572 [release/1.6] restart: containerd.io/restart.logpath warning
  pkg/deprecation/deprecation.go
  runtime/restart/monitor/change.go
  runtime/restart/monitor/monitor.go
Labels: size/M

#9571 shim: Create pid-file with 0644 permissions
  runtime/v2/shim/util.go
Labels: ok-to-test, cherry-pick/1.6.x, cherry-picked/1.7.x, size/XS

#9565 fix: return gRPC code "unavailable" if server is not initialized yet
  pkg/cri/instrument/instrumented_service.go
Labels: needs-ok-to-test, size/XS

#9570 [release/1.6 backport] go.mod: dario.cat/mergo v1.0.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  services/server/config/config.go
  vendor/dario.cat/mergo/.deepsource.toml
  vendor/dario.cat/mergo/.gitignore
  vendor/dario.cat/mergo/.travis.yml
  vendor/dario.cat/mergo/CODE_OF_CONDUCT.md
  vendor/dario.cat/mergo/CONTRIBUTING.md
  vendor/dario.cat/mergo/LICENSE
  vendor/dario.cat/mergo/README.md
  vendor/dario.cat/mergo/SECURITY.md
  vendor/dario.cat/mergo/doc.go
  vendor/dario.cat/mergo/map.go
  vendor/dario.cat/mergo/merge.go
  vendor/dario.cat/mergo/mergo.go
  vendor/modules.txt
Labels: size/L

#9569 [release/1.7 backport] go.mod: dario.cat/mergo v1.0.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  services/server/config/config.go
  vendor/dario.cat/mergo/.deepsource.toml
  vendor/dario.cat/mergo/.gitignore
  vendor/dario.cat/mergo/.travis.yml
  vendor/dario.cat/mergo/CODE_OF_CONDUCT.md
  vendor/dario.cat/mergo/CONTRIBUTING.md
  vendor/dario.cat/mergo/LICENSE
  vendor/dario.cat/mergo/README.md
  vendor/dario.cat/mergo/SECURITY.md
  vendor/dario.cat/mergo/doc.go
  vendor/dario.cat/mergo/map.go
  vendor/dario.cat/mergo/merge.go
  vendor/dario.cat/mergo/mergo.go
  vendor/modules.txt
Labels: size/L
