Repository containerd/containerd, pull requests merged in 2023-09, with the labels that each got.

#9036 Update hcsshim tag in runhcs-version script
  script/setup/runhcs-version
Labels: ok-to-test

#9041 .github: enable fuzz build
  .github/workflows/fuzz.yml
  contrib/fuzz/oss_fuzz_build.sh
Labels: easy-to-review

#9015 [release/1.7] CRI: Support Linux usernames for !linux platforms
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
Labels: area/cri

#5890 RFC: Initial support of idmapped mount points
  cmd/ctr/commands/run/run_unix.go
  integration/client/container_idmapped_linux_test.go
  mount/mount_idmapped_linux.go
  mount/mount_linux.go
  snapshots/overlay/overlay.go
  snapshots/overlay/overlay_test.go
  snapshots/overlay/overlayutils/check.go
  snapshots/overlay/plugin/plugin.go
  sys/subprocess_unsafe_linux.go
  sys/userns_unsafe_linux.go
Labels: ok-to-test

#9050 fix(docs): fix on the windows installation script
  docs/getting-started.md
Labels: needs-ok-to-test

#9061 CI: bump up crun to 1.8.7
  script/setup/crun-version
Labels: kind/test

#8792 content: reduce the contention between ref lock and boltdb lock
  content/local/store.go
  content/testsuite/testsuite.go
Labels: impact/changelog, ok-to-test

#9029 push: inherit distribution sources from parent
  cmd/ctr/commands/content/fetch.go
  cmd/ctr/commands/images/pull.go
  content/content.go
  pkg/display/manifest_printer.go
  remotes/handlers.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9063 [release/1.7] Update hcsshim tag to v0.11.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/hcsshim/osversion/platform_compat_windows.go
  vendor/modules.txt
Labels: needs-ok-to-test

#9060 task: expose criu work path opt
  task_opts.go
Labels: needs-ok-to-test

#9069 [release/1.7] Invoke Stable ABI compatibility function in windows platform matcher
  pkg/transfer/streaming/stream.go
  platforms/defaults_windows.go
  platforms/defaults_windows_test.go
  platforms/platforms.go
  platforms/platforms_other.go
  platforms/platforms_windows.go
Labels: needs-ok-to-test

#8909 Use canonical field_mask type
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  protobuf/types/types.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/fuzz.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/trie.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/genproto/LICENSE
  vendor/google.golang.org/genproto/protobuf/field_mask/field_mask.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/modules.txt
Labels: ok-to-test

#8330 remotes/docker: Add Mounted and Exists push status
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
  remotes/docker/status.go
Labels: ok-to-test

#8287 Add support for userns in stateless and stateful pods with idmap mounts (KEP-127, k8s >= 1.27)
  RELEASES.md
  docs/user-namespaces/README.md
  docs/user-namespaces/config.json
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  integration/main_test.go
  integration/pod_userns_linux_test.go
  pkg/cri/opts/spec_linux_opts.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_create_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_create_test.go
  pkg/process/init.go
  pkg/process/utils.go
  script/setup/crun-version
  vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: ok-to-test

#8493 Add image verifier transfer service plugin system based on a binary directory
  cmd/containerd/builtins/builtins.go
  docs/image-verification.md
  pkg/imageverifier/bindir/bindir.go
  pkg/imageverifier/bindir/bindir_test.go
  pkg/imageverifier/bindir/processes_unix.go
  pkg/imageverifier/bindir/processes_windows.go
  pkg/imageverifier/bindir/testdata/verifier_templates/verifier_test_input_output_management.go.tmpl
  pkg/imageverifier/bindir/testdata/verifiers/accept_reason_a.go
  pkg/imageverifier/bindir/testdata/verifiers/accept_reason_b.go
  pkg/imageverifier/bindir/testdata/verifiers/accept_reason_c.go
  pkg/imageverifier/bindir/testdata/verifiers/large_stderr.go
  pkg/imageverifier/bindir/testdata/verifiers/large_stderr_chunked.go
  pkg/imageverifier/bindir/testdata/verifiers/large_stdout.go
  pkg/imageverifier/bindir/testdata/verifiers/large_stdout_chunked.go
  pkg/imageverifier/bindir/testdata/verifiers/reject_reason_d.go
  pkg/imageverifier/bindir/testdata/verifiers/slow_child_process.go
  pkg/imageverifier/image_verifier.go
  pkg/transfer/local/pull.go
  pkg/transfer/local/transfer.go
  plugin/plugin.go
  plugins/imageverifier/path_unix.go
  plugins/imageverifier/path_windows.go
  plugins/imageverifier/plugin.go
  plugins/transfer/plugin.go
Labels: impact/changelog, kind/feature, area/cri, ok-to-test

#9108 Refactor: Removing inherently flaky and unused SourceDateEpochOrNow function.
  pkg/epoch/epoch.go
  pkg/epoch/epoch_test.go
Labels: ok-to-test

#9097 [release/1.7] remotes/docker: Add MountedFrom and Exists push status
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
  remotes/docker/status.go
Labels: ok-to-test

#9091 vendor: github.com/containerd/nri v0.5.0
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/nri/Makefile
  vendor/github.com/containerd/nri/client.go
  vendor/modules.txt
Labels: cherry-pick/1.7.x

#8356 Support for dropping inheritable capabilities
  oci/spec_opts.go
  oci/spec_opts_linux_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9111 [release/1.6] remotes/docker: Add MountedFrom and Exists push status
  remotes/docker/pusher.go
  remotes/docker/pusher_test.go
  remotes/docker/status.go
Labels: needs-ok-to-test

#9122 Improve doc of func NewNetNS
  pkg/netns/netns_linux.go
Labels: kind/docs, needs-ok-to-test

#9126 fix: Add `containerd` to the message type reference
  api/runtime/sandbox/v1/sandbox.proto
Labels: ok-to-test

#9106 [release/1.7 backport] alias log package to github.com/containerd/log v0.1.0
  .golangci.yml
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  log/context_deprecated.go
  log/context_test.go
  log/logtest/context_deprecated.go
  vendor/github.com/containerd/log/.golangci.yml
  vendor/github.com/containerd/log/LICENSE
  vendor/github.com/containerd/log/README.md
  vendor/github.com/containerd/log/context.go
  vendor/github.com/containerd/log/logtest/context.go
  vendor/github.com/containerd/log/logtest/log_hook.go
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/modules.txt
Labels: impact/changelog

#9112 Sandbox: Handle unexpected shim kill events
  pkg/cri/sbserver/events.go
  plugins/sandbox/controller.go
  services/sandbox/controller_service.go
  services/tasks/local.go
Labels: needs-ok-to-test

#9129 docs/userns: Clarify requirements for k8s 1.25/1.26
  docs/user-namespaces/README.md
Labels: needs-ok-to-test

#9142 Allow for images with artifacts layers to pull and run
  image.go
Labels: needs-ok-to-test

#9054 Fix usages of `mountinfo.PrefixFilter`
  mount/lookup_unix.go
  mount/mount.go
  mount/mount_unix.go
  mount/temp_unix.go
  pkg/cri/sbserver/helpers_linux.go
  pkg/cri/sbserver/podsandbox/helpers_linux.go
  pkg/cri/server/helpers_linux.go
Labels: needs-ok-to-test

#9154 images: use mediatype helpers
  images/archive/exporter.go
  images/handlers.go
  images/image.go
Labels: ok-to-test

#9117 Require opt-in for rootfs chown when idmap mounts is not supported
  docs/user-namespaces/README.md
  script/test/utils.sh
  snapshots/overlay/overlay.go
  snapshots/overlay/plugin/plugin.go
  snapshotter_opts_unix.go
Labels: ok-to-test

#9147 docs: Update `transfer` service docs to reflect completed implementations for `1.7`
  docs/transfer.md
Labels: kind/docs, needs-ok-to-test

#9153 Require plugins to succeed after registering readiness
  services/server/server.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#9164 cri: call RegisterReadiness after NewCRIService
  pkg/cri/cri.go
Labels: area/cri, cherry-pick/1.6.x, cherry-pick/1.7.x

#9158 cri: stop recommending disable_cgroup
  pkg/cri/sbserver/service_linux.go
  pkg/cri/server/service_linux.go
Labels: area/cri, cherry-pick/1.6.x, cherry-pick/1.7.x
