Repository containerd/containerd, pull requests merged in 2023-06, with the labels that each got.

#8582 fix(docs): minor fix on the windows installation steps
  docs/getting-started.md
Labels: platform/windows, needs-ok-to-test

#8588 Cleanup DEPRECATED TLS config
  integration/image_pull_timeout_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/cri/sbserver/images/image_pull.go
  pkg/cri/server/image_pull.go
Labels: ok-to-test

#8535 bugfix: add nil pointer check for cgroup v1 mem usage
  metrics/cgroups/v1/memory.go
Labels: ok-to-test

#8619 remotes/docker: ResolverOptions: fix deprecation comments
  remotes/docker/resolver.go
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x

#8627 docs: cherry-pick individual commits instead of merge commit
  RELEASES.md
Labels: needs-ok-to-test

#8624 [release/1.7] fix: cio.Cancel() should close the pipes
  cio/io_unix.go
Labels: ok-to-test

#8626 Fix issue for HPC pod metrics
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: needs-ok-to-test

#8628 Replace `atomicBool` with the standard library `atomic.Bool`
  pkg/process/init.go
  pkg/process/init_state.go
  pkg/process/utils.go
Labels: needs-ok-to-test

#8609 cri: write generated CNI config atomically
  cmd/ctr/commands/commands.go
  pkg/atomicfile/file.go
  pkg/atomicfile/file_test.go
  pkg/cri/sbserver/update_runtime_config.go
  pkg/cri/server/update_runtime_config.go
  runtime/v2/shim/util.go
Labels: area/cri, cherry-pick/1.6.x, cherry-pick/1.7.x

#8637 RELEASES.md: de-deprecation of CNI conf_template will be v1.7.3
  RELEASES.md
  pkg/cri/config/config.go
Labels: impact/changelog, kind/docs

#8634 [release/1.7] Fix issue for HPC pod metrics
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: needs-ok-to-test

#8572 Document Protocol Buffer Setup
  BUILDING.md
Labels: needs-ok-to-test

#8633 [CRI] Windows Pod Stats: Add a check to skip stats for containers that are not running.
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: needs-ok-to-test

#8652 fix release `ticker` correctly in `HandleProgress`
  pkg/transfer/local/progress.go
Labels: needs-ok-to-test

#8643 task: don't `close()` io before `cancel()`
  task.go
Labels: ok-to-test

#8362 Fix non C volumes on Windows
  integration/images/image_list.go
  integration/main_test.go
  integration/volume_copy_up_test.go
  pkg/cri/opts/container.go
  pkg/cri/sbserver/container_create.go
  pkg/cri/server/container_create.go
  script/test/cri-integration.sh
Labels: needs-ok-to-test

#8664 integration/client: add timeout to `TestShimOOMScore`
  integration/client/container_linux_test.go
Labels: needs-ok-to-test

#8668 [release/1.6] Revert "Downgrade MinGW to version 10.2.0"
  .github/workflows/ci.yml
Labels: needs-ok-to-test

#7944 CRI Pinned image support
  integration/containerd_image_test.go
  pkg/cri/labels/labels.go
  pkg/cri/sbserver/images/image_pull.go
  pkg/cri/sbserver/images/image_pull_test.go
  pkg/cri/sbserver/images/image_status.go
  pkg/cri/sbserver/images/service.go
  pkg/cri/server/helpers.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_pull_test.go
  pkg/cri/server/image_status.go
  pkg/cri/store/image/image.go
Labels: area/cri, ok-to-test

#8660 [release/1.6] update test box to fedora 37
  .github/workflows/ci.yml
Labels: ok-to-test

#8533 [release/1.6] Fix cpu architecture detection issue on emulated ARM platform
  platforms/cpuinfo.go
  platforms/cpuinfo_linux.go
  platforms/cpuinfo_linux_test.go
  platforms/cpuinfo_other.go
  platforms/cpuinfo_test.go
  platforms/database.go
Labels: ok-to-test

#8685 No more nondistributable layers in MS registry
  integration/client/convert_test.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8680 Sandbox: Add SandboxMetrics rpc
  api/next.pb.txt
  api/runtime/sandbox/v1/sandbox.pb.go
  api/runtime/sandbox/v1/sandbox.proto
  api/runtime/sandbox/v1/sandbox_grpc.pb.go
  api/runtime/sandbox/v1/sandbox_ttrpc.pb.go
  api/services/sandbox/v1/sandbox.pb.go
  api/services/sandbox/v1/sandbox.proto
  api/services/sandbox/v1/sandbox_grpc.pb.go
  pkg/cri/sbserver/podsandbox/sandbox_stats.go
  plugins/sandbox/controller.go
  runtime/v2/runc/pause/sandbox.go
  sandbox/bridge.go
  sandbox/controller.go
  sandbox/proxy/controller.go
  services/sandbox/controller_service.go
Labels: area/cri

#8617 runtime/v2/runc: handle early exits w/o big locks
  runtime/v2/runc/container.go
  runtime/v2/runc/task/service.go
Labels: needs-ok-to-test

#8654 [release/1.7] [cri] Windows Pod Stats: Add a check to skip stats for containers that are not running
  pkg/cri/sbserver/sandbox_stats_windows.go
  pkg/cri/sbserver/sandbox_stats_windows_test.go
  pkg/cri/server/sandbox_stats_windows.go
  pkg/cri/server/sandbox_stats_windows_test.go
Labels: ok-to-test

#8697 Fix unbound variable used by Prow
  test/build.sh
Labels: needs-ok-to-test

#8708 cri: drop unused arg from generateRuntimeOptions
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/helpers_test.go
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/server/helpers.go
  pkg/cri/server/helpers_test.go
  pkg/cri/server/sandbox_run.go
Labels: ok-to-test

#8720 [release/1.6] Pinned image support
  integration/containerd_image_test.go
  pkg/cri/labels/labels.go
  pkg/cri/server/helpers.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_pull_test.go
  pkg/cri/server/image_status.go
  pkg/cri/store/image/image.go
Labels: kind/enhancement, area/cri, ok-to-test

#8719 log when a lease expires
  metadata/gc.go
Labels: ok-to-test

#8718 [release/1.7] Pinned image support
  integration/containerd_image_test.go
  pkg/cri/labels/labels.go
  pkg/cri/sbserver/helpers.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/sbserver/image_pull_test.go
  pkg/cri/sbserver/image_status.go
  pkg/cri/server/helpers.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/image_pull_test.go
  pkg/cri/server/image_status.go
  pkg/cri/store/image/image.go
Labels: kind/enhancement, area/cri, ok-to-test

#8739 [1.6] Add Fields type alias to log package
  log/context.go
Labels: needs-ok-to-test

#8713 [release/1.6 backport] Adding support to run hcsshim from local clone
  script/setup/install-runhcs-shim
Labels: ok-to-test

#8752 seccomp: always allow name_to_handle_at
  contrib/seccomp/seccomp_default.go
Labels: ok-to-test

#8758 Update ginkgo to match cri-tools' version
  script/setup/install-critools
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x

#8753 [release/1.7 backport] seccomp: always allow name_to_handle_at
  contrib/seccomp/seccomp_default.go
Labels: needs-ok-to-test

#8754 [release/1.6 backport] seccomp: always allow name_to_handle_at
  contrib/seccomp/seccomp_default.go
Labels: needs-ok-to-test
