Repository containerd/containerd, pull requests merged in 2024-04, with the labels that each got.

#10023 Add IsNotFound case to ListPodSandboxStats
  internal/cri/server/sandbox_stats_list.go
Labels: size/XS

#10011 [release/1.6] Fix compile from version control system (source) use case
  go.mod
  go.sum
Labels: needs-ok-to-test, size/XS

#9908 Transfer: Registry: Enable to use registry configuration diretory
  api/next.pb.txt
  api/types/transfer/registry.pb.go
  api/types/transfer/registry.proto
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  core/transfer/registry/registry.go
Labels: impact/changelog, size/L

#10021 fix(cri): fix unexpected order of mounts since go 1.19
  internal/cri/opts/spec_darwin_opts.go
  internal/cri/opts/spec_linux_opts.go
  internal/cri/opts/spec_windows_opts.go
Labels: area/cri, size/XS

#10024 Transfer: Registry: Enable plain HTTP
  api/next.pb.txt
  api/types/transfer/registry.pb.go
  api/types/transfer/registry.proto
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  core/transfer/registry/registry.go
Labels: size/L

#10037 [release/1.7] Fix runc shim to only defer init process exits
  runtime/v2/runc/task/service.go
Labels: impact/changelog, area/runtime, size/XS

#10038 [release/1.6] Fix runc shim to only defer init process exits
  runtime/v2/runc/task/service.go
Labels: impact/changelog, size/XS

#10040 [release/1.6] Prepare for v1.6.31 release
  releases/v1.6.31.toml
  version/version.go
Labels: size/S

#10039 [release/1.7] Prepare for v1.7.15 release
  releases/v1.7.15.toml
  version/version.go
Labels: size/S

#7807 Update tracing documentation to add details about manual instrumentation
  docs/tracing.md
Labels: needs-ok-to-test, size/L

#10042 [release/1.7] Add IsNotFound case to ListPodSandboxStats
  pkg/cri/server/sandbox_stats_list.go
Labels: size/XS

#10031 remote: Fix HTTPFallback fails when pushing manifest
  core/remotes/docker/pusher_test.go
  core/remotes/docker/resolver.go
Labels: cherry-pick/1.7.x, size/M

#9992 [release 1.7] Add support for configuring otel from env and config deprecation notice
  RELEASES.md
  pkg/deprecation/deprecation.go
  tracing/plugin/otlp.go
  tracing/plugin/otlp_test.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/exporter.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/recorder.go
  vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/span.go
  vendor/modules.txt
Labels: impact/changelog, impact/deprecation, needs-ok-to-test, size/XL

#10045 [release/1.6] fix(cri): fix unexpected order of mounts since go 1.19
  pkg/cri/opts/spec_linux.go
  pkg/cri/opts/spec_windows.go
Labels: size/XS

#10044 [release/1.7] remote: Fix HTTPFallback fails when pushing manifest
  remotes/docker/pusher_test.go
  remotes/docker/resolver.go
Labels: size/M

#9415 Use different containerd sock address for integration test client
  integration/client/client.go
  integration/client/client_unix.go
  integration/client/client_windows.go
  integration/client/client_windows_test.go
Labels: size/M

#9419 cri: add sandbox image name to annotations
  internal/cri/annotations/annotations.go
  internal/cri/server/podsandbox/sandbox_run.go
  internal/cri/server/podsandbox/sandbox_run_linux.go
  internal/cri/server/podsandbox/sandbox_run_other.go
  internal/cri/server/podsandbox/sandbox_run_windows.go
Labels: area/cri, ok-to-test, area/snapshotter, size/M

#10054 core/diff/apply: use unix.Syncfs
  core/diff/apply/apply_linux.go
Labels: needs-ok-to-test, size/XS

#10060 Replace direct waitid syscall with unix.Waitid
  core/mount/mount_idmapped_linux.go
Labels: size/S

#10056 [release/1.7] Use different containerd sock address in tests
  integration/client/client.go
  integration/client/client_windows.go
  integration/client/client_windows_test.go
Labels: size/M

#9989 [release/1.7] Automatically decompress archives for transfer service import
  pkg/transfer/archive/importer.go
Labels: needs-ok-to-test, size/S

#10059 pkg/sys: Add helper to ignore eintr
  core/metrics/cgroups/v1/oom.go
  core/mount/mount_idmapped_linux.go
  pkg/archive/link_freebsd.go
  pkg/oom/v1/v1.go
  pkg/sys/eintr_unix.go
Labels: size/L

#10063 [release/1.7] fix(cri): fix unexpected order of mounts since go 1.19
  pkg/cri/opts/spec_darwin_opts.go
  pkg/cri/opts/spec_linux_opts.go
  pkg/cri/opts/spec_windows_opts.go
Labels: area/cri, size/XS

#10069 fix default working directory `hostProcess`
  internal/cri/server/container_create.go
Labels: needs-ok-to-test, size/XS

#10070 fix: close profile
  contrib/apparmor/apparmor_fuzzer.go
Labels: needs-ok-to-test, size/XS

#10071 [release/1.7] backport: fix default working directory `hostProcess`
  pkg/cri/sbserver/container_create.go
Labels: platform/windows, area/cri, needs-ok-to-test, size/XS

#10077 [release/1.7] Bump tags.cncf.io/container-device-interface to v0.7.2
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/service_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/service_linux.go
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/internal/multierror/multierror.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/default-cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/doc.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/registry.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec-dirs.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/version.go
  vendor/tags.cncf.io/container-device-interface/specs-go/config.go
  vendor/tags.cncf.io/container-device-interface/specs-go/oci.go
Labels: needs-ok-to-test, size/L

#10064 [release/1.6] fix bug that using invalid token to retry fetching layer
  remotes/docker/authorizer.go
Labels: size/S

#10065 [release/1.7] fix bug that using invalid token to retry fetching layer
  remotes/docker/authorizer.go
Labels: size/S

#10089 mod: bump github.com/containerd/nri@v0.6.1
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/modules.txt
Labels: impact/changelog, dependencies, cherry-pick/1.7.x, size/S, area/nri

#10097 [release/1.7] mod: bump github.com/containerd/nri@v0.6.1
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/modules.txt
Labels: impact/changelog, dependencies, size/S, area/nri

#10103 [release/1.6] Prevent GC from schedule itself with 0 period.
  gc/scheduler/scheduler.go
Labels: needs-ok-to-test, size/XS

#10102 [release/1.7] Prevent GC from schedule itself with 0 period.
  gc/scheduler/scheduler.go
Labels: needs-ok-to-test, size/XS

#10104 update to go1.21.9, go1.22.2
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/S

#10068 Account for ipv6 localhost in windows port forwarding
  internal/cri/server/sandbox_portforward_windows.go
Labels: size/S

#10008 [release/1.7] Add support for HPC port forwarding
  pkg/cri/sbserver/sandbox_portforward_windows.go
  pkg/cri/server/sandbox_portforward_windows.go
Labels: platform/windows, size/L

#10100 chore: use errors.New to replace fmt.Errorf with no parameters will much better
  cmd/ctr/commands/content/content.go
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/mount.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/tag.go
  cmd/ctr/commands/images/unmount.go
  cmd/ctr/commands/images/usage.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test, size/M

#10109 Update HTTP fallback to better account for TLS timeout and previous attempts
  cmd/ctr/commands/resolver.go
  core/remotes/docker/config/hosts.go
  core/remotes/docker/config/hosts_test.go
  core/remotes/docker/pusher_test.go
  core/remotes/docker/resolver.go
  core/remotes/docker/resolver_test.go
Labels: cherry-pick/1.6.x, status/needs-major-release, cherry-pick/1.7.x, size/L

#10111 apparmor: add `signal (receive) peer=/usr/local/bin/rootlesskit,`
  contrib/apparmor/template.go
Labels: cherry-pick/1.7.x, size/S

#10112 [release/1.7] Update HTTP fallback to better account for TLS timeout and previous attempts
  cmd/ctr/commands/resolver.go
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
  remotes/docker/pusher_test.go
  remotes/docker/resolver.go
  remotes/docker/resolver_test.go
Labels: size/L

#10115 [release/1.7 backport] update to go1.21.9, go1.22.2
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S

#10116 [release/1.7] apparmor: add `signal (receive) peer=/usr/local/bin/rootlesskit,`
  contrib/apparmor/template.go
Labels: size/S

#10117 [release/1.6 backport] update to go1.21.9, go1.22.2
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#10113 [release/1.6] Update HTTP fallback to better account for TLS timeout and previous attempts
  cmd/ctr/commands/resolver.go
  remotes/docker/config/hosts.go
  remotes/docker/config/hosts_test.go
  remotes/docker/pusher_test.go
  remotes/docker/resolver.go
  remotes/docker/resolver_test.go
Labels: size/L

#10122 [release/1.7] pod: CreatedAt time will be 269 years ago while creating cri network failed.
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/server/sandbox_run.go
Labels: size/XS

#10096 [release/1.7] Fix CRI snapshotter root path when not under containerd root
  pkg/cri/cri.go
  pkg/cri/server/service.go
  plugin/plugin.go
  services/server/config/config.go
  services/server/server.go
  snapshots/blockfile/plugin/plugin.go
  snapshots/btrfs/plugin/plugin.go
  snapshots/devmapper/plugin/plugin.go
  snapshots/native/plugin/plugin.go
  snapshots/overlay/plugin/plugin.go
Labels: impact/changelog, needs-ok-to-test, size/M

#10121 fix migrateConfig for io.containerd.cri.v1.images
  plugins/cri/images/plugin.go
  plugins/cri/images/plugin_test.go
Labels: needs-ok-to-test, size/L

#10098 Prepare release notes for v2.0.0-rc.1
  version/version.go
Labels: size/XS

#9894 fix(docs): fix duplicate instructions for windows installation
  docs/getting-started.md
Labels: needs-ok-to-test, size/S

#10125 Makefile: update default PACKAGE to v2
  Makefile
Labels: needs-ok-to-test, size/XS

#10123 apparmor: Allow confined runc to kill containers
  contrib/apparmor/template.go
Labels: impact/changelog, ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#10133 cri: introspectRuntimeFeatures: fix nil panic
  internal/cri/server/service.go
Labels: area/cri, size/XS

#10124 Add release notes for v1.7.16
  releases/v1.7.16.toml
  version/version.go
Labels: size/S

#10139 Add Syself Autopilot to adopters
  ADOPTERS.md
Labels: needs-ok-to-test, size/XS

#10140 ADOPTERS.md: Fix Actuated italics
  ADOPTERS.md
Labels: needs-ok-to-test, size/XS

#10145 pkg/cri/server/base: use structured log for CRI plugin startup and log config as embedded JSON
  plugins/cri/runtime/plugin.go
Labels: size/XS

#9853 sandbox: make an independent shim plugin
  core/runtime/v2/shim_load.go
  core/runtime/v2/shim_manager.go
  core/runtime/v2/task_manager.go
  core/runtime/v2/task_manager_test.go
  plugins/sandbox/controller.go
  plugins/types.go
Labels: ok-to-test, size/XL

#10110 go.mod: go 1.22
  .github/actions/install-go/action.yml
  .github/workflows/release.yml
  BUILDING.md
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  go.mod
  script/setup/install-runc
  script/setup/prepare_env_windows.ps1
Labels: size/S

#10152 optimize error logs by providing absolute file paths
  core/remotes/docker/config/hosts.go
Labels: needs-ok-to-test, size/XS
