Repository containerd/containerd, pull requests merged in 2024-01, with the labels that each got.

#9593 update runc binary to v1.1.11
  script/setup/runc-version
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9596 [release/1.7 backport] update runc binary to v1.1.11
  script/setup/runc-version
Labels: size/XS

#9597 [release/1.6 backport] update runc binary to v1.1.11
  script/setup/runc-version
Labels: size/XS

#9554 import/export: Support references to missing content
  client/import.go
  content/helpers.go
  images/archive/exporter.go
  integration/client/export_test.go
  integration/client/import_test.go
Labels: ok-to-test, size/XL

#9601 Fix CimFS plugin init error
  diff/windows/cimfs.go
  snapshots/windows/cimfs.go
Labels: platform/windows, size/XS

#9600 [release/1.7 backport] import/export: Support references to missing content
  content/helpers.go
  images/archive/exporter.go
  import.go
  integration/client/export_test.go
  integration/client/go.mod
  integration/client/import_test.go
Labels: needs-ok-to-test, size/XL

#9477 add get cgroupdriver from RuntimeConfig to integration
  integration/cri-api/pkg/apis/services.go
  integration/main_test.go
  integration/remote/remote_runtime.go
Labels: ok-to-test, size/M

#9603 integration: remove use of golang.org/x/sys/execabs
  integration/release_upgrade_utils_linux_test.go
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/modules.txt
Labels: size/L

#9608 [Windows] Use latest VM image in CI to get Windows updates regularly
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic.yml
Labels: size/XS

#9606 [release/1.6 backport] remove github.com/opencontainers/runc dependency
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts.go
  vendor/github.com/moby/sys/user/LICENSE
  vendor/github.com/moby/sys/user/lookup_unix.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/user_fuzzer.go
  vendor/github.com/opencontainers/runc/NOTICE
  vendor/modules.txt
Labels: size/M

#9605 [release/1.7] update to CDI v0.6.1, and remove github.com/opencontainers/runc dependency
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  oci/spec_opts.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/internal/validation/k8s/objectmeta.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/internal/validation/k8s/validation.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/internal/validation/validate.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/annotations.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits_unix.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/registry.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/version.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/parser/parser.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/config.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/oci.go
  vendor/github.com/moby/sys/user/LICENSE
  vendor/github.com/moby/sys/user/lookup_unix.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/user_fuzzer.go
  vendor/github.com/opencontainers/runc/NOTICE
  vendor/github.com/opencontainers/runc/libcontainer/devices/device.go
  vendor/github.com/opencontainers/runc/libcontainer/devices/device_unix.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: size/XXL

#9476 add label flags to ctr import
  client/import.go
  cmd/ctr/commands/images/import.go
  integration/client/import_test.go
Labels: kind/feature, needs-ok-to-test, size/M

#9602 [release/1.7 backport] switch back from golang.org/x/sys/execabs to os/exec (go1.19)
  archive/compression/compression.go
  archive/compression/compression_test.go
  archive/tar_test.go
  cmd/containerd-shim/main_unix.go
  cmd/containerd/command/service_windows.go
  cmd/ctr/commands/content/content.go
  contrib/apparmor/template.go
  contrib/nvidia/nvidia.go
  diff/stream_unix.go
  diff/stream_windows.go
  integration/client/client_test.go
  integration/client/container_fuzzer.go
  integration/client/container_linux_test.go
  integration/client/container_test.go
  integration/client/daemon.go
  integration/client/restart_monitor_test.go
  integration/image_load_test.go
  integration/issue7496_linux_test.go
  integration/main_test.go
  integration/pod_userns_linux_test.go
  integration/volume_copy_up_unix_test.go
  mount/lookup_linux_test.go
  mount/mount_freebsd.go
  mount/mount_linux.go
  mount/mount_linux_test.go
  pkg/process/io.go
  pkg/process/io_util.go
  runtime/v1/shim/client/client.go
  runtime/v1/shim/client/client_linux.go
  runtime/v1/shim/client/client_unix.go
  runtime/v2/runc/manager/manager_linux.go
  runtime/v2/runc/v1/service.go
  runtime/v2/shim/util.go
  snapshots/btrfs/btrfs_test.go
  snapshots/devmapper/blkdiscard/blkdiscard.go
  snapshots/devmapper/dmsetup/dmsetup.go
  snapshots/devmapper/pool_device_test.go
  snapshots/devmapper/snapshotter.go
  snapshots/overlay/overlayutils/check_test.go
  sys/oom_linux_test.go
  sys/reaper/reaper_unix.go
Labels: size/M

#9548 [release/1.7] shim: Create pid-file and address with 0644 permissions
  runtime/v2/shim/util.go
Labels: ok-to-test, size/XS

#9613 [release/1.6 backport] shim: Create pid-file with 0644 permissions
  runtime/v2/shim/util.go
Labels: size/XS

#9607 content: Add InfoReaderProvider
  content/content.go
  images/archive/exporter.go
  images/usage/calculator.go
  pkg/cri/store/image/image.go
  pkg/display/manifest_printer.go
Labels: ok-to-test, size/M

#9463 sandbox: remove sandboxStore from podsandbox controller
  integration/main_test.go
  integration/sandbox_run_rollback_test.go
  pkg/cri/server/base/sandbox_info.go
  pkg/cri/server/events.go
  pkg/cri/server/podsandbox/controller.go
  pkg/cri/server/podsandbox/controller_test.go
  pkg/cri/server/podsandbox/helpers.go
  pkg/cri/server/podsandbox/recover.go
  pkg/cri/server/podsandbox/sandbox_delete.go
  pkg/cri/server/podsandbox/sandbox_run.go
  pkg/cri/server/podsandbox/sandbox_status.go
  pkg/cri/server/podsandbox/sandbox_stop.go
  pkg/cri/server/podsandbox/store.go
  pkg/cri/server/podsandbox/types/podsandbox.go
  pkg/cri/server/restart.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_status.go
  pkg/cri/server/sandbox_stop.go
  pkg/cri/server/service.go
Labels: ok-to-test, size/XL

#9611 Handle failure when stopping a sandbox
  plugins/sandbox/controller.go
Labels: ok-to-test, size/XS

#9625 [release/1.6] update to go1.20.13, test go1.21.6
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#9619 build(deps): bump github.com/containerd/imgcrypt to v1.1.9
  script/setup/imgcrypt-version
  script/setup/install-imgcrypt
Labels: needs-ok-to-test, size/XS

#9626 Move certain debug level logs to trace level logs
  cmd/ctr/commands/content/content.go
  gc/scheduler/scheduler.go
  metadata/db.go
  pkg/cri/instrument/instrumented_service.go
  pkg/cri/io/logger.go
  pkg/cri/server/container_execsync.go
Labels: size/M

#9624 [release/1.7] update to go1.20.13, test go1.21.6
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#9630 transfer: add OCI descriptors to Progress structure
  api/next.pb.txt
  api/types/transfer/progress.pb.go
  api/types/transfer/progress.proto
  cmd/ctr/commands/images/pull.go
  pkg/transfer/local/import.go
  pkg/transfer/local/progress.go
  pkg/transfer/local/push.go
  pkg/transfer/proxy/transfer.go
  pkg/transfer/transfer.go
  services/transfer/service.go
Labels: size/L

#9631 [release/1.6] Prepare release notes for v1.6.27
  releases/v1.6.27.toml
  version/version.go
Labels: size/M

#8355 Move DefaultSnapshotter constants
  client/client.go
  cmd/ctr/commands/images/mount.go
  cmd/ctr/commands/images/usage.go
  defaults/defaults_snapshotter_linux.go
  defaults/defaults_snapshotter_unix.go
  defaults/defaults_snapshotter_windows.go
  integration/client/client.go
  integration/client/client_test.go
  integration/client/image_test.go
  integration/client/snapshot_test.go
  integration/image_pull_timeout_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/transfer/local/pull.go
  pkg/transfer/local/pull_test.go
  plugins/transfer/plugin.go
Labels: needs-ok-to-test, size/M

#9636 [release/1.6] carry #9557 - enable ARM CI
  .github/workflows/ci.yml
  integration/container_update_resources_test.go
  script/setup/install-cni
  script/setup/install-critools
Labels: size/M

#9640 mount: UnmountRecursive return nil if path doesn't exist
  mount/mount_unix.go
Labels: size/XS

#9646 runtime/v2: reduce shim plugin log
  runtime/v2/shim/shim.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9645 ci: make artifact name unique in linux integration
  .github/workflows/ci.yml
Labels: size/XS

#9621 config: enable CDI by default
  docs/cri/config.md
  pkg/cri/config/config_unix.go
Labels: ok-to-test, size/S

#9649 include image name in error message
  client/image.go
Labels: size/XS

#9432 ctr: use transfer service by default
  cmd/ctr/commands/images/export.go
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/images/tag.go
Labels: size/S

#9655 CI: use standard GHA runners
  .github/workflows/ci.yml
Labels: kind/test, size/XS

#9654 Prepare release notes for v2.0.0-beta.1
  releases/v2.0.0-beta.toml
  version/version.go
Labels: size/XS

#9555 Remove overlayfs volatile option on temp mounts
  core/mount/mount_test.go
  core/mount/temp.go
Labels: impact/changelog, ok-to-test, size/L

#9634 Add migration tests
  cmd/containerd/command/config.go
  cmd/containerd/server/config/config.go
  cmd/containerd/server/config/config_test.go
  integration/client/migration_test.go
  integration/client/testdata/default-1.6.toml
  integration/client/testdata/default-1.7.toml
  pkg/cri/server/base/cri_base.go
  plugins/transfer/plugin.go
Labels: size/XL

#9658 [release/1.7] content: Add InfoReaderProvider
  content/content.go
  images/archive/exporter.go
Labels: needs-ok-to-test, size/S

#9677 Update container-device-interface to v0.6.2
  cmd/ctr/commands/run/run_unix.go
  go.mod
  go.sum
  pkg/cri/config/config.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/service_linux.go
  pkg/oci/spec_opts.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/oci.go
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/LICENSE
  vendor/tags.cncf.io/container-device-interface/internal/multierror/multierror.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/validation.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/validate.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/annotations.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache_test_unix.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache_test_windows.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits_unix.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits_windows.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/device.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/doc.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/qualified-device.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/registry.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec-dirs.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec_linux.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec_other.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/version.go
  vendor/tags.cncf.io/container-device-interface/pkg/parser/parser.go
  vendor/tags.cncf.io/container-device-interface/specs-go/LICENSE
  vendor/tags.cncf.io/container-device-interface/specs-go/config.go
  vendor/tags.cncf.io/container-device-interface/specs-go/oci.go
Labels: ok-to-test, cherry-pick/1.7.x, size/XL

#9673 pod: CreatedAt time will be 269 years ago if create cri network failed
  pkg/cri/server/sandbox_run.go
Labels: area/cri, needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9685 [release/1.7] Update container-device-interface to v0.6.2
  docs/cri/config.md
  go.mod
  go.sum
  integration/client/go.sum
  pkg/cri/config/config.go
  pkg/cri/opts/spec_linux.go
  pkg/cri/sbserver/container_create_linux_test.go
  pkg/cri/sbserver/service_linux.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/service_linux.go
  vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/oci.go
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/LICENSE
  vendor/tags.cncf.io/container-device-interface/internal/multierror/multierror.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/validation.go
  vendor/tags.cncf.io/container-device-interface/internal/validation/validate.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/annotations.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache_test_unix.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache_test_windows.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits_unix.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/container-edits_windows.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/device.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/doc.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/qualified-device.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/registry.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec-dirs.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec_linux.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec_other.go
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/version.go
  vendor/tags.cncf.io/container-device-interface/pkg/parser/parser.go
  vendor/tags.cncf.io/container-device-interface/specs-go/LICENSE
  vendor/tags.cncf.io/container-device-interface/specs-go/config.go
  vendor/tags.cncf.io/container-device-interface/specs-go/oci.go
Labels: ok-to-test, size/XL

#9686 Use tags.cncf.io CDI url in config.md
  docs/cri/config.md
Labels: kind/docs, area/cri, needs-ok-to-test, size/XS

#9683 Code clean for nri_api.
  pkg/cri/nri/nri_api_linux.go
Labels: needs-ok-to-test, size/S

#9682 mv contrib/seccomp/kernelversion pkg/kernelversion
  contrib/seccomp/seccomp_default.go
  core/mount/losetup_linux.go
  core/mount/mount_idmapped_linux_test.go
  pkg/cri/config/config_kernel_linux.go
  pkg/cri/config/config_kernel_linux_test.go
  pkg/kernelversion/kernel_linux.go
  pkg/kernelversion/kernel_linux_test.go
  plugins/snapshots/overlay/overlayutils/check.go
Labels: kind/refactor, size/S

#9680 Remove walker diff plugin for Windows
  cmd/containerd/builtins/builtins.go
  cmd/containerd/builtins/builtins_freebsd.go
  cmd/containerd/builtins/builtins_linux.go
  cmd/containerd/builtins/builtins_unix.go
Labels: size/XS

#9665 integration: add test for recovering images
  integration/release_upgrade_linux_test.go
Labels: easy-to-review, size/M

#8890 remotes: FetchByDigest: propagate media type from config to desc
  cmd/ctr/commands/content/content.go
  core/remotes/docker/fetcher.go
Labels: size/XS

#9442 api/services/instrospection: add PluginInfo
  api/next.pb.txt
  api/services/introspection/v1/introspection.pb.go
  api/services/introspection/v1/introspection.proto
  api/services/introspection/v1/introspection_grpc.pb.go
  api/types/introspection.pb.go
  api/types/introspection.proto
  client/client.go
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
  cmd/ctr/commands/commands.go
  cmd/ctr/commands/commands_unix.go
  cmd/ctr/commands/commands_windows.go
  cmd/ctr/commands/containers/containers.go
  cmd/ctr/commands/plugins/plugins.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
  core/runtime/typeurl.go
  core/runtime/v2/README.md
  core/runtime/v2/example/example.go
  core/runtime/v2/manager.go
  core/runtime/v2/shim/shim.go
  integration/client/client_test.go
  plugins/services/introspection/introspection.go
  plugins/services/introspection/local.go
  plugins/services/introspection/service.go
Labels: impact/changelog, kind/feature, size/XXL

#9684 seccomp: kernel 6.7
  contrib/seccomp/seccomp_default.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9687 refactor: move plugin/fieldpath to api/types/
  api/events/container.pb.go
  api/events/container.proto
  api/events/content.pb.go
  api/events/content.proto
  api/events/image.pb.go
  api/events/image.proto
  api/events/namespace.pb.go
  api/events/namespace.proto
  api/events/snapshot.pb.go
  api/events/snapshot.proto
  api/events/task.pb.go
  api/events/task.proto
  api/next.pb.txt
  api/services/events/v1/events.pb.go
  api/services/events/v1/events.proto
  api/services/ttrpc/events/v1/events.pb.go
  api/services/ttrpc/events/v1/events.proto
  api/types/fieldpath.pb.go
  api/types/fieldpath.proto
  protobuf/plugin/doc.go
  protobuf/plugin/fieldpath.pb.go
Labels: size/XL

#9697 refactor: remove containerd/containerd/log
  log/context_deprecated.go
Labels: size/S

#9692 doc: fix package import in sample code
  README.md
  core/runtime/v2/README.md
  docs/PLUGINS.md
  docs/client-opts.md
  docs/getting-started.md
  docs/remote-snapshotter.md
Labels: size/M

#9661 Add support for multiple subscribers to CRI container events
  integration/container_event_test.go
  integration/main_test.go
  internal/eventq/eventq.go
  internal/eventq/eventq_test.go
  pkg/cri/server/container_events.go
  pkg/cri/server/helpers.go
  pkg/cri/server/service.go
Labels: size/L

#9700 Fix func (m manager) Info in containerd-shim-runc-v2.
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
Labels: kind/bug, needs-ok-to-test, kind/cleanup, size/XS

#9675 Clean plugin indent in containerd-config.toml.5.md
  docs/man/containerd-config.toml.5.md
Labels: kind/docs, needs-ok-to-test, easy-to-review, kind/cleanup, size/XS

#9702 Disable Links workflow in forks
  .github/workflows/links.yml
Labels: needs-ok-to-test, size/XS

#9681 Add CRI Service plugin type
  cmd/containerd/builtins/cri.go
  contrib/fuzz/builtins.go
  contrib/fuzz/cri_server_fuzzer.go
  integration/build_local_containerd_helper_test.go
  integration/main_test.go
  integration/sandbox_run_rollback_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_kernel_linux.go
  pkg/cri/config/config_kernel_linux_test.go
  pkg/cri/config/config_kernel_other.go
  pkg/cri/config/config_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/cri/config/streaming.go
  pkg/cri/config/streaming_test.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_create_linux_test.go
  pkg/cri/server/container_create_test.go
  pkg/cri/server/container_update_resources_linux_test.go
  pkg/cri/server/podsandbox/controller.go
  pkg/cri/server/podsandbox/controller_test.go
  pkg/cri/server/podsandbox/helpers.go
  pkg/cri/server/podsandbox/sandbox_status.go
  pkg/cri/server/runtime_config_linux_test.go
  pkg/cri/server/sandbox_status.go
  pkg/cri/server/service.go
  pkg/cri/server/service_test.go
  pkg/cri/server/streaming.go
  pkg/cri/server/streaming_test.go
  pkg/cri/server/test_config.go
  pkg/cri/types/sandbox_info.go
  plugins/cri/cri.go
  plugins/cri/images/plugin.go
  plugins/cri/runtime/load_test.go
  plugins/cri/runtime/plugin.go
  plugins/types.go
Labels: size/XXL

#8735 remotes/docker/authorizer.go: refresh OAuth tokens when they expire
  core/remotes/docker/auth/fetch.go
  core/remotes/docker/authorizer.go
Labels: needs-ok-to-test, size/M

#9696 Prepare release notes for v2.0.0-beta.2
  .mailmap
  releases/v2.0.0-beta.toml
  version/version.go
Labels: size/XS

#9714 rm docs/cri/installation.md
  docs/cri/installation.md
Labels: kind/docs, area/cri, easy-to-review, size/L

#9723 Prepare v1.6.28 and update runc to v1.1.12
  releases/v1.6.28.toml
  script/setup/runc-version
  version/version.go
Labels: size/M

#9724 Prepare v1.7.13 and update runc to v1.1.12
  releases/v1.7.13.toml
  script/setup/runc-version
  version/version.go
Labels: size/M

#9721 docs: fix typo
  docs/hosts.md
Labels: kind/docs, ok-to-test, size/XS

#9722 Update runc binary to v1.1.12
  script/setup/runc-version
Labels: size/XS

#9715 CI: bump up crun to 1.14
  script/setup/crun-version
Labels: kind/test, easy-to-review, size/XS

#9716 CI: update Rocky Linux to 8.9
  .github/workflows/ci.yml
Labels: kind/test, size/XS
