Repository containerd/containerd, pull requests merged in 2024-03, with the labels that each got.

#9900 [release/1.7] Update golangci-lint to v1.56.1
  .github/workflows/ci.yml
  .golangci.yml
  content/helpers_test.go
  integration/remote/util/util_windows.go
  metadata/containers_test.go
  metadata/images_test.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/server/image_pull.go
  remotes/docker/config/hosts.go
  script/setup/install-dev-tools
  tracing/plugin/otlp.go
  tracing/plugin/otlp_test.go
Labels: size/M

#9855 [release/1.7] Register imagePullThroughput and count with MiB
  pkg/cri/sbserver/image_pull.go
  pkg/cri/sbserver/metrics.go
  pkg/cri/server/image_pull.go
  pkg/cri/server/metrics.go
Labels: kind/bug, needs-ok-to-test, size/M

#9828 runc-shim: process exec exits before init (w/o extra locks!)
  cmd/containerd-shim-runc-v2/task/service.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/L

#9921 [release/1.7] Backport fix various timing issues with docker pusher
  content/helpers.go
  content/helpers_test.go
  remotes/docker/pusher.go
Labels: needs-ok-to-test, size/L

#9910 Add ttrpc to proxy interfaces
  client/client.go
  cmd/containerd/server/server.go
  core/content/proxy/content_reader.go
  core/content/proxy/content_store.go
  core/content/proxy/content_writer.go
  core/events/proxy/remote_events.go
Labels: size/L

#9860 [release/1.7] update to go 1.21.6, test 1.22.0
  .github/actions/install-go/action.yml
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  BUILDING.md
  Vagrantfile
  contrib/Dockerfile.test
  contrib/apparmor/apparmor.go
  contrib/fuzz/oss_fuzz_build.sh
  contrib/seccomp/seccomp.go
  go.mod
  go.sum
  integration/client/go.mod
  script/setup/prepare_env_windows.ps1
Labels: size/L

#9892 Move nri packages to plugin and internal
  cmd/containerd/builtins/builtins.go
  contrib/fuzz/builtins.go
  contrib/v2-migrate.sh
  internal/cri/nri/nri_api_linux.go
  internal/cri/nri/nri_api_other.go
  internal/nri/config.go
  internal/nri/container.go
  internal/nri/container_linux.go
  internal/nri/container_other.go
  internal/nri/domain.go
  internal/nri/nri.go
  internal/nri/sandbox.go
  internal/nri/sandbox_linux.go
  internal/nri/sandbox_other.go
  plugins/cri/cri.go
  plugins/nri/plugin.go
Labels: size/S

#9925 Update hcsshim to v0.12.0
  go.mod
  go.sum
  script/setup/runhcs-version
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/stats.pb.go
  vendor/github.com/Microsoft/hcsshim/internal/wclayer/cim/process.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/utils.go
  vendor/modules.txt
Labels: size/M

#9928 [release/1.7] runc-shim: process exec exits before init
  runtime/v2/runc/task/service.go
Labels: size/L

#9927 [release/1.6] runc-shim: process exec exits before init
  runtime/v2/runc/task/service.go
Labels: size/L

#9939 Disable OOM set score unpriv test temporarily
  pkg/sys/oom_linux_test.go
Labels: size/XS

#9659 Don't create new scratch VHD per image for CimFS
  plugins/snapshots/windows/cimfs.go
  plugins/snapshots/windows/common.go
  plugins/snapshots/windows/windows.go
Labels: ok-to-test, size/XL

#9932 update to go 1.21.8, 1.22.1
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x, size/S

#9944 [release/1.7] Disable OOM set score unpriv test temporarily
  sys/oom_linux_test.go
Labels: size/XS

#9943 [release/1.6] Disable OOM set score unpriv test temporarily
  sys/oom_linux_test.go
Labels: size/XS

#9938 [release/1.7] Move inline PS scripts into files
  .github/workflows/ci.yml
  script/setup/upgrade_chocolaty_windows_2019.ps1
  script/setup/upgrade_mingw_windows_2019.ps1
Labels: size/M

#6965 Wire through CRI checkpoint RPC
  go.mod
  go.sum
  internal/cri/instrument/instrumented_service.go
  internal/cri/server/container_checkpoint.go
  internal/cri/server/container_checkpoint_linux.go
  internal/cri/server/metrics.go
  vendor/github.com/checkpoint-restore/checkpointctl/LICENSE
  vendor/github.com/checkpoint-restore/checkpointctl/lib/metadata.go
  vendor/github.com/checkpoint-restore/go-criu/v7/.gitignore
  vendor/github.com/checkpoint-restore/go-criu/v7/.golangci.yml
  vendor/github.com/checkpoint-restore/go-criu/v7/LICENSE
  vendor/github.com/checkpoint-restore/go-criu/v7/MAINTAINERS
  vendor/github.com/checkpoint-restore/go-criu/v7/Makefile
  vendor/github.com/checkpoint-restore/go-criu/v7/README.md
  vendor/github.com/checkpoint-restore/go-criu/v7/features.go
  vendor/github.com/checkpoint-restore/go-criu/v7/main.go
  vendor/github.com/checkpoint-restore/go-criu/v7/notify.go
  vendor/github.com/checkpoint-restore/go-criu/v7/rpc/rpc.pb.go
  vendor/github.com/checkpoint-restore/go-criu/v7/rpc/rpc.proto
  vendor/modules.txt
Labels: area/cri, ok-to-test, size/XXL

#9933 [release/1.7] update to go 1.21.8, 1.22.1
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: impact/changelog, size/S

#9945 [release/1.6] update to go 1.21.8, 1.22.1
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S

#9946 Use the Go toolchain in CI matrix to build binaries
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/XS

#9926 Move core/runtime/v2/shim to pkg/shim
  cmd/containerd-shim-runc-v2/main.go
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
  cmd/containerd-shim-runc-v2/task/plugin/plugin_linux.go
  cmd/containerd-shim-runc-v2/task/service.go
  cmd/ctr/commands/shim/shim.go
  core/runtime/v2/binary.go
  core/runtime/v2/example/cmd/main.go
  core/runtime/v2/example/example.go
  core/runtime/v2/manager.go
  core/runtime/v2/shim.go
  core/runtime/v2/shim_test.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/main_linux.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
  integration/issue7496_linux_test.go
  integration/shim_dial_unix_test.go
  pkg/oom/v1/v1.go
  pkg/oom/v2/v2.go
  pkg/shim/publisher.go
  pkg/shim/shim.go
  pkg/shim/shim_darwin.go
  pkg/shim/shim_freebsd.go
  pkg/shim/shim_linux.go
  pkg/shim/shim_test.go
  pkg/shim/shim_unix.go
  pkg/shim/shim_windows.go
  pkg/shim/util.go
  pkg/shim/util_test.go
  pkg/shim/util_unix.go
  pkg/shim/util_windows.go
Labels: size/M

#9949 [release/1.6] use a composite action to install Go
  .github/workflows/ci.yml
Labels: size/M

#9951 [release/1.7] Backport use Go toolchain in CI matrix to build binaries
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/XS

#9950 [release/1.6] Prepare release notes for v1.6.29
  releases/v1.6.29.toml
  version/version.go
Labels: size/S

#9930 Clean typos in plugins.
  plugins/types.go
Labels: needs-ok-to-test, kind/cleanup, size/XS

#9879 add k8s 1.29 and 1.30preview to support table
  README.md
  RELEASES.md
Labels: size/S

#9952 [release/1.6] Prepare v1.6.30
  .github/workflows/release.yml
  releases/v1.6.30.toml
  version/version.go
Labels: size/M

#9917 mv internal/testutil pkg/testutil
  core/content/testsuite/testsuite.go
  core/metadata/snapshot_test.go
  core/runtime/v2/bundle_linux_test.go
  core/runtime/v2/bundle_test.go
  core/snapshots/storage/bolt_test.go
  core/snapshots/testsuite/testsuite.go
  integration/client/client_test.go
  integration/client/restart_monitor_test.go
  pkg/archive/issues_test.go
  pkg/archive/tar_linux_test.go
  pkg/archive/tar_test.go
  pkg/oci/spec_opts_linux_test.go
  pkg/oci/spec_test.go
  pkg/testutil/helpers.go
  pkg/testutil/helpers_unix.go
  pkg/testutil/helpers_windows.go
  plugins/content/local/store_test.go
  plugins/snapshots/blockfile/blockfile_test.go
  plugins/snapshots/btrfs/btrfs_test.go
  plugins/snapshots/devmapper/dmsetup/dmsetup_test.go
  plugins/snapshots/devmapper/pool_device_test.go
  plugins/snapshots/devmapper/snapshotter_test.go
  plugins/snapshots/native/native_test.go
  plugins/snapshots/overlay/overlay_test.go
  plugins/snapshots/overlay/overlayutils/check_test.go
  plugins/snapshots/windows/windows_test.go
Labels: kind/test, kind/refactor, size/M

#9967 vendor: github.com/golang/protobuf v1.5.4
  go.mod
  go.sum
  vendor/modules.txt
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/S

#9735 Prepare release notes for v2.0.0-rc.0
  .mailmap
  contrib/v2-migrate.sh
  releases/v2.0.0-rc.toml
  version/version.go
Labels: size/S

#9955 [release/1.6] Backport test release on PR
  .github/workflows/release.yml
Labels: needs-ok-to-test, size/S

#9961 Clean cri options and useless parms
  internal/cri/opts/spec_linux_opts.go
  internal/cri/server/container_create.go
Labels: needs-ok-to-test, kind/cleanup, size/S

#9864 Automatically decompress archives for transfer service import
  core/transfer/archive/importer.go
Labels: needs-ok-to-test, size/S

#9983 transfer: Platform matcher should match multiple platforms
  plugins/transfer/plugin.go
Labels: size/XS

#9976 pkg/systemd, pkg/seutil: move to internal/cri
  internal/cri/server/helpers_linux.go
  internal/cri/server/podsandbox/helpers_linux.go
  internal/cri/server/runtime_config_linux.go
  internal/cri/server/runtime_config_linux_test.go
  internal/cri/seutil/seutil.go
  internal/cri/systemd/util.go
Labels: size/S

#9885 cri: ensure the pause image loaded in older versions is pinned
  internal/cri/server/images/image_pull.go
Labels: size/M

#9998 docs: fix typo
  docs/cri/registry.md
Labels: needs-ok-to-test, size/XS

#9991 [release/1.6] adds mediatype to oci index record
  images/archive/exporter.go
Labels: ok-to-test, size/XS

#9990 [release/1.7] adds mediatype to oci index record
  images/archive/exporter.go
Labels: needs-ok-to-test, size/XS

#9679 Change port forwarding on windows
  internal/cri/server/sandbox_portforward_windows.go
Labels: size/L

#10004 ctr: fix parsing mount options
  cmd/ctr/app/main.go
Labels: ok-to-test, size/XS

#10012 [release/1.7] Fix compile from version control system (source) use case
  go.mod
  go.sum
Labels: needs-ok-to-test, size/XS
