Repository containerd/containerd, pull requests merged in 2024-02, with the labels that each got.

#9713 cri: make read-only mounts recursively read-only
  RELEASES.md
  docs/cri/config.md
  integration/container_volume_linux_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_kernel_linux.go
  pkg/cri/config/config_kernel_other.go
  pkg/cri/config/config_test.go
  pkg/cri/opts/spec_linux_opts.go
  pkg/cri/server/container_create.go
  pkg/cri/server/container_create_linux_test.go
  plugins/cri/runtime/plugin.go
Labels: impact/changelog, area/cri, impact/breaking, size/L

#9718 Add a default differ for Windows that matches the snapshotter when using transfer service
  defaults/defaults_differ_windows.go
  plugins/transfer/plugin.go
  plugins/transfer/plugin_defaults_other.go
  plugins/transfer/plugin_defaults_windows.go
Labels: size/M

#9742 Move Message proto to types
  api/Protobuild.toml
  api/next.pb.txt
  api/services/events/v1/events.pb.go
  api/services/events/v1/events.proto
  api/services/events/v1/events_grpc.pb.go
  api/services/ttrpc/events/v1/events.pb.go
  api/services/ttrpc/events/v1/events.proto
  api/services/ttrpc/events/v1/events_fieldpath.pb.go
  api/types/event.pb.go
  api/types/event.proto
  client/events.go
  core/runtime/v2/shim/publisher.go
  integration/client/client_ttrpc_test.go
  plugins/services/events/service.go
  plugins/services/events/ttrpc.go
Labels: size/XL

#9729 Remove duplicated TOML duration parsers
  plugins/gc/scheduler.go
  plugins/gc/scheduler_test.go
  plugins/restart/monitor.go
Labels: easy-to-review, size/M

#9644 sandbox: fix podsandbox recover status issue
  integration/restart_linux_test.go
  internal/cri/server/podsandbox/recover.go
  internal/cri/server/podsandbox/recover_test.go
Labels: ok-to-test, size/XL

#9754 Update TTRPC
  go.mod
  go.sum
  vendor/github.com/containerd/ttrpc/client.go
  vendor/github.com/containerd/ttrpc/config.go
  vendor/github.com/containerd/ttrpc/services.go
  vendor/modules.txt
Labels: size/L

#9761 [release/1.7] Move certain debug logs to trace logs
  cmd/ctr/commands/content/content.go
  gc/scheduler/scheduler.go
  metadata/db.go
  pkg/cri/instrument/instrumented_service.go
  pkg/cri/io/logger.go
  pkg/cri/server/container_execsync.go
Labels: size/M

#9762 [release/1.6] Move certain debug logs to trace logs
  cmd/ctr/commands/content/content.go
  gc/scheduler/scheduler.go
  metadata/db.go
  pkg/cri/io/logger.go
  pkg/cri/server/instrumented_service.go
Labels: size/M

#9763 Treat PRs that require rebase > 90 days as stale
  .github/workflows/stale.yml
Labels: size/XS

#9753 Update hcsshim to v0.12.0-rc.3
  go.mod
  go.sum
  script/setup/runhcs-version
  vendor/github.com/Microsoft/hcsshim/Makefile
  vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go
  vendor/github.com/Microsoft/hcsshim/internal/oc/errors.go
  vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/import.go
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/errdefs/grpc.go
  vendor/modules.txt
Labels: size/XL

#9750 Support inject delay running with the old version (4.x) of strace for test case
  integration/issue7496_linux_test.go
Labels: needs-ok-to-test, easy-to-review, cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9764 Clean up repeated package import
  cmd/ctr/commands/run/run_unix.go
Labels: needs-ok-to-test, size/XS

#9744 Flip NRI on by default.
  docs/NRI.md
  integration/client/testdata/default-1.7.toml
  pkg/nri/config.go
Labels: impact/changelog, size/S

#9777 [CI] Move inline PS scripts into files
  .github/workflows/ci.yml
  script/setup/upgrade_chocolaty_windows_2019.ps1
  script/setup/upgrade_mingw_windows_2019.ps1
Labels: easy-to-review, size/M

#9743 go.{mod,sum}: update NRI dependency, fixing a potential fd double close error.
  go.mod
  go.sum
  vendor/github.com/containerd/nri/client.go
  vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
  vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
  vendor/github.com/containerd/nri/pkg/net/socketpair.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_linux.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_cloexec_windows.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
  vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
  vendor/github.com/containerd/nri/pkg/stub/stub.go
  vendor/modules.txt
Labels: size/XL

#9769 [release/1.7] Add option to perform syncfs after pull
  api/next.pb.txt
  api/services/diff/v1/diff.pb.go
  api/services/diff/v1/diff.proto
  contrib/diffservice/service.go
  diff/apply/apply.go
  diff/apply/apply_darwin.go
  diff/apply/apply_linux.go
  diff/apply/apply_other.go
  diff/diff.go
  diff/proxy/differ.go
  image.go
  pkg/cri/config/config.go
  pkg/cri/config/config_unix.go
  pkg/cri/server/image_pull.go
  services/diff/local.go
Labels: size/L

#9779 Move image event publishing to metadata store
  core/metadata/db.go
  core/metadata/images.go
  core/metadata/snapshot.go
  internal/cri/server/images/image_pull.go
  internal/cri/server/images/image_remove.go
  internal/cri/server/images/service.go
  plugins/cri/images/plugin.go
  plugins/services/images/local.go
Labels: size/L

#9732 bug fix: make sure cri image is pinned when it is pulled outside cri
  integration/containerd_image_test.go
  internal/cri/server/images/image_pull.go
Labels: area/cri, size/M

#9733 Add OSVersion to platform protobuf
  Makefile
  api/next.pb.txt
  api/types/platform.pb.go
  api/types/platform.proto
  api/types/platform_helpers.go
Labels: size/M

#9747 Revert "cri: make read-only mounts recursively read-only"
  RELEASES.md
  docs/cri/config.md
  integration/container_volume_linux_test.go
  internal/cri/config/config.go
  internal/cri/config/config_kernel_linux.go
  internal/cri/config/config_kernel_other.go
  internal/cri/config/config_test.go
  internal/cri/opts/spec_linux_opts.go
  internal/cri/server/container_create.go
  internal/cri/server/container_create_linux_test.go
  plugins/cri/runtime/plugin.go
Labels: area/cri, size/L

#9786 Extract setup-go step into composite action
  .github/actions/install-go/action.yml
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
Labels: size/L

#9796 Fix CRI link in readme
  README.md
Labels: ok-to-test, size/XS

#9794 Build with Go 1.22.0
  .github/workflows/ci.yml
  BUILDING.md
  go.mod
  go.sum
Labels: size/M

#9797 Update codeql-action/upload-sarif dependency in scorecards workflow
  .github/workflows/scorecards.yml
Labels: needs-ok-to-test, size/XS

#9784 [release/1.7] bug fix: make sure cri image is pinned when it is pulled outside cri
  integration/containerd_image_test.go
  pkg/cri/sbserver/image_pull.go
  pkg/cri/server/image_pull.go
Labels: size/M

#9785 [release/1.6] bug fix: make sure cri image is pinned when it is pulled outside cri
  integration/containerd_image_test.go
  pkg/cri/server/image_pull.go
Labels: size/M

#9782 Include userns info in cri/server PodSandboxStatus
  internal/cri/server/sandbox_status.go
  internal/cri/server/sandbox_status_test.go
Labels: ok-to-test, size/S

#9790 Move transfer and unpack packages to core
  client/pull.go
  client/transfer.go
  cmd/ctr/commands/images/export.go
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/images/tag.go
  cmd/ctr/commands/resolver.go
  contrib/v2-migrate.sh
  core/streaming/streaming.go
  core/transfer/archive/exporter.go
  core/transfer/archive/importer.go
  core/transfer/image/imagestore.go
  core/transfer/image/imagestore_test.go
  core/transfer/local/export.go
  core/transfer/local/import.go
  core/transfer/local/progress.go
  core/transfer/local/pull.go
  core/transfer/local/pull_test.go
  core/transfer/local/push.go
  core/transfer/local/tag.go
  core/transfer/local/transfer.go
  core/transfer/plugins/plugins.go
  core/transfer/proxy/transfer.go
  core/transfer/registry/registry.go
  core/transfer/streaming/stream.go
  core/transfer/streaming/stream_test.go
  core/transfer/streaming/writer.go
  core/transfer/transfer.go
  core/unpack/unpacker.go
  integration/client/import_test.go
  integration/client/transfer_test.go
  plugins/services/streaming/service.go
  plugins/services/transfer/service.go
  plugins/streaming/manager.go
  plugins/transfer/plugin.go
Labels: size/L

#9799 Fix for k8s nfs related tests probably caused by `ulimit` changes
  contrib/gce/configure.sh
Labels: size/XS

#9803 Remove deprecated functions and packages
  client/signals.go
  core/runtime/restart/restart.go
  integration/client/signals_test.go
  pkg/dialer/dialer.go
  pkg/reference/docker/helpers_deprecated.go
  pkg/reference/docker/normalize_deprecated.go
  pkg/reference/docker/reference_deprecated.go
  pkg/reference/docker/regexp_deprecated.go
  pkg/reference/docker/sort_deprecated.go
  pkg/sys/filesys_deprecated_windows.go
Labels: size/XL

#9802 Fix unpacker link in remote snapshotter docs
  docs/remote-snapshotter.md
Labels: needs-ok-to-test, size/XS

#9804 Revert "Fix for k8s nfs related tests"
  contrib/gce/configure.sh
Labels: size/XS

#9805 go.mod: Bump golang.org/x/sys to v0.17.0
  core/mount/losetup_linux.go
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: needs-ok-to-test, size/L

#9778 Update gce configure.sh to use registry config_path
  contrib/gce/configure.sh
Labels: ok-to-test, size/S

#9813 Remove internal LoopConfig struct
  core/mount/losetup_linux.go
Labels: needs-ok-to-test, size/XS

#9814 moving up cri-tools to pull in new CRI changes tied to k8s v1.29
  script/setup/critools-version
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9767 cri: propagate deprecation list to runtime status
  internal/cri/config/config.go
  internal/cri/server/status.go
  internal/cri/server/status_test.go
Labels: area/cri, cherry-pick/1.6.x, cherry-pick/1.7.x, size/L

#9817 Move high volume event logs to Trace level
  pkg/events/exchange/exchange.go
Labels: size/XS

#9820 [release/1.7] ctr: print deprecation warnings on every invocation
  cmd/ctr/commands/client.go
  cmd/ctr/commands/deprecations/deprecations.go
Labels: size/S

#9821 [release/1.6] ctr: print deprecation warnings on every invocation
  cmd/ctr/commands/client.go
  cmd/ctr/commands/deprecations/deprecations.go
Labels: size/S

#9818 [release/1.7] cri: propagate deprecation list to runtime status
  pkg/cri/config/config.go
  pkg/cri/server/status.go
  pkg/cri/server/status_test.go
Labels: area/cri, size/L

#9819 [release/1.6] cri: propagate deprecation list to runtime status
  pkg/cri/config/config.go
  pkg/cri/server/status.go
  pkg/cri/server/status_test.go
Labels: area/cri, size/L

#9788 Add CRIImageService.RemoveImage()
  internal/cri/server/images/image_remove.go
Labels: size/S

#9815 Pass runtimehandler from CRI to pull image request
  integration/cri-api/pkg/apis/services.go
  integration/image_pull_timeout_test.go
  integration/main_test.go
  integration/release_upgrade_linux_test.go
  integration/remote/remote_image.go
  internal/cri/server/container_status_test.go
  internal/cri/server/images/image_pull.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/podsandbox/sandbox_run.go
  internal/cri/server/service.go
Labels: size/M

#9823 [release/1.7] Move high volume event logs to Trace level
  events/exchange/exchange.go
Labels: size/XS

#9827 Move config version to version package
  cmd/containerd/command/config.go
  cmd/containerd/server/config/config.go
  cmd/containerd/server/config/config_test.go
  cmd/containerd/server/server.go
  cmd/containerd/server/server_test.go
  contrib/fuzz/daemon.go
  plugins/cri/cri.go
  plugins/cri/images/plugin.go
  plugins/cri/runtime/plugin.go
  version/version.go
Labels: size/M

#9824 [release/1.6] Move high volume event logs to Trace level
  events/exchange/exchange.go
Labels: size/XS

#9746 Fix config import relative path glob
  cmd/containerd/server/config/config.go
  cmd/containerd/server/config/config_test.go
Labels: impact/changelog, ok-to-test, size/S

#9829 Run failpoints tests only for runc
  integration/client/container_linux_test.go
  integration/client/container_test.go
Labels: size/XS

#9831 Workaround "required job statuses" job list
  .github/workflows/ci.yml
Labels: size/S

#9768 [release/1.6] pkg/cri: add timeout to drain exec io
  docs/cri/config.md
  integration/container_exec_test.go
  pkg/cri/config/config.go
  pkg/cri/config/config_test.go
  pkg/cri/config/config_unix.go
  pkg/cri/config/config_windows.go
  pkg/cri/server/container_execsync.go
  pkg/cri/server/container_execsync_test.go
  script/test/utils.sh
Labels: area/cri, ok-to-test, size/L

#9748 test: update upgrade test suite in integration
  integration/cri-api/pkg/apis/services.go
  integration/issue7496_linux_test.go
  integration/issue7496_shutdown_linux_test.go
  integration/release_upgrade_linux_test.go
  integration/release_upgrade_utils_linux_test.go
  integration/remote/remote_runtime.go
Labels: ok-to-test, size/XL

#9765 Disable the support for Schema 1 images
  RELEASES.md
  client/pull.go
  core/remotes/docker/schema1/converter.go
  integration/client/client_test.go
  integration/client/client_unix_test.go
  integration/containerd_image_test.go
  pkg/deprecation/deprecation.go
Labels: impact/changelog, impact/breaking, size/M

#9635 cri: Stat host sandbox files before adding them
  internal/cri/server/container_create.go
  internal/cri/server/container_create_test.go
Labels: area/cri, size/L

#9847 replace deprecated Prestart to CreateRuntime hook
  contrib/nvidia/nvidia.go
  integration/client/container_test.go
Labels: size/XS

#9789 Add container monitor plugin type for restart
  core/metrics/cgroups/cgroups.go
  plugins/restart/monitor.go
  plugins/types.go
Labels: size/M

#8379 Fix various timing issues with docker pusher
  core/content/helpers.go
  core/content/helpers_test.go
  core/remotes/docker/pusher.go
Labels: needs-ok-to-test, cherry-pick/1.7.x, size/L

#9787 KEP-3857: Recursive Read-only (RRO) mounts
  go.mod
  go.sum
  internal/cri/opts/spec_linux_opts.go
  internal/cri/server/container_create.go
  internal/cri/server/container_create_linux_test.go
  internal/cri/server/container_create_test.go
  internal/cri/server/container_create_windows_test.go
  internal/cri/server/service.go
  internal/cri/server/service_linux.go
  internal/cri/server/status.go
  script/test/utils.sh
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/k8s.io/cri-api/pkg/errors/doc.go
  vendor/k8s.io/cri-api/pkg/errors/errors.go
  vendor/modules.txt
Labels: area/cri, size/XXL

#9848 ci: update crun version to 1.14.3
  script/setup/crun-version
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9845 Replace go-grpc-prometheus with go-grpc-middleware/providers/prometheus
  cmd/containerd/server/server.go
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/.gitignore
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/CONTRIBUTING.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/makefile
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/constants.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/slack.png
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.gitignore
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/.travis.yml
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/CHANGELOG.md
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/makefile
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/metric_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/modules.txt
Labels: size/XXL

#9833 Update 1.7 support timeline
  RELEASES.md
Labels: size/M

#9795 Prevent GC from schedule itself with 0 period.
  plugins/gc/scheduler.go
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS

#9837 [release/1.7] Add WithMetaStore to overlay snapshotter and missing unpacker.Wait for image import
  pkg/transfer/local/import.go
  snapshots/overlay/overlay.go
Labels: needs-ok-to-test, size/M

#9738 sandbox: support vsock connection to task api
  core/runtime/v2/shim/util_unix.go
  go.mod
  go.sum
  vendor/github.com/mdlayher/socket/CHANGELOG.md
  vendor/github.com/mdlayher/socket/LICENSE.md
  vendor/github.com/mdlayher/socket/README.md
  vendor/github.com/mdlayher/socket/accept.go
  vendor/github.com/mdlayher/socket/accept4.go
  vendor/github.com/mdlayher/socket/conn.go
  vendor/github.com/mdlayher/socket/conn_linux.go
  vendor/github.com/mdlayher/socket/doc.go
  vendor/github.com/mdlayher/socket/netns_linux.go
  vendor/github.com/mdlayher/socket/netns_others.go
  vendor/github.com/mdlayher/socket/setbuffer_linux.go
  vendor/github.com/mdlayher/socket/setbuffer_others.go
  vendor/github.com/mdlayher/socket/typ_cloexec_nonblock.go
  vendor/github.com/mdlayher/socket/typ_none.go
  vendor/github.com/mdlayher/vsock/.gitignore
  vendor/github.com/mdlayher/vsock/CHANGELOG.md
  vendor/github.com/mdlayher/vsock/LICENSE.md
  vendor/github.com/mdlayher/vsock/README.md
  vendor/github.com/mdlayher/vsock/conn_linux.go
  vendor/github.com/mdlayher/vsock/doc.go
  vendor/github.com/mdlayher/vsock/fd_linux.go
  vendor/github.com/mdlayher/vsock/listener_linux.go
  vendor/github.com/mdlayher/vsock/vsock.go
  vendor/github.com/mdlayher/vsock/vsock_others.go
  vendor/golang.org/x/net/bpf/asm.go
  vendor/golang.org/x/net/bpf/constants.go
  vendor/golang.org/x/net/bpf/doc.go
  vendor/golang.org/x/net/bpf/instructions.go
  vendor/golang.org/x/net/bpf/setter.go
  vendor/golang.org/x/net/bpf/vm.go
  vendor/golang.org/x/net/bpf/vm_instructions.go
  vendor/modules.txt
Labels: impact/changelog, needs-ok-to-test, size/XXL

#8970 Configure otel from env instead of config.toml
  RELEASES.md
  integration/client/testdata/default-1.6.toml
  integration/client/testdata/default-1.7.toml
  pkg/deprecation/deprecation.go
  pkg/tracing/plugin/otlp.go
  pkg/tracing/plugin/otlp_test.go
Labels: impact/changelog, cherry-pick/1.6.x, cherry-pick/1.7.x, size/L

#9836 Add support for userns (k8s >= 1.30)
  go.mod
  go.sum
  internal/cri/server/service.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go
  vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto
  vendor/modules.txt
Labels: needs-ok-to-test, size/XL

#9851 [release/1.6] ci: update crun version to 1.14.3
  script/setup/crun-version
  script/setup/install-runc
Labels: size/XS

#9850 [release/1.7] ci: update crun version to 1.14.3
  script/setup/crun-version
Labels: size/XS

#7609 Generate proto services with go-ttrpc
  api/Protobuild.toml
  api/services/containers/v1/containers_ttrpc.pb.go
  api/services/content/v1/content_ttrpc.pb.go
  api/services/diff/v1/diff_ttrpc.pb.go
  api/services/events/v1/events_ttrpc.pb.go
  api/services/images/v1/images_ttrpc.pb.go
  api/services/introspection/v1/introspection_ttrpc.pb.go
  api/services/leases/v1/leases_ttrpc.pb.go
  api/services/namespaces/v1/namespace_ttrpc.pb.go
  api/services/sandbox/v1/sandbox_ttrpc.pb.go
  api/services/snapshots/v1/snapshots_ttrpc.pb.go
  api/services/streaming/v1/streaming_ttrpc.pb.go
  api/services/tasks/v1/tasks_ttrpc.pb.go
  api/services/transfer/v1/transfer_ttrpc.pb.go
  api/services/version/v1/version_ttrpc.pb.go
  script/setup/install-dev-tools
Labels: size/XXL

#9800 Update golangci-lint version to v1.56.1 and resolve warnings
  .github/workflows/ci.yml
  client/snapshotter_opts_unix.go
  plugins/snapshots/overlay/overlay.go
  plugins/snapshots/overlay/overlay_test.go
  plugins/snapshots/overlay/plugin/plugin.go
Labels: impact/changelog, size/M

#9861 Remove pause package from runc shim
  cmd/containerd-shim-runc-v2/main.go
  cmd/containerd-shim-runc-v2/pause/sandbox.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/main_linux.go
Labels: size/L

#9871 .github: windows should use fix critool version
  .github/workflows/ci.yml
Labels: ok-to-test, cherry-pick/1.7.x, size/XS

#9869 plugins/sandbox: move local plugin into services
  plugins/sandbox/controller.go
  plugins/services/sandbox/store_local.go
Labels: ok-to-test, easy-to-review, size/XS

#9877 [release/1.6] Backport GitHub actions package updates
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test, size/L

#9878 refactor: clean switch statements and convert if to switch
  core/snapshots/snapshotter.go
Labels: needs-ok-to-test, size/S

#9876 [release/1.7] Backport GitHub actions package updates
  .github/workflows/build-test-images.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzz.yml
  .github/workflows/images.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scorecards.yml
  .github/workflows/windows-hyperv-periodic.yml
  .github/workflows/windows-periodic.yml
Labels: needs-ok-to-test, size/L

#9888 vendor: go.etcd.io/bbolt v1.3.9
  go.mod
  go.sum
  vendor/go.etcd.io/bbolt/bucket.go
  vendor/modules.txt
Labels: size/M

#9859 mediatypes: support zstd compression
  core/images/mediatypes.go
Labels: size/XS

#9617 sandbox: use sandboxService in CRI plugin instead of calling controller API directly
  integration/build_local_containerd_helper_test.go
  internal/cri/config/config.go
  internal/cri/server/container_create.go
  internal/cri/server/container_stats_list.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/podsandbox/controller_test.go
  internal/cri/server/podsandbox/recover.go
  internal/cri/server/podsandbox/recover_test.go
  internal/cri/server/podsandbox/sandbox_run.go
  internal/cri/server/podsandbox/sandbox_status.go
  internal/cri/server/podsandbox/sandbox_stop.go
  internal/cri/server/podsandbox/types/podsandbox.go
  internal/cri/server/podsandbox/types/podsandbox_test.go
  internal/cri/server/restart.go
  internal/cri/server/sandbox_remove.go
  internal/cri/server/sandbox_run.go
  internal/cri/server/sandbox_service.go
  internal/cri/server/sandbox_status.go
  internal/cri/server/sandbox_stop.go
  internal/cri/server/service.go
  internal/cri/server/service_test.go
  internal/cri/store/sandbox/sandbox.go
  plugins/cri/cri.go
Labels: area/cri, ok-to-test, size/L

#9893 Add Go client stability in RELEASES.md for 2.0
  RELEASES.md
Labels: kind/docs, size/XS

#9891 Move events to plugins and core
  client/client.go
  client/events.go
  cmd/containerd/builtins/builtins.go
  cmd/ctr/commands/events/events.go
  contrib/fuzz/builtins.go
  contrib/fuzz/exchange_fuzzer.go
  contrib/v2-migrate.sh
  core/events/events.go
  core/events/exchange/exchange.go
  core/events/exchange/exchange_test.go
  core/metadata/db.go
  core/metrics/cgroups/cgroups.go
  core/metrics/cgroups/v1/cgroups.go
  core/metrics/cgroups/v2/cgroups.go
  core/runtime/v2/manager.go
  core/runtime/v2/shim.go
  core/runtime/v2/shim/publisher.go
  core/runtime/v2/shim/shim.go
  integration/build_local_containerd_helper_test.go
  internal/cri/server/events.go
  plugins/events/plugin.go
  plugins/metadata/plugin.go
  plugins/sandbox/controller.go
  plugins/services/containers/local.go
  plugins/services/content/store.go
  plugins/services/events/service.go
  plugins/services/events/ttrpc.go
  plugins/services/namespaces/local.go
  plugins/services/sandbox/controller_service.go
  plugins/services/tasks/local.go
Labels: size/M

#9867 adds mediatype to oci index record
  core/images/archive/exporter.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/XS
