Repository containerd/containerd, pull requests merged in 2024-12, with the labels that each got.

#11073 docs: fix snapshots api import
  docs/PLUGINS.md
Labels: kind/docs, needs-ok-to-test, size/XS

#11043 The task_dir successfully cleans when the file is absent.
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
Labels: kind/bug, needs-ok-to-test, area/runtime, size/XS

#11069 Fix panic due to nil dereference cgroups v2
  cmd/containerd-shim-runc-v2/runc/container.go
Labels: kind/bug, cherry-pick/1.6.x, cherry-pick/1.7.x, area/runtime, size/M, cherry-pick/2.0.x

#11102 update to go1.23.4 / go1.22.10
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/S, github_actions, area/toolchain, cherry-pick/2.0.x

#10930 CI: update Fedora to 41
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/S, github_actions, cherry-pick/2.0.x

#11099 [release/1.7] Fix panic due to nil dereference cgroups v2
  runtime/v2/runc/container.go
Labels: kind/bug, area/runtime, size/M

#11100 [release/1.6] Fix panic due to nil dereference cgroups v2
  runtime/v2/runc/container.go
Labels: kind/bug, area/runtime, size/M

#11130 update xx to v1.6.1 for compatibility with alpine 3.21 and file 5.46+
  .github/workflows/release/Dockerfile
Labels: dependencies, size/XS, cherry-pick/2.0.x

#11086 ctr pull should unpack for default platform when transfer service is used
  cmd/ctr/commands/images/pull.go
Labels: kind/bug, size/S, area/distribution, cherry-pick/2.0.x

#11061 Complete cri grpc plugin config migration
  integration/client/migration_test.go
  integration/client/testdata/custom-1.7.toml
  plugins/cri/cri.go
  plugins/cri/cri_test.go
Labels: area/cri, size/L, cherry-pick/2.0.x

#11135 Update go-cni for CNI STATUS
  go.mod
  go.sum
  vendor/github.com/containerd/go-cni/README.md
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/testutils.go
  vendor/modules.txt
Labels: dependencies, size/L

#11112 [release/1.6] update build to go1.22.10, test go1.23.4
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go, area/toolchain

#11111 [release/1.7] update build to go1.22.10, test go1.23.4
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go, area/toolchain

#11118 cmd/ctr: allow user to syncfs during unpacking image locally
  cmd/ctr/commands/images/import.go
  cmd/ctr/commands/images/mount.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/run/run.go
  cmd/ctr/commands/run/run_unix.go
  cmd/ctr/commands/run/run_windows.go
  cmd/ctr/commands/snapshots/snapshots.go
Labels: needs-ok-to-test, size/M

#11141 update runc binary to v1.2.3
  script/setup/runc-version
Labels: cherry-picked/1.6.x, cherry-picked/1.7.x, size/XS, cherry-picked/2.0.x

#11104 internal/cri: should not apply IoOwner options if it's not user namespace
  internal/cri/server/container_start_linux.go
Labels: area/cri, size/S, cherry-pick/2.0.x

#11142 [release/2.0 backport] update runc binary to v1.2.3
  script/setup/runc-version
Labels: size/XS

#11145 vendor: update golang.org/x/ dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: dependencies, size/L

#11144 [release/1.6 backport] update runc binary to v1.2.3
  script/setup/runc-version
Labels: area/runtime, size/XS

#11143 [release/1.7 backport] update runc binary to v1.2.3
  script/setup/runc-version
Labels: size/XS

#10646 Report an error when cni confDir removed
  internal/cri/server/cni_conf_syncer.go
Labels: kind/bug, area/cri, ok-to-test, size/XS

#10851 test: prevent segfault in imageverifier test
  pkg/imageverifier/bindir/bindir_test.go
Labels: needs-ok-to-test, kind/test, size/XS

#11158 [release/2.0] Prepare release notes for v2.0.1
  .mailmap
  releases/v2.0.1.toml
  version/version.go
Labels: area/cri, area/runtime, size/M, area/distribution

#11180 Update golangci-lint version in dev tools script
  script/setup/install-dev-tools
Labels: needs-ok-to-test, size/XS, go, area/toolchain

#11185 Update golangci to 1.60.3
  .github/workflows/ci.yml
  .golangci.yml
Labels: size/XS, github_actions, area/toolchain

#11181 build(deps): bump golang.org/x/net from 0.30.0 to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/modules.txt
Labels: dependencies, size/XL, go
