Repository containerd/containerd, pull requests merged in 2024-05, with the labels that each got.

#10138 document usage and design of blockfile snapshotter
  docs/snapshotters/README.md
  docs/snapshotters/blockfile.md
Labels: kind/docs, needs-ok-to-test, size/L

#10157 docs: correct the typo in the documentation
  docs/man/containerd-config.toml.5.md
Labels: needs-ok-to-test, size/XS

#10128 Perform file sync outside of lock on Commit
  core/content/content.go
  core/metadata/content.go
  plugins/content/local/writer.go
Labels: ok-to-test, size/S

#8567 container.Checkpoint(), WithRestoreImage(): use ocispec.AnnotationRefName
  client/container.go
  client/container_restore_opts.go
Labels: size/XS

#9657 content: add a BlobReadSeeker to allow multipart blob uploads
  core/content/helpers.go
Labels: needs-ok-to-test, size/S

#9736 sandbox: Store bootstrap parameters in sandbox metadata and shim get them from sandbox metadata rather than other shim's bootstrap.json file.
  api/next.pb.txt
  api/services/sandbox/v1/sandbox.pb.go
  api/services/sandbox/v1/sandbox.proto
  client/task_opts.go
  core/runtime/runtime.go
  core/runtime/v2/binary.go
  core/runtime/v2/runc/options/next.pb.txt
  core/runtime/v2/runc/options/oci.pb.go
  core/runtime/v2/runc/options/oci.proto
  core/runtime/v2/shim.go
  core/runtime/v2/shim_manager.go
  core/sandbox/controller.go
  core/sandbox/proxy/controller.go
  internal/cri/server/container_start.go
  internal/cri/server/restart.go
  internal/cri/server/sandbox_run.go
  internal/cri/store/sandbox/sandbox.go
  plugins/sandbox/controller.go
  plugins/services/tasks/local.go
Labels: impact/changelog, ok-to-test, size/XL

#10162 Cleanup local transfer interface
  core/transfer/local/pull.go
  core/transfer/local/transfer.go
  plugins/transfer/plugin.go
Labels: size/M

#10165 [release/1.7] Handle unsupported config versions
  services/server/config/config.go
Labels: cherry-pick/1.6.x, size/S

#9781 core/runtime: Check shim PluginInfo to enforce idmap support
  cmd/containerd-shim-runc-v2/process/init.go
  cmd/containerd-shim-runc-v2/process/utils.go
  core/runtime/v2/task_manager.go
Labels: ok-to-test, size/L

#10163 Add support for ttrpc in transfer and streaming service
  client/transfer.go
  core/streaming/proxy/streaming.go
  core/transfer/proxy/transfer.go
Labels: size/L

#10164 Update ctr shim subcommand to task v3
  cmd/ctr/commands/shim/shim.go
Labels: size/XS

#10168 Add API release action
  .github/workflows/api-release.yml
Labels: size/M

#10167 Prepare release notes for api/v1.8.0-rc.0
  api/releases/v1.8.0-rc.toml
Labels: size/S

#10169 CI: bump up crun to 1.15
  script/setup/crun-version
Labels: kind/test, size/XS

#10171 core/metadata: failfast on content.Commit
  core/metadata/content.go
Labels: size/S

#10178 Update containerd api to v1.8.0-rc.0
  Makefile
  go.mod
  go.sum
  releases/README.md
  vendor/github.com/containerd/containerd/api/LICENSE
  vendor/modules.txt
Labels: size/L

#9960 Return correct error if CRIU binary is missing
  internal/cri/server/container_checkpoint_linux.go
Labels: ok-to-test, size/S

#10176 remove go1.21.9 from CI matrix
  .github/workflows/ci.yml
Labels: size/XS

#9883 sandbox: modify sandbox client
  client/sandbox.go
Labels: needs-ok-to-test, size/S

#10174 Chore: Simplify some syscall error checks
  pkg/dialer/dialer_unix.go
  pkg/shim/util_unix.go
Labels: size/M

#10127 [release/1.6] Fix CRI snapshotter root path when not under containerd root
  pkg/cri/cri.go
  pkg/cri/server/service.go
  plugin/plugin.go
  services/server/config/config.go
  services/server/server.go
  snapshots/btrfs/plugin/plugin.go
  snapshots/devmapper/plugin/plugin.go
  snapshots/native/plugin/plugin.go
  snapshots/overlay/plugin/plugin.go
Labels: needs-ok-to-test, size/M

#9965 cri: support io by streaming API
  core/transfer/streaming/reader.go
  internal/cri/config/config.go
  internal/cri/io/container_io.go
  internal/cri/io/exec_io.go
  internal/cri/io/helpers.go
  internal/cri/server/container_create.go
  internal/cri/server/container_execsync.go
  pkg/cio/io.go
Labels: needs-ok-to-test, size/L

#9920 critools-version: v1.30.0
  .github/workflows/ci.yml
  script/critest.sh
  script/setup/critools-version
Labels: area/cri, kind/test, size/S

#10185 [release/1.6] Update image-spec
  go.mod
  go.sum
  images/converter/default.go
  images/converter/uncompress/uncompress.go
  images/diffid.go
  images/mediatypes.go
  integration/client/go.mod
  integration/client/go.sum
  integration/client/import_test.go
  oci/spec_opts.go
  pkg/cri/opts/spec_windows.go
  remotes/handlers_test.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: size/L

#10188 CI: bump up golangci-lint to v1.58.0
  .github/workflows/ci.yml
  .golangci.yml
Labels: size/S

#10175 Integration: Change to grpc.NewClient
  integration/main_test.go
  integration/remote/remote_image.go
  integration/remote/remote_runtime.go
  integration/remote/util/util_unix.go
  integration/remote/util/util_windows.go
Labels: size/M

#10194 Don't require vagrant tests in merge queues
  .github/workflows/ci.yml
Labels: size/XS

#10193 fix: delete sockets on shim exit
  integration/client/container_linux_test.go
  pkg/shim/shim.go
  pkg/shim/util_unix.go
  pkg/shim/util_windows.go
Labels: size/M

#10206 Update tooling to Go 1.22.3 for net/http bug fixes
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test, size/S

#10200 Preserve Unprivileged locked flags during remount of bind mounts
  core/mount/mount_linux.go
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/M

#10199 [release/1.6] Update metadata snapshotter to lease on already exists
  metadata/snapshot.go
  metadata/snapshot_test.go
Labels: size/L

#10198 [release/1.7] Update metadata snapshotter to lease on already exists
  metadata/snapshot.go
  metadata/snapshot_test.go
Labels: impact/changelog, size/L

#10202 Unpack fetch all
  cmd/ctr/commands/images/pull.go
  core/unpack/unpacker.go
Labels: impact/changelog, cherry-pick/1.7.x, size/M

#10207 [release/1.7] Update tooling to Go 1.21.10, 1.22.3 for net/http bug fixes
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test, size/S

#10208 [release/1.6] Update tooling to Go 1.21.10, 1.22.3 for net/http bug fixes
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test, size/S

#10214 [release/1.6] vendor: golang.org/x/net@v0.23.0
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/websocket/client.go
  vendor/golang.org/x/net/websocket/dial.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: needs-ok-to-test, size/XXL

#10219 Update instrumentation fuzzer with new flag
  contrib/fuzz/oss_fuzz_build.sh
Labels: cherry-pick/1.7.x, size/XS

#10218 Update platforms package to v0.2.0
  go.mod
  go.sum
  vendor/github.com/containerd/platforms/defaults.go
  vendor/github.com/containerd/platforms/platforms.go
  vendor/github.com/containerd/platforms/platforms_other.go
  vendor/github.com/containerd/platforms/platforms_windows.go
  vendor/modules.txt
Labels: size/M

#10212 [release/1.6] Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts
  mount/mount_linux.go
Labels: needs-ok-to-test, size/M

#10220 Update ttrpc tag to 1.2.4
  go.mod
  go.sum
  vendor/github.com/containerd/ttrpc/client.go
  vendor/modules.txt
Labels: size/M

#10210 [release/1.7] Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts
  mount/mount_linux.go
Labels: needs-ok-to-test, size/M

#10221 [release/1.7] Update ttrpc tag to 1.2.4
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/ttrpc/client.go
  vendor/modules.txt
Labels: size/M

#10234 [release/1.6] Handle unsupported config versions
  services/server/config/config.go
Labels: impact/changelog, size/S

#10233 [release/1.7] Unpack fetch all
  cmd/ctr/commands/images/pull.go
  pkg/unpack/unpacker.go
Labels: impact/changelog, size/M

#10209 [release/1.7] Use LOOP_CONFIGURE when creating loop devices
  mount/losetup_linux.go
Labels: impact/changelog, ok-to-test, size/S

#10075 docs: update registry config guide
  docs/cri/registry.md
  docs/hosts.md
Labels: needs-ok-to-test, easy-to-review, size/M

#10190 fix: modify streaming io url and add docs of sandboxer and io_type
  docs/cri/config.md
  internal/cri/io/container_io.go
  internal/cri/io/exec_io.go
  internal/cri/io/helpers.go
  internal/cri/server/restart.go
Labels: ok-to-test, size/M

#10235 [release/1.7] Prepare release notes for v1.7.17
  releases/v1.7.17.toml
  version/version.go
Labels: size/S

#10026 internal/cri: log ctr's exit event on info level
  internal/cri/server/events.go
Labels: needs-ok-to-test, size/XS

#10105 images: tests: Fix typos in the tests
  internal/cri/server/images/image_pull_test.go
Labels: ok-to-test, size/M

#10240 Prepare release notes for v2.0.0-rc.2
  .mailmap
  version/version.go
Labels: size/XS

#10238 Add support to set loopback to up
  docs/cri/config.md
  internal/cri/config/config.go
  internal/cri/config/config_unix.go
  internal/cri/config/config_windows.go
  internal/cri/server/sandbox_run.go
  internal/cri/server/sandbox_run_linux.go
  internal/cri/server/sandbox_run_other.go
  internal/cri/server/sandbox_run_windows.go
  internal/cri/server/service_linux.go
Labels: area/cri, size/L

#10251 Provide runtime options in plugin info
  core/runtime/v2/task_manager.go
Labels: size/XS

#10245 [release/1.6] Bump hcsshim and go-winio for go1.22 compat
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/Microsoft/go-winio/fileinfo.go
  vendor/github.com/Microsoft/hcsshim/.gitattributes
  vendor/github.com/Microsoft/hcsshim/.gitignore
  vendor/github.com/Microsoft/hcsshim/Protobuild.toml
  vendor/github.com/Microsoft/hcsshim/README.md
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
  vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/stats.pb.go
  vendor/github.com/Microsoft/hcsshim/internal/regstate/zsyscall_windows.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
  vendor/github.com/Microsoft/hcsshim/pkg/go-runhcs/runhcs.go
  vendor/modules.txt
Labels: size/XXL

#10255 [release/1.6] Prepare release notes for v1.6.32
  .mailmap
  releases/v1.6.32.toml
  version/version.go
Labels: size/S

#10257 core/image: fix usage of "unknown" platform
  core/images/image.go
Labels: size/XS

#10263 [release/1.6] Explicitly set release latest to false
  .github/workflows/release.yml
Labels: ok-to-test, size/XS

#10265 [release/1.7] Explicitly set release latest to true
  .github/workflows/release.yml
Labels: ok-to-test, size/XS

#10273 remove uses of platforms.Platform alias
  core/sandbox/controller.go
  core/sandbox/proxy/controller.go
  internal/cri/server/container_create.go
  internal/cri/server/container_create_test.go
  internal/cri/server/images/service.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/sandbox_service.go
  internal/cri/server/service.go
  internal/cri/server/service_test.go
  plugins/sandbox/controller.go
Labels: size/M

#10258 update pause image to 3.10
  contrib/ansible/cri-containerd.yaml
  docs/cri/config.md
  docs/cri/crictl.md
  integration/client/testdata/default-1.6.toml
  integration/client/testdata/default-1.7.toml
  integration/images/image_list.go
  integration/images/image_list.sample.toml
  internal/cri/config/config.go
  internal/cri/server/images/image_pull_test.go
  plugins/cri/images/plugin_test.go
Labels: ok-to-test, size/M

#10201 sandbox: do retry for wait to remote sandbox controller
  core/sandbox/proxy/controller.go
  internal/cri/server/events.go
Labels: ok-to-test, size/M

#10276 Update api minimum Go version to 1.21
  api/go.mod
Labels: size/XS

#10277 [release/1.7] remove uses of platforms.Platform alias
  pkg/cri/sbserver/container_create.go
  pkg/cri/sbserver/container_create_test.go
  pkg/cri/sbserver/podsandbox/controller.go
  plugins/sandbox/controller.go
  sandbox/controller.go
  sandbox/proxy/controller.go
Labels: size/M

#10264 Explicitly set release latest to false
  .github/workflows/release.yml
Labels: ok-to-test, size/XS

#10274 *: export RemoveVolatileOption for CRI image volumes
  core/mount/mount_test.go
  core/mount/temp.go
  integration/container_volume_linux_test.go
  integration/images/volume-ownership/Dockerfile
  internal/cri/opts/container.go
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/L
