Repository containerd/containerd, pull requests merged in 2024-10, with the labels that each got.

#10752 Prepare release notes for v2.0.0-rc.5
  version/version.go
Labels: impact/deprecation, kind/feature, area/cri, kind/cleanup, area/runtime, size/XS, area/distribution, area/client

#10757 Clean up some dependency trees for runc shim
  Makefile
  api/runtime/sandbox/v1/sandbox_grpc.pb.go
  api/runtime/task/v3/shim_grpc.pb.go
  api/services/containers/v1/containers_grpc.pb.go
  api/services/content/v1/content_grpc.pb.go
  api/services/diff/v1/diff_grpc.pb.go
  api/services/events/v1/events_grpc.pb.go
  api/services/images/v1/images_grpc.pb.go
  api/services/introspection/v1/introspection_grpc.pb.go
  api/services/leases/v1/leases_grpc.pb.go
  api/services/namespaces/v1/namespace_grpc.pb.go
  api/services/sandbox/v1/sandbox_grpc.pb.go
  api/services/snapshots/v1/snapshots_grpc.pb.go
  api/services/streaming/v1/streaming_grpc.pb.go
  api/services/tasks/v1/tasks_grpc.pb.go
  api/services/transfer/v1/transfer_grpc.pb.go
  api/services/version/v1/version_grpc.pb.go
  cmd/containerd-shim-runc-v2/manager/manager_linux.go
  cmd/containerd-shim-runc-v2/runc/util.go
  cmd/go-buildtag/main.go
  contrib/snapshotservice/service.go
  core/snapshots/proxy/convert.go
  core/snapshots/proxy/proxy.go
  core/snapshots/snapshotter.go
  go.mod
  go.sum
  plugins/services/snapshots/service.go
  vendor/github.com/containerd/containerd/api/LICENSE
  vendor/github.com/containerd/containerd/api/runtime/sandbox/v1/sandbox_grpc.pb.go
  vendor/github.com/containerd/containerd/api/runtime/task/v3/shim_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/containers/v1/containers_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/content/v1/content_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/diff/v1/diff_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/events/v1/events_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/images/v1/images_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/introspection/v1/introspection_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/leases/v1/leases_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/namespaces/v1/namespace_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/sandbox/v1/sandbox_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/snapshots/v1/snapshots_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/streaming/v1/streaming_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/transfer/v1/transfer_grpc.pb.go
  vendor/github.com/containerd/containerd/api/services/version/v1/version_grpc.pb.go
  vendor/modules.txt
Labels: kind/refactor, area/runtime, size/XL

#10723 Fix the race condition during GC of snapshots when client retries
  core/unpack/unpacker.go
Labels: kind/bug, ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, area/runtime, size/XS

#10760 script/setup/install-runc: Add trap statement to clean up tmp files
  script/setup/install-runc
Labels: needs-ok-to-test, size/XS, area/toolchain

#10761 More shim imports cleanup
  Makefile
  cmd/containerd-shim-runc-v2/main_tracing.go
  integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
  internal/pprof/plugin.go
  pkg/shim/shim.go
  pkg/tracing/plugin/ttrpc.go
  plugins/types.go
Labels: kind/refactor, area/runtime, size/L

#10767 [release/1.7] Add check for CNI plugins before tearing down pod network
  pkg/cri/server/sandbox_stop.go
Labels: area/cri, ok-to-test, size/XS

#10766 [release/1.6] Add check for CNI plugins before tearing down pod network
  pkg/cri/server/sandbox_stop.go
Labels: area/cri, ok-to-test, size/XS

#10764 [release/1.6] Fix the race condition during GC of snapshots when client retries
  unpacker.go
Labels: kind/bug, ok-to-test, area/snapshotter, size/XS

#10774 [release/1.7 backport] Bump crun to 1.16.1
  script/setup/crun-version
Labels: needs-ok-to-test, area/runtime, size/XS

#10777 core/runtime: Fix a typo in error message
  core/runtime/v2/shim.go
Labels: needs-ok-to-test, kind/cleanup, size/XS

#10784 [release/1.6 backport] Update runner images to macOS13
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/XS, github_actions

#10783 [release/1.7 backport] Update runner images to macOS13
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/XS, github_actions

#10787 update runc binary to 1.1.15
  script/setup/runc-version
Labels: size/XS

#10772 update to go1.23.2,go1.22.8
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: needs-ok-to-test, size/S, github_actions, go, area/toolchain

#10792 [release/1.7] Add errdefs aliases
  errdefs/errors.go
  errdefs/errors_test.go
  go.mod
  go.sum
  integration/client/go.mod
  integration/client/go.sum
  vendor/github.com/containerd/errdefs/LICENSE
  vendor/github.com/containerd/errdefs/README.md
  vendor/github.com/containerd/errdefs/errors.go
  vendor/github.com/containerd/errdefs/resolve.go
  vendor/modules.txt
Labels: impact/changelog, dependencies, size/XXL, go

#10776 [release/1.7 backport] TestNewBinaryIOCleanup: fix a comment, minor rewrite
  pkg/process/io_test.go
Labels: needs-ok-to-test, size/M

#10801 [release/1.7] prow: allow ENABLE_CRI_SANDBOXES to be configured
  contrib/gce/configure.sh
  test/e2e_node/init.yaml
Labels: area/cri, size/S

#10809 [release/1.6 backport] update to go1.23.2,go1.22.8
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test, size/S, github_actions, go, area/toolchain

#10808 [release/1.7 backport] update to go1.23.2,go1.22.8
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: ok-to-test, size/S, github_actions, area/toolchain

#10813 [release/1.7] bump golangci/golangci-lint-action from 4 to 6
  .github/workflows/ci.yml
Labels: needs-ok-to-test, cherry-pick/1.6.x, size/XS, github_actions

#10821 Switch from actuated.dev to GH Action runners for arm64
  .github/workflows/ci.yml
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, size/S, github_actions

#10822 [release/1.7 backport] Switch from actuated.dev to GH Action runners for arm64
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/S, github_actions

#10823 [release/1.6 backport] Switch from actuated.dev to GH Action runners for arm64
  .github/workflows/ci.yml
Labels: needs-ok-to-test, size/S, github_actions

#10817 CI: fix vagrant
  .github/workflows/ci.yml
  Vagrantfile
Labels: kind/test, size/M, github_actions

#10826 Revert "update runc binary to 1.1.15"
  script/setup/runc-version
Labels: dependencies, area/runtime, size/XS

#10802 [release/1.7] Prepare release notes for v1.7.23
  releases/v1.7.23.toml
  version/version.go
Labels: area/cri, area/runtime, size/S, area/distribution

#10721 Fix data loss in rootfs overlayfs when unmount of tmp dirs fail with idmap mounts
  core/mount/mount_linux.go
Labels: kind/bug, needs-ok-to-test, area/runtime, size/S

#10838 Revert "update runc binary to 1.1.15"
  script/setup/runc-version
Labels: dependencies, area/runtime, size/XS

#10815 metrics: Use UnmarshalTo instead of UnmarshalAny
  core/metrics/cgroups/v1/metrics.go
  core/metrics/cgroups/v2/metrics.go
Labels: size/S

#10814 [release/1.7] metrics: Use UnmarshalTo instead of UnmarshalAny
  metrics/cgroups/v1/metrics.go
  metrics/cgroups/v2/metrics.go
Labels: kind/bug, size/S

#10839 Handle teardown failure to avoid blocking cleanup
  internal/cri/server/sandbox_run.go
Labels: area/cri, ok-to-test, cherry-picked/1.6.x, cherry-picked/1.7.x, size/XS

#10696 Add containerd 2.0 doc
  docs/containerd-2.0.md
Labels: kind/docs, needs-ok-to-test, size/L

#10656 Remove deprecated cri SandboxInfo RuntimeHandler
  internal/cri/server/podsandbox/sandbox_status.go
  internal/cri/server/sandbox_status.go
  internal/cri/types/sandbox_info.go
Labels: area/cri, kind/cleanup, size/M

#9882 sandbox: make podsandbox controller plugin type of PodSandboxPlugin
  client/client.go
  client/services.go
  cmd/containerd/server/server.go
  core/sandbox/proxy/controller.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/restart.go
  plugins/cri/cri.go
  plugins/services/sandbox/controller_service.go
  plugins/types.go
Labels: ok-to-test, size/L

#10845 Update `docs/containerd-2.0.md`
  README.md
  docs/containerd-2.0.md
Labels: kind/docs, easy-to-review, size/S

#10849 Format link text in containerd 2.0 doc for readability
  docs/containerd-2.0.md
Labels: kind/docs, needs-ok-to-test, size/S

#10798 Add After=dbus.service to containerd.service
  containerd.service
Labels: ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, area/runtime, size/XS

#10741 Allow `setgroups` in user namespaces
  pkg/sys/unshare_linux.go
  pkg/sys/unshare_linux_test.go
Labels: ok-to-test, area/runtime, size/S

#10850 containerd 2.0 guide: add image verifier plugins
  docs/containerd-2.0.md
Labels: kind/docs, size/XS

#10852 Update NRI documentation for containerd 2.0
  docs/NRI.md
Labels: kind/docs, needs-ok-to-test, size/S, area/nri

#10854 Update tracing docs for containerd 2.0
  docs/tracing.md
Labels: kind/docs, needs-ok-to-test, size/M

#10778 [release/1.6] Handle teardown failure to avoid blocking cleanup
  pkg/cri/server/sandbox_run.go
Labels: area/cri, needs-ok-to-test, size/XS

#10860 [release/1.6 backport] Add After=dbus.service to containerd.service
  containerd.service
Labels: needs-ok-to-test, area/runtime, size/XS

#10859 [release/1.7 backport] Add After=dbus.service to containerd.service
  containerd.service
Labels: needs-ok-to-test, size/XS

#10866 Update hcsshim version to v0.12.8
  go.mod
  go.sum
  script/setup/runhcs-version
  vendor/modules.txt
Labels: platform/windows, dependencies, size/S, go

#10878 CI: bump up crun to 1.17
  script/setup/crun-version
Labels: size/XS

#10881 docs: update min version for deprecation warnings
  docs/containerd-2.0.md
Labels: kind/docs, size/XS

#10882 docs: add command for finding schema 1 images
  docs/containerd-2.0.md
Labels: kind/docs, size/XS

#9982 Allow sections of Plugins to be merged, and not overwritten as entire sections.
  cmd/containerd/server/config/config.go
  cmd/containerd/server/config/config_test.go
Labels: impact/changelog, ok-to-test, size/L

#10864 Deduplicate some cri util functions
  internal/cri/server/container_create.go
  internal/cri/server/helpers.go
  internal/cri/server/helpers_test.go
  internal/cri/server/images/image_pull.go
  internal/cri/server/images/image_pull_test.go
  internal/cri/server/images/image_status_test.go
  internal/cri/server/podsandbox/helpers.go
  internal/cri/server/podsandbox/helpers_test.go
  internal/cri/server/podsandbox/sandbox_run.go
  internal/cri/server/podsandbox/sandbox_run_linux.go
  internal/cri/server/podsandbox/sandbox_run_windows.go
  internal/cri/util/references.go
  internal/cri/util/references_test.go
  internal/cri/util/util.go
  internal/cri/util/util_test.go
Labels: area/cri, kind/refactor, size/XL

#10884 deps: bump github.com/containerd/nri
  go.mod
  go.sum
  vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
  vendor/modules.txt
Labels: dependencies, size/S

#10887 Prepare release notes for v2.0.0-rc.6
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/api/LICENSE
  vendor/modules.txt
  version/version.go
Labels: size/L

#10883 CI: move crun from Ubuntu to Fedora
  .github/workflows/ci.yml
Labels: kind/test, size/M, github_actions

#10867 Lock store writer per digest and writer.
  plugins/content/local/locks.go
  plugins/content/local/locks_test.go
  plugins/content/local/store.go
  plugins/content/local/writer.go
Labels: needs-ok-to-test, kind/performance, size/M

#10892 Add back ZFS snapshotter
  cmd/containerd/builtins/builtins_freebsd.go
  cmd/containerd/builtins/zfs_linux.go
  go.mod
  go.sum
  vendor/github.com/containerd/zfs/v2/.gitignore
  vendor/github.com/containerd/zfs/v2/LICENSE
  vendor/github.com/containerd/zfs/v2/README.md
  vendor/github.com/containerd/zfs/v2/codecov.yml
  vendor/github.com/containerd/zfs/v2/plugin/plugin.go
  vendor/github.com/containerd/zfs/v2/zfs.go
  vendor/github.com/mistifyio/go-zfs/v3/.envrc
  vendor/github.com/mistifyio/go-zfs/v3/.gitignore
  vendor/github.com/mistifyio/go-zfs/v3/.golangci.yml
  vendor/github.com/mistifyio/go-zfs/v3/.yamllint
  vendor/github.com/mistifyio/go-zfs/v3/CHANGELOG.md
  vendor/github.com/mistifyio/go-zfs/v3/CONTRIBUTING.md
  vendor/github.com/mistifyio/go-zfs/v3/LICENSE
  vendor/github.com/mistifyio/go-zfs/v3/Makefile
  vendor/github.com/mistifyio/go-zfs/v3/README.md
  vendor/github.com/mistifyio/go-zfs/v3/Vagrantfile
  vendor/github.com/mistifyio/go-zfs/v3/error.go
  vendor/github.com/mistifyio/go-zfs/v3/lint.mk
  vendor/github.com/mistifyio/go-zfs/v3/rules.mk
  vendor/github.com/mistifyio/go-zfs/v3/shell.nix
  vendor/github.com/mistifyio/go-zfs/v3/utils.go
  vendor/github.com/mistifyio/go-zfs/v3/utils_notsolaris.go
  vendor/github.com/mistifyio/go-zfs/v3/utils_solaris.go
  vendor/github.com/mistifyio/go-zfs/v3/zfs.go
  vendor/github.com/mistifyio/go-zfs/v3/zpool.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#10793 Update sample `go test` commands in BUILDING.md
  BUILDING.md
Labels: kind/docs, needs-ok-to-test, size/S

#10895 Update ttrpc to v1.2.6 tag
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/XS, go

#10896 Update containerd plugin to v1.0.0
  go.mod
  go.sum
  vendor/github.com/containerd/plugin/.golangci.yml
  vendor/modules.txt
Labels: dependencies, size/S

#10899 pkg/protobuf: fix typo in godoc
  pkg/protobuf/proto/proto.go
  pkg/protobuf/types/types.go
Labels: kind/cleanup, size/XS

#10904 go.mod: github.com/containerd/imgcrypt v2.0.0-rc-1
  go.mod
  go.sum
  internal/cri/server/images/image_pull.go
  script/setup/imgcrypt-version
  vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
  vendor/github.com/AdamKorcz/go-118-fuzz-build/testing/f.go
  vendor/github.com/containerd/imgcrypt/v2/.gitignore
  vendor/github.com/containerd/imgcrypt/v2/.golangci.yml
  vendor/github.com/containerd/imgcrypt/v2/CHANGES
  vendor/github.com/containerd/imgcrypt/v2/LICENSE
  vendor/github.com/containerd/imgcrypt/v2/MAINTAINERS
  vendor/github.com/containerd/imgcrypt/v2/Makefile
  vendor/github.com/containerd/imgcrypt/v2/README.md
  vendor/github.com/containerd/imgcrypt/v2/images/encryption/client.go
  vendor/github.com/containerd/imgcrypt/v2/images/encryption/encryption.go
  vendor/github.com/containerd/imgcrypt/v2/payload.go
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/go.mozilla.org/pkcs7/.gitignore
  vendor/go.mozilla.org/pkcs7/.travis.yml
  vendor/go.mozilla.org/pkcs7/Makefile
  vendor/go.mozilla.org/pkcs7/README.md
  vendor/go.mozilla.org/pkcs7/ber.go
  vendor/go.mozilla.org/pkcs7/encrypt.go
  vendor/go.mozilla.org/pkcs7/sign.go
  vendor/go.mozilla.org/pkcs7/verify.go
  vendor/go.mozilla.org/pkcs7/verify_test_dsa.go
  vendor/modules.txt
Labels: dependencies, size/XL, go

#10894 local: avoid writing to content root on readonly store
  plugins/content/local/store.go
  plugins/content/local/store_test.go
Labels: kind/enhancement, cherry-pick/1.7.x, size/M

#10918 Update hcsshim to v0.12.9
  go.mod
  go.sum
  script/setup/runhcs-version
  vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/oc/errors.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
  vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/errdefs/grpc.go
  vendor/modules.txt
Labels: platform/windows, dependencies, size/L, go

#10907 config: v1Migrate: support DisabledPlugins and RequiredPlugins
  cmd/containerd/server/config/config.go
  cmd/containerd/server/config/config_test.go
Labels: kind/enhancement, size/M
