Repository containerd/containerd, pull requests merged in 2025-03, with the labels that each got.

#11116 Remove After=local-fs.target from containerd.service
  containerd.service
Labels: needs-ok-to-test, size/XS

#11461 Bump to newer opencontainers/image-spec @ v1.1.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: dependencies, size/S, go

#11481 CVE-2025-22868: upgrade golang.org/x/oauth2 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: dependencies, size/S, go

#11476 erofs-snapshotter: two bug-fixes
  docs/snapshotters/erofs.md
  plugins/snapshots/erofs/erofs_linux.go
Labels: kind/bug, size/S

#11080 Consolidate security profile logic into a common pkg
  internal/cri/server/container_create.go
  internal/cri/server/container_create_linux.go
  internal/cri/server/container_create_linux_test.go
  internal/cri/server/podsandbox/container_linux.go
  internal/cri/server/podsandbox/sandbox_run_linux.go
  internal/cri/sputil/apparmor_linux.go
  internal/cri/sputil/apparmor_linux_test.go
  internal/cri/sputil/seccomp_linux.go
  internal/cri/sputil/seccomp_linux_test.go
  internal/cri/sputil/securityprofile_linux.go
  internal/cri/util/util.go
  internal/cri/util/util_test.go
Labels: area/cri, kind/refactor, size/XXL

#11402 docs: add CRI Plugin Config runtime_path
  docs/cri/config.md
Labels: kind/docs, needs-ok-to-test, size/XS

#11330 device mapper:fix sometimes blkdiscard doesn't have --version flags
  plugins/snapshots/devmapper/blkdiscard/blkdiscard.go
  plugins/snapshots/devmapper/pool_device.go
Labels: needs-ok-to-test, size/S

#11482 CVE-2025-22869: upgrade golang.org/x/crypto to v0.35.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/S, go

#11319 [release/1.6] fix fatal error: concurrent map iteration and map write
  pkg/cri/streaming/portforward/httpstream.go
Labels: kind/bug, area/cri, ok-to-test, size/XS

#11489 e2e: use the shim bundled with containerd artifact
  contrib/gce/configure.sh
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, cherry-pick/2.0.x

#11479 ci: update GitHub Actions release runner to ubuntu-24.04
  .github/workflows/release.yml
Labels: size/XS, github_actions, area/toolchain

#11497 [release/2.0] build(deps): bump containerd/project-checks from 1.1.0 to 1.2.1
  .github/workflows/ci.yml
Labels: dependencies, size/XS, github_actions

#11500 [release/1.6] Remove hashicorp/go-multierror dependency and fix CI
  .github/workflows/ci.yml
  contrib/gce/configure.sh
  go.mod
  pkg/process/io.go
  runtime/v2/shim.go
  snapshots/devmapper/config.go
  snapshots/devmapper/config_test.go
  snapshots/devmapper/pool_device.go
  snapshots/devmapper/snapshotter.go
  snapshots/devmapper/snapshotter_test.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/group.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#11460 Update runtime-spec to v1.2.1
  go.mod
  go.sum
  vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
  vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
  vendor/modules.txt
Labels: dependencies, size/M, go

#11337 perf(applyNaive): avoid walking the tree for each file in the same directory
  pkg/archive/tar.go
Labels: needs-ok-to-test, kind/performance, size/M

#11327 Don't produce unnecessary logs when encountering attestations
  core/images/image.go
  core/images/mediatypes.go
  core/remotes/handlers.go
Labels: needs-ok-to-test, cherry-pick/1.6.x, cherry-pick/1.7.x, size/S, cherry-pick/2.0.x

#11514 [release/2.0] update build to go1.23.7, test go1.24.1
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go, area/toolchain

#11513 update to go1.23.7 / go1.24.1
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go, area/toolchain

#11518 add name in package version
  internal/nri/nri.go
  version/version.go
Labels: needs-ok-to-test, size/XS, area/nri, cherry-pick/2.0.x

#11421 [release/1.6] update build to go1.23.7, test go1.24.1
  .github/actions/install-go/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  Vagrantfile
  contrib/Dockerfile.test
  script/setup/prepare_env_windows.ps1
Labels: size/M, github_actions, go, area/toolchain

#10365 Support container restore through CRI/Kubernetes
  .github/workflows/ci.yml
  api/go.mod
  api/go.sum
  client/container.go
  contrib/checkpoint/checkcriu.go
  contrib/checkpoint/checkpoint-restore-cri-test.sh
  contrib/checkpoint/checkpoint-restore-kubernetes-test.sh
  contrib/checkpoint/testdata/container_sleep.json
  contrib/checkpoint/testdata/sandbox_config.json
  contrib/checkpoint/testdata/sleep-restore.yaml
  contrib/checkpoint/testdata/sleep.yaml
  core/runtime/runtime.go
  core/runtime/v2/shim.go
  internal/cri/server/container_checkpoint.go
  internal/cri/server/container_checkpoint_linux.go
  internal/cri/server/container_create.go
  internal/cri/server/container_start.go
  internal/cri/server/container_status_test.go
  internal/cri/server/podsandbox/recover_test.go
  internal/cri/store/container/status.go
  plugins/services/tasks/local.go
  vendor/github.com/checkpoint-restore/go-criu/v7/stats/stats.pb.go
  vendor/github.com/checkpoint-restore/go-criu/v7/stats/stats.proto
  vendor/github.com/checkpoint-restore/go-criu/v7/stats/types.go
  vendor/github.com/checkpoint-restore/go-criu/v7/stats/utils.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu_linux.go
  vendor/github.com/checkpoint-restore/go-criu/v7/utils/criu_unsupported.go
  vendor/k8s.io/kubelet/pkg/types/labels.go
  vendor/modules.txt
Labels: kind/feature, area/cri, needs-ok-to-test, area/criu, size/XXL

#11534 add k8s 1.32 to support table and as tested containerd supported branches at the time of release
  RELEASES.md
Labels: kind/docs, area/cri, size/XS

#11529 [release/2.0] Fix incorrect runtime name being passed to NRI
  internal/nri/nri.go
  version/version.go
Labels: needs-ok-to-test, size/XS, area/nri

#11508 client: Respect `client.WithTimeout` option
  client/client.go
Labels: kind/bug, needs-ok-to-test, size/XS, area/client, cherry-pick/2.0.x

#11510 Prepare release notes for v2.1.0-beta.0
  .mailmap
  RELEASES.md
  integration/issue10467_linux_test.go
  integration/release_upgrade_linux_test.go
  integration/release_upgrade_utils_linux_test.go
  releases/v2.1.0-beta.toml
  version/version.go
Labels: area/cri, dependencies, area/runtime, size/L, area/nri

#11512 fix: repeat args from sub-func call
  integration/client/export_test.go
Labels: ok-to-test, size/XS

#11538 [release/1.7] Update image type checks to avoid unnecessary logs for attestations
  images/image.go
  images/mediatypes.go
  remotes/handlers.go
Labels: impact/changelog, size/S

#11544 Bump github.com/go-jose/go-jose/v4 from 4.0.4 to 4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/modules.txt
Labels: dependencies, cherry-pick/1.6.x, cherry-pick/1.7.x, size/M, go, cherry-pick/2.0.x

#11539 [release/1.6] Prepare release notes for v1.6.38
  releases/v1.6.38.toml
  version/version.go
Labels: area/cri, size/S

#11540 [release/1.7] Prepare release notes for v1.7.27
  .mailmap
  releases/v1.7.27.toml
  version/version.go
Labels: size/M

#11541 [release/2.0] Prepare release notes for v2.0.4
  releases/v2.0.4.toml
  version/version.go
Labels: size/S

#11555 Fix CI lint error
  pkg/oci/spec_opts.go
  pkg/oci/spec_opts_linux_test.go
Labels: size/S, github_actions, go

#11574 bump golang.org/x/net from 0.33.0 to 0.37.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/S, go

#11582 go.mod: tags.cncf.io/container-device-interface v1.0.1
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
  vendor/modules.txt
  vendor/tags.cncf.io/container-device-interface/pkg/cdi/spec.go
Labels: dependencies, size/XXL, go, cherry-pick/2.0.x

#11311 Support multiple cni plugin bin dirs
  RELEASES.md
  docs/cri/config.md
  internal/cri/config/config.go
  internal/cri/config/config_test.go
  internal/cri/config/config_unix.go
  internal/cri/config/config_windows.go
  internal/cri/server/service_linux.go
  internal/cri/server/service_windows.go
  pkg/deprecation/deprecation.go
  plugins/cri/runtime/plugin.go
  plugins/cri/runtime/plugin_test.go
Labels: kind/feature, area/cri, size/L

#11452 Update max container log line size json field
  internal/cri/config/config.go
Labels: area/cri, ok-to-test, size/XS

#11616 downgrade cni version in CI test
  .devcontainer/setup.sh
  .github/workflows/ci.yml
  script/setup/install-cni
Labels: needs-ok-to-test, kind/test, size/XS

#11569 update taskOptions based on runtimeOptions when creating a task
  client/container.go
  client/task.go
  client/task_opts.go
  client/task_opts_unix.go
  core/runtime/v2/task_manager.go
  integration/client/client_unix_test.go
  integration/client/container_linux_test.go
Labels: priority/P2, area/runtime, size/L, cherry-pick/2.0.x

#11475 fix: call checkCopyShimLogError(shimCtx) to avoid expected error log flood
  core/runtime/v2/shim.go
Labels: needs-ok-to-test, cherry-pick/1.7.x, area/runtime, size/XS, cherry-pick/2.0.x

#11619 [release/1.7] vendor: github.com/go-jose/go-jose/v3 v3.0.4
  go.mod
  go.sum
  integration/client/go.sum
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/modules.txt
Labels: ok-to-test, dependencies, size/S, go

#11588 Fix the panic caused by the failure of RunPodSandbox
  internal/cri/server/podsandbox/events.go
Labels: kind/bug, area/cri, ok-to-test, size/XS, cherry-pick/2.0.x

#11579 cri: fix lost container exit events if they arrive before info is cached
  internal/cri/server/restart.go
Labels: kind/bug, area/cri, ok-to-test, size/S
