Repository containerd/containerd, pull requests merged in 2025-09, with the labels that each got.

#12270 pkg/cio: Close(): use errors.Join to return all errors
  pkg/cio/io.go
Labels: size/XS

#12294 doc: add k8s 1.34 into support matrix
  RELEASES.md
Labels: kind/docs, size/XS

#12297 docs: Update 1.7 LTS support timeline
  RELEASES.md
Labels: kind/docs, size/XS

#11921 Tar unpack progress through transfer service
  cmd/ctr/commands/images/pull.go
  core/diff/apply/apply.go
  core/diff/diff.go
  core/diff/proxy/differ.go
  core/transfer/local/progress.go
  core/transfer/local/pull.go
Labels: impact/changelog, size/L, area/distribution

#12320 vendor: opencontainers/runtime-tools v0.9.1-0.20250523060157-0ea5ed0382a2
  go.mod
  go.sum
  vendor/github.com/moby/sys/capability/CHANGELOG.md
  vendor/github.com/moby/sys/capability/LICENSE
  vendor/github.com/moby/sys/capability/README.md
  vendor/github.com/moby/sys/capability/capability.go
  vendor/github.com/moby/sys/capability/capability_linux.go
  vendor/github.com/moby/sys/capability/capability_noop.go
  vendor/github.com/moby/sys/capability/enum.go
  vendor/github.com/moby/sys/capability/enum_gen.go
  vendor/github.com/moby/sys/capability/syscall_linux.go
  vendor/github.com/opencontainers/runtime-tools/generate/generate.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_action.go
  vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/lastcap.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_linux.go
  vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
  vendor/github.com/syndtr/gocapability/capability/capability.go
  vendor/github.com/syndtr/gocapability/capability/capability_noop.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#12323 Add conf.d include in the default config
  cmd/containerd/command/config.go
  defaults/defaults_unix.go
  defaults/defaults_windows.go
Labels: impact/changelog, kind/feature, size/XS

#12322 Make E2E workflow a required check
  .github/workflows/ci.yml
  .github/workflows/node-e2e.yml
Labels: size/S, github_actions
