Repository containerd/containerd, pull requests merged in 2025-10, with the labels that each got.

#12346 Prepare release notes for api/v1.10.0-beta.0
  api/releases/v1.10.0-beta.toml
Labels: area/runtime, size/S

#12348 1.6 is EOL
  RELEASES.md
Labels: impact/deprecation, size/XS

#12356 Fix gha api release file path
  .github/workflows/api-release.yml
Labels: size/XS, github_actions
