Repository containerd/containerd, pull requests merged in 2025-04, with the labels that each got.

#11608 pkg/sys: improve GetLocalListener/CreateUnixSocket error message
  pkg/sys/socket_unix.go
Labels: ok-to-test, kind/refactor, size/XS

#11641 Set default differ for the default unpack config of transfer service
  defaults/defaults_linux.go
  defaults/defaults_unix_nolinux.go
  plugins/transfer/plugin_defaults_other.go
Labels: cherry-pick/1.7.x, size/XS, area/distribution, cherry-pick/2.0.x

#11649 fix call fmt.Errorf with wrong error
  core/metadata/migrations.go
  core/runtime/v2/shim_manager.go
  pkg/sys/unshare_linux.go
Labels: kind/bug, needs-ok-to-test, size/S

#11666 avoid import to testing pkg outside of tests
  plugins/content/local/helper_test.go
Labels: size/XS, cherry-pick/2.0.x

#11546 [hosts] wrong explicitTLS value when dialTimeout is set
  core/remotes/docker/config/hosts.go
Labels: kind/bug, size/L

#11670 Prevent panic in Docker pusher.
  core/remotes/docker/pusher.go
Labels: kind/bug, needs-ok-to-test, size/S, area/distribution, cherry-pick/2.0.x

#11685 release: use Ubuntu 22.04 (glibc 2.35)
  .github/workflows/release.yml
  .github/workflows/release/Dockerfile
  releases/v2.1.0-beta.toml
Labels: impact/changelog, size/S, github_actions, area/toolchain, cherry-pick/2.0.x

#11688 [release/2.0] backport: Set default differ for the default unpack config of transfer service
  defaults/defaults_snapshotter_linux.go
  defaults/defaults_snapshotter_unix.go
  plugins/transfer/plugin_defaults_other.go
Labels: size/XS

#11689 [release/1.7] backport: Set default differ for the default unpack config of transfer service
  plugins/transfer/plugin.go
  snapshotter_default_linux.go
  snapshotter_default_unix.go
  snapshotter_default_windows.go
Labels: size/XS

#11681 Remove the support for Schema 1 images
  RELEASES.md
  client/client.go
  client/client_opts.go
  client/pull.go
  cmd/ctr/commands/content/fetch.go
  core/images/labels.go
  core/remotes/docker/fetcher.go
  core/remotes/docker/resolver.go
  core/remotes/docker/schema1/converter.go
  integration/client/client_test.go
  integration/client/client_unix_test.go
  integration/client/image_test.go
  integration/containerd_image_test.go
  integration/images/image_list.go
  internal/cri/server/images/image_pull.go
  internal/cri/util/references.go
  internal/cri/util/references_test.go
  pkg/deprecation/deprecation.go
  plugins/services/images/local.go
Labels: impact/changelog, impact/deprecation, size/XL

#11710 [release/2.0] Disable criu test on arm64
  .github/workflows/ci.yml
  script/critest.sh
Labels: size/S, github_actions

#11696 Fixing install instructions for Windows
  docs/getting-started.md
Labels: kind/docs, needs-ok-to-test, size/XS

#11006 Add content create event
  api/events/content.pb.go
  api/events/content.proto
  api/events/content_fieldpath.pb.go
  api/next.pb.txt
  core/metadata/content.go
  go.mod
  go.sum
  vendor/github.com/containerd/containerd/api/LICENSE
  vendor/github.com/containerd/containerd/api/events/content.pb.go
  vendor/github.com/containerd/containerd/api/events/content.proto
  vendor/github.com/containerd/containerd/api/events/content_fieldpath.pb.go
  vendor/modules.txt
Labels: kind/feature, needs-ok-to-test, size/XL

#11683 Remove deprecated dynamic library plugins
  RELEASES.md
  cmd/containerd/server/config/config.go
  cmd/containerd/server/server.go
  pkg/deprecation/deprecation.go
  vendor/github.com/containerd/plugin/dynamic/dynamic.go
  vendor/github.com/containerd/plugin/dynamic/dynamic_supported.go
  vendor/github.com/containerd/plugin/dynamic/dynamic_unsupported.go
  vendor/modules.txt
Labels: impact/changelog, kind/cleanup, size/L

#11684 config: postpone planned v2.1 deprecations to v2.2
  RELEASES.md
  pkg/deprecation/deprecation.go
Labels: impact/changelog, size/S

#11691 change criService.runtimeHandlers slice to a map
  internal/cri/server/container_create.go
  internal/cri/server/service.go
  internal/cri/server/status.go
Labels: area/cri, kind/refactor, size/M

#11714 chore: fix broken links to https://docs.docker.com/registry
  core/remotes/docker/auth/fetch.go
  core/remotes/docker/authorizer.go
  core/remotes/docker/resolver_test.go
  core/remotes/docker/scope.go
Labels: needs-ok-to-test, kind/cleanup, size/S

#11705 ci: update go 1.24.2, 1.23.8
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go

#11713 [release/2.0] Prepare release notes for v2.0.5
  releases/v2.0.5.toml
  version/version.go
Labels: area/cri, area/runtime, size/S, area/distribution

#11717 [release/2.0] Update go to 1.23.8
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: impact/changelog, size/S, github_actions, go, area/toolchain

#11612 [CRI] store extension when create sandbox in metadata store
  internal/cri/server/sandbox_run.go
Labels: area/cri, ok-to-test, size/S

#11092 Add cri headers and hosts.toml header to auth requests
  core/remotes/docker/authorizer.go
  core/remotes/docker/config/hosts.go
  core/remotes/docker/config/hosts_resolver_test.go
  core/remotes/docker/resolver.go
  internal/cri/server/images/image_pull.go
Labels: kind/bug, area/cri, size/L

#11195 Transfer Service: enable to pass annotations to remote snapshotters
  core/transfer/local/pull.go
Labels: size/XS, area/distribution

#11709 Fix cross-repo mount fallback after authorization failure
  core/remotes/docker/pusher.go
  core/remotes/docker/pusher_test.go
Labels: kind/bug, size/L, area/distribution, cherry-pick/2.0.x

#11700 client: fix returned error in the defer function
  client/container.go
  client/task.go
Labels: size/S, area/client

#11603 erofs-differ: implement fast differ with DiffDirChanges()
  plugins/diff/erofs/differ_linux.go
  plugins/snapshots/erofs/erofsutils/mount_linux.go
Labels: kind/performance, size/L

#11727 Add loong64 seccomp support
  contrib/seccomp/seccomp_default.go
Labels: ok-to-test, area/runtime, size/XS

#11723 erofsutils: MountsToLayer slight optimizations
  plugins/snapshots/erofs/erofsutils/mount_linux.go
Labels: size/S

#11675 cri,nri: add missing option to allow plugins to inject devices using CDI.
  internal/cri/nri/nri_api_linux.go
Labels: area/cri, size/M, area/nri

#11722 [release 1.7] Fix CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
  contrib/Dockerfile.test
  script/critest.sh
Labels: size/M, github_actions

#11547 Fix upgrade tests for 1.7
  integration/issue10467_linux_test.go
  integration/release_upgrade_linux_test.go
  integration/release_upgrade_utils_linux_test.go
Labels: size/L

#11730 [CI] Fix vagrant
  .github/workflows/ci.yml
Labels: cherry-pick/1.7.x, size/XS, github_actions, cherry-pick/2.0.x

#11735 cri: do not set sandbox id when using podsandbox type
  internal/cri/server/container_create.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/podsandbox/types/podsandbox.go
Labels: kind/enhancement, area/cri, ok-to-test, area/runtime, size/S, cherry-pick/2.0.x

#11741 [release/2.0] Fix issue preventing some v2 shims from shutting down properly
  internal/cri/server/container_create.go
  internal/cri/server/podsandbox/controller.go
  internal/cri/server/podsandbox/types/podsandbox.go
Labels: impact/changelog, area/cri, size/S

#11721 [release 1.7] remotes/docker/authorizer.go: invalidate auth tokens when they expire.
  remotes/docker/auth/fetch.go
  remotes/docker/authorizer.go
Labels: size/M, area/distribution

#10745 Add no_sync option to boost boltDB performance on ephemeral environments
  core/snapshots/storage/metastore.go
  plugins/metadata/plugin.go
Labels: impact/changelog, kind/performance, size/M

#11729 Move erofsutils to internal
  internal/erofsutils/mount_linux.go
  plugins/diff/erofs/differ_linux.go
  plugins/snapshots/erofs/erofs_linux.go
Labels: kind/refactor, size/S

#11746 Revert criserver metrics subsystem back to cri
  internal/cri/server/metrics.go
Labels: kind/bug, area/cri, ok-to-test, size/XS, cherry-pick/2.0.x

#8515 Update CRI to use transfer service for image pull by default
  client/client.go
  client/services.go
  core/transfer/registry/registry.go
  docs/cri/config.md
  integration/build_local_containerd_helper_test.go
  integration/build_local_containerd_helper_test_linux.go
  integration/client/restart_monitor_test.go
  integration/image_pull_timeout_test.go
  internal/cri/config/config.go
  internal/cri/config/config_test.go
  internal/cri/server/images/image_pull.go
  internal/cri/server/images/image_pull_test.go
  internal/cri/server/images/service.go
  plugins/cri/images/plugin.go
  plugins/transfer/plugin.go
  plugins/types.go
Labels: area/cri, ok-to-test, size/XL

#11733 erofs-differ: support EROFS native image layers
  plugins/diff/erofs/differ_linux.go
Labels: size/M

#11693 use lazyregexp to compile regexes on first use
  .golangci.yml
  internal/cri/bandwidth/linux.go
  internal/lazyregexp/lazyregexp.go
  internal/lazyregexp/lazyregexp_test.go
  pkg/identifiers/validate.go
  pkg/progress/writer.go
  pkg/reference/reference.go
  pkg/sys/filesys_windows.go
Labels: size/L

#11744 Add support for unpacking custom media types
  core/unpack/unpacker.go
  plugins/transfer/plugin.go
Labels: impact/changelog, size/M, area/distribution

#10762 Enable HTTP debug and trace for transfer based puller
  api/next.pb.txt
  api/types/transfer/registry.pb.go
  api/types/transfer/registry.proto
  cmd/ctr/commands/content/fetch.go
  cmd/ctr/commands/images/pull.go
  cmd/ctr/commands/images/push.go
  cmd/ctr/commands/resolver.go
  core/transfer/registry/registry.go
  pkg/httpdbg/debug.go
  vendor/github.com/containerd/containerd/api/types/transfer/registry.pb.go
  vendor/github.com/containerd/containerd/api/types/transfer/registry.proto
Labels: kind/enhancement, size/XL

#10177 Multipart layer fetch
  client/client.go
  client/pull.go
  cmd/ctr/commands/content/fetch.go
  core/remotes/docker/fetcher.go
  core/remotes/docker/fetcher_test.go
  core/remotes/docker/pusher.go
  core/remotes/docker/resolver.go
  core/remotes/resolver.go
  core/transfer/local/pull.go
  core/transfer/local/transfer.go
  core/transfer/registry/registry.go
  core/transfer/transfer.go
  integration/client/client_test.go
  internal/cri/config/config.go
  internal/cri/server/images/image_pull.go
  plugins/transfer/plugin.go
Labels: impact/changelog, ok-to-test, kind/performance, size/XL

#11751 Add release notes for api v1.9.0-rc.0
  api/releases/v1.9.0-rc.toml
Labels: size/S

#11752 Add release notes for v2.1.0-rc.0
  .mailmap
  RELEASES.md
  go.mod
  go.sum
  releases/v2.1.0-rc.toml
  vendor/github.com/containerd/containerd/api/LICENSE
  vendor/modules.txt
  version/version.go
Labels: dependencies, size/L

#11757 nri: replace type conversion functions removed from NRI.
  internal/cri/nri/nri_api_linux.go
Labels: size/M, area/nri

#11728 ctr shim: allow override to computed shim address
  cmd/ctr/commands/shim/shim.go
Labels: area/runtime, size/M

#11762 core/transfer/local: should not mark completed if it's not found
  core/transfer/local/progress.go
Labels: kind/bug, ok-to-test, size/S

#11748 fix: update containerd config dump to reflect plugin config migrations.
  cmd/containerd/command/config.go
Labels: kind/bug, size/M, cherry-pick/2.0.x

#11772 [release/2.0] fix: update containerd config dump to reflect plugin config migrations.
  cmd/containerd/command/config.go
Labels: kind/bug, size/M

#11643 docs: Fix typos to run userns with ctr
  docs/user-namespaces/README.md
  docs/user-namespaces/config.json
Labels: kind/docs, needs-ok-to-test, size/M
