Repository containerd/containerd, pull requests merged in 2025-01, with the labels that each got.

#11204 bump up ttrpc to use its MD.Clone
  go.mod
  go.sum
  pkg/namespaces/ttrpc.go
  pkg/namespaces/ttrpc_test.go
  vendor/github.com/containerd/ttrpc/metadata.go
  vendor/github.com/containerd/ttrpc/server.go
  vendor/modules.txt
Labels: dependencies, size/M, go

#11200 Bump seccomp version to be the same as one in runc repo
  script/setup/install-seccomp
Labels: needs-ok-to-test, size/XS

#11220 downgrade go-difflib and go-spew to tagged releases
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/S, go, cherry-pick/2.0.x

#11213 [release/2.0] Add a build tag to disable std `plugin` import
  BUILDING.md
  cmd/containerd/server/server.go
  cmd/containerd/server/server_no_plugins.go
  cmd/containerd/server/server_plugins.go
Labels: ok-to-test, size/M, area/toolchain

#11219 Avoid duplicated chain ID calculation in unpack
  core/unpack/unpacker.go
  core/unpack/unpacker_test.go
Labels: kind/performance, size/L, area/distribution

#11223 [release/1.7 backport] Fix `ip_pref` configuration option
  pkg/cri/sbserver/sandbox_run.go
  pkg/cri/sbserver/sandbox_run_test.go
  pkg/cri/server/sandbox_run.go
  pkg/cri/server/sandbox_run_test.go
Labels: kind/bug, area/cri, size/XS

#11241 Bump up otelttrpc to 0.1.0
  go.mod
  go.sum
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/modules.txt
Labels: dependencies, size/XXL, cherry-pick/2.0.x

#11189 Move fuzz tests to go native fuzz [part1]
  contrib/apparmor/apparmor_fuzzer.go
  contrib/apparmor/apparmor_fuzzer_test.go
  contrib/fuzz/archive_fuzz_test.go
  contrib/fuzz/archive_fuzzer.go
  contrib/fuzz/content_fuzz_test.go
  contrib/fuzz/cri_fuzzer.go
  contrib/fuzz/diff_fuzz_test.go
  contrib/fuzz/diff_fuzzer.go
  contrib/fuzz/exchange_fuzz_test.go
  contrib/fuzz/exchange_fuzzer.go
  contrib/fuzz/fuzz_images.go
  contrib/fuzz/images_fuzz_test.go
  contrib/fuzz/metadata_fuzz_test.go
  contrib/fuzz/metadata_fuzzer.go
  contrib/fuzz/oss_fuzz_build.sh
  contrib/fuzz/uuid_fuzzer.go
  core/remotes/docker/config/docker_fuzzer_test.go
  core/remotes/docker/converter_fuzz_test.go
  core/remotes/docker/fetcher_fuzz.go
  core/remotes/docker/fetcher_fuzz_test.go
  go.mod
  go.sum
  integration/client/container_fuzz_test.go
  internal/cri/server/images/image_fuzz_test.go
  pkg/archive/compression/compression_fuzzer_test.go
  plugins/content/local/content_local_fuzz_test.go
  script/go-test-fuzz.sh
  vendor/github.com/AdamKorcz/go-118-fuzz-build/LICENSE
  vendor/github.com/AdamKorcz/go-118-fuzz-build/testing/f.go
  vendor/github.com/AdamKorcz/go-118-fuzz-build/testing/t.go
  vendor/github.com/AdamKorcz/go-118-fuzz-build/testing/unsupported_funcs.go
  vendor/modules.txt
Labels: kind/test, size/XXL

#11161 make sure console master tty is closed on task exit
  cmd/containerd-shim-runc-v2/task/service.go
  integration/container_tty_leak_linux_test.go
Labels: kind/bug, cherry-pick/1.7.x, area/runtime, size/L

#11244 Fix go-cni race condition
  go.mod
  go.sum
  vendor/github.com/containerd/go-cni/cni.go
  vendor/github.com/containerd/go-cni/deprecated.go
  vendor/github.com/containerd/go-cni/mutex.go
  vendor/github.com/containerd/go-cni/mutex_deadlocks.go
  vendor/github.com/containerd/go-cni/result.go
  vendor/github.com/containerd/go-cni/testutils.go
  vendor/github.com/petermattis/goid/.gitignore
  vendor/github.com/petermattis/goid/LICENSE
  vendor/github.com/petermattis/goid/README.md
  vendor/github.com/petermattis/goid/goid.go
  vendor/github.com/petermattis/goid/goid_gccgo.go
  vendor/github.com/petermattis/goid/goid_go1.3.c
  vendor/github.com/petermattis/goid/goid_go1.3.go
  vendor/github.com/petermattis/goid/goid_go1.4.go
  vendor/github.com/petermattis/goid/goid_go1.4.s
  vendor/github.com/petermattis/goid/goid_go1.5.go
  vendor/github.com/petermattis/goid/goid_go1.5.s
  vendor/github.com/petermattis/goid/goid_slow.go
  vendor/github.com/petermattis/goid/runtime_gccgo_go1.8.go
  vendor/github.com/petermattis/goid/runtime_go1.23.go
  vendor/github.com/petermattis/goid/runtime_go1.5.go
  vendor/github.com/petermattis/goid/runtime_go1.6.go
  vendor/github.com/petermattis/goid/runtime_go1.9.go
  vendor/github.com/sasha-s/go-deadlock/.travis.yml
  vendor/github.com/sasha-s/go-deadlock/LICENSE
  vendor/github.com/sasha-s/go-deadlock/Readme.md
  vendor/github.com/sasha-s/go-deadlock/deadlock.go
  vendor/github.com/sasha-s/go-deadlock/deadlock_map.go
  vendor/github.com/sasha-s/go-deadlock/stacktraces.go
  vendor/github.com/sasha-s/go-deadlock/test.sh
  vendor/github.com/sasha-s/go-deadlock/trylock.go
  vendor/modules.txt
Labels: kind/bug, dependencies, size/XXL

#11240 ci: fix the issue of config_file unset
  script/test/utils.sh
Labels: kind/bug, size/XS

#11242 [release/2.0] Bump up otelttrpc to 0.1.0
  go.mod
  go.sum
  vendor/github.com/containerd/otelttrpc/metadata_supplier.go
  vendor/github.com/containerd/ttrpc/metadata.go
  vendor/github.com/containerd/ttrpc/server.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: dependencies, size/XXL, go

#11243 [release/1.7] Prepare release notes for v1.7.25
  releases/v1.7.25.toml
  version/version.go
Labels: size/S

#11165 Fix runtime platform loading in cri image plugin init
  plugins/cri/images/plugin.go
Labels: kind/bug, area/cri, size/M, cherry-pick/2.0.x

#11093 Clarify Go client API guidance
  RELEASES.md
Labels: size/S, area/client

#11167 Unify default transport in docker resolver
  core/remotes/docker/config/hosts.go
  core/remotes/docker/registry.go
  internal/cri/server/images/image_pull.go
Labels: size/M, area/distribution

#10980 Remove confusing warning in cri runtime config migration
  plugins/cri/runtime/plugin.go
  plugins/cri/runtime/plugin_test.go
Labels: area/cri, size/L

#11257 Update platforms to latest rc
  go.mod
  go.sum
  vendor/github.com/containerd/platforms/compare.go
  vendor/github.com/containerd/platforms/database.go
  vendor/github.com/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/platforms/platform_windows_compat.go
  vendor/github.com/containerd/platforms/platforms.go
  vendor/github.com/containerd/platforms/platforms_other.go
  vendor/github.com/containerd/platforms/platforms_windows.go
  vendor/modules.txt
Labels: dependencies, size/L, go, cherry-pick/2.0.x

#11132 Use a order-only-prerequisite for mandir creation
  Makefile
Labels: needs-ok-to-test, size/XS, area/toolchain

#11245 Prepare release notes for v2.0.2
  releases/v2.0.2.toml
  version/version.go
Labels: size/S

#11261 docs: fix some function names in comment
  cmd/ctr/commands/run/run.go
  contrib/apparmor/template.go
  contrib/fuzz/content_fuzz_test.go
  internal/cri/util/util.go
Labels: kind/docs, needs-ok-to-test, size/XS

#11262 Move CDI device spec out of the OCI package
  cmd/ctr/commands/run/run_unix.go
  internal/cri/opts/spec_linux.go
  pkg/cdi/oci_opt.go
  pkg/oci/spec_opts.go
Labels: area/runtime, size/L

#11249 Fix panics in CI fuzz integration tests
  integration/client/container_fuzz_test.go
Labels: kind/test, size/S

#10002 runtime/v2: add note about orphan process for runc-shim
  core/runtime/v2/README.md
Labels: needs-ok-to-test, size/XS

#11263 [release/2.0 backport] build(deps): bump google.golang.org/protobuf from 1.35.1 to 1.35.2
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/compiler/protogen/protogen.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/modules.txt
Labels: dependencies, size/L, go

#10955 Make ovl idmap mounts read-only
  core/mount/mount_idmapped_linux.go
  core/mount/mount_idmapped_linux_test.go
  core/mount/mount_linux.go
  core/mount/mount_linux_test.go
  plugins/snapshots/overlay/overlayutils/check.go
Labels: needs-ok-to-test, area/runtime, size/L

#11251 Move all fuzz tests to go native fuzz [part2]
  contrib/fuzz/containerd_import_fuzz_test.go
  contrib/fuzz/cri_server_fuzz_test.go
  contrib/fuzz/cri_server_fuzzer.go
  contrib/fuzz/daemon.go
  internal/cri/server/fuzz.go
Labels: kind/test, size/L

#11148 log: avoid using unsupported field by logrus
  core/runtime/v2/binary.go
Labels: kind/bug, needs-ok-to-test, area/runtime, size/XS

#10722 Support multiple uid/gid mappings [2/2]
  client/snapshotter_opts_unix.go
  cmd/ctr/commands/run/run_unix.go
  core/mount/mount_idmapped_linux.go
  core/mount/mount_idmapped_linux_test.go
  integration/client/container_idmapped_linux_test.go
  internal/cri/server/container_start_linux.go
  internal/userns/idmap.go
  internal/userns/idmap_test.go
  plugins/snapshots/overlay/overlay.go
  plugins/snapshots/overlay/overlay_test.go
Labels: area/runtime, size/XXL

#11276 client: add WithExtraDialOpts option
  client/client.go
  client/client_opts.go
Labels: size/S, area/client

#11277 update to go1.23.5 / go1.22.11
  .devcontainer/devcontainer.json
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: cherry-pick/1.6.x, cherry-pick/1.7.x, github_actions, go, area/toolchain, cherry-pick/2.0.x

#11298 [release/1.7] update build to go1.22.11, test go1.23.5
  .github/actions/install-go/action.yml
  .github/workflows/api-release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Vagrantfile
  contrib/Dockerfile.test
  contrib/fuzz/oss_fuzz_build.sh
  script/setup/prepare_env_windows.ps1
Labels: size/S, github_actions, go, area/toolchain

#11265 [release/2.0] Move CDI device spec out of the OCI package
  cmd/ctr/commands/run/run_unix.go
  internal/cri/opts/spec_linux.go
  pkg/cdi/oci_opt.go
  pkg/oci/spec_opts.go
Labels: area/cri, area/runtime, size/L

#11306 [release/1.7] fix fatal error: concurrent map iteration and map write
  pkg/cri/streaming/portforward/httpstream.go
Labels: kind/bug, area/cri, ok-to-test, size/XS
